### ISSUE TITLE
too many requirements

### ISSUE THREAD

**Issue by MrAmbiG** [dell/iDRAC-Redfish-Scripting#1]
So we configure atleast 50 iDRACs per day on an average from our team. We have a team size of around 80. The Get-ImportServerConfigurationProfilePreviewREDFISH requires that all of these guys should have access to a network share or should know the credentials. We should be able to give any path, preferably local path.
what we are trying to do is this.
1. configure one idrac
2. import and save the configuration of that on our local machine
3. push it to all the others
or
give target idrac ip, give source idrac ip then the settings should get copied.

**Comment by tehbluemuppetz** [comment]
That's OK. Having a network share is not a requirement. 

You can export the server configuration to your local machine with "ExportSystemConfigurationLocalREDFISH" for example.

**Comment by MrAmbiG** [comment]
@tehbluemuppetz unfortunately that particular option is not documented anywhere as a parameter in any of the following i checked just now
Set-ExportImportServerConfigurationProfileREDFISH.psm1
Set-ExportImportServerConfigurationProfileREDFISH.psm1
Set-ExportImportServerConfigurationProfileREDFISH.psm1
Set-ExportImportServerConfigurationProfileREDFISH_iDRAC8_only.psm1
Get-ImportServerConfigurationProfilePreviewREDFISH.psm1

**Comment by MrAmbiG** [comment]
you may delete this comment once you read.
Please find me on internal "ambi, gajendra" if you can. we do atleast 50 iDracs per day and we are all doing them manually.

**Comment by tehbluemuppetz** [comment]
@MrAmbiG 
ExportSystemConfigurationLocalREDFISH is one of the Python scripts, not PowerShell. If you install Python for Windows (ActiveState for example) you should be able to run it.

**Comment by MrAmbiG** [comment]
@tehbluemuppetz Thank you but i got away with using racadm.
https://github.com/MrAmbiG/Dell/tree/master/idrac

**Comment by texroemer** [comment]
@MrAmbiG

Hi,

I know you got local SCP to work using RACADM but just wanted to let you know i have created cmdlets using Redfish for local export / import SCP support which have been uploaded to GitHub.

Thanks
