### ISSUE TITLE
Fetching PCI bus order number

### ISSUE THREAD

**Issue by kgrvamsi** [dell/iDRAC-Redfish-Scripting#103]
Is there a way to fetch the PCI slot Bus order number from Redfish API?

**Comment by texroemer** [comment]
Hi @kgrvamsi 

GET on URI "redfish/v1/Systems/System.Embedded.1", you will see "PCIeDevices" property which will list URIs for each PCI device. GET on any of these URIs, you will see "Id" property. The first digit is the Bus number. 

Example below is for H330 which id reports a value of "25-0". 25 is the Bus number, 0 is the Device number.

GET on URI "redfish/v1/Systems/System.Embedded.1/PCIeDevices/25-0":


  
@odata.context | "/redfish/v1/$metadata#PCIeDevice.PCIeDevice"
@odata.etag | "1585664701"
@odata.id | "/redfish/v1/Systems/System.Embedded.1/PCIeDevices/25-0"
@odata.type | "#PCIeDevice.v1_3_0.PCIeDevice"
Assembly |  
@odata.id | "/redfish/v1/Chassis/System.Embedded.1/Assembly"
AssetTag | null
Description | "PERC H330 Mini"
DeviceType | "SingleFunction"
FirmwareVersion | "25.5.6.0009"
**Id | "25-0"**
Links |  
Chassis |  
0 |  
@odata.id | "/redfish/v1/Chassis/Enclosure.Internal.0-1:RAID.Integrated.1-1"
Chassis@odata.count | 1
PCIeFunctions |  
0 |  
@odata.id | "/redfish/v1/Systems/System.Embedded.1/PCIeDevices/25-0/PCIeFunctions/25-0-0"
PCIeFunctions@odata.count | 1
Manufacturer | "Broadcom / LSI"
Model | null
Name | "PERC H330 Mini"
PartNumber | "0GDJ3J"
SKU | null
SerialNumber | "CN7792168906J6"
Status |  
Health | "OK"
HealthRollup | "OK"
State | "Enabled"

**Comment by kgrvamsi** [comment]
@texroemer Thanks for the info and is this api working on 3.21.22.21 and above versions or is this available in 4.00.00.00?

**Comment by texroemer** [comment]
Hi @kgrvamsi 

DMTF PCIeDevice URI support was added in 3.30.30.30 iDRAC. 

Thanks
