### ISSUE TITLE
Error code 5 ("not supported") when trying to use Set-ExportImportServerConfigurationProfileREDFISH

### ISSUE THREAD

**Issue by tluchowski** [dell/iDRAC-Redfish-Scripting#11]
Hello,

I've downloaded the most recent version of scripts, and I'm trying to access iDRAC from Powershell. I'm trying to use Set-ExportImportServerConfigurationProfileREDFISH, however I keep getting an error.

I've tried both the regular and iDRAC8 only module, with the same result.

Please help! :)

Set-ExportImportServerConfigurationProfileREDFISH -idrac_ip 10.77.250.8 -idrac_username root -idrac_password calvin -Method import -network_share_IPAddress 10.77.1.5 -ShareType CIFS -ShareName Redfish -cifs_Username user -cifs_Password pass  -Target RAID -FileName export_ps.xml

Output: 

- WARNING, Parameter details for import operation

Name                           Value
----                           -----
ShareParameters                {Password, ShareName, IPAddress, UserName...}

ShareParameters details:

Password                       pass
ShareName                      Redfish
IPAddress                      10.77.1.5
UserName                       user
FileName                       export_ps.xml
ShareType                      CIFS
Target                         RAID
Invoke-WebRequest : { "error": { "code": "5", "message": { "lang": "en-us", "value": "not supported: " } } }
At C:\apps\iDRAC-Redfish-Scripting-master\Redfish PowerShell\Set-ExportImportServerConfigurationProfileREDFISH_iDRAC8_o
nly\Set-ExportImportServerConfigurationProfileREDFISH_iDRAC8_only.psm1:175 char:12
+ $result1 = Invoke-WebRequest -Uri $u -Credential $credential -Method Post -Body  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
Exception calling "Match" with "2" argument(s): "Value cannot be null.
Parameter name: input"
At C:\apps\iDRAC-Redfish-Scripting-master\Redfish PowerShell\Set-ExportImportServerConfigurationProfileREDFISH_iDRAC8_o
nly\Set-ExportImportServerConfigurationProfileREDFISH_iDRAC8_only.psm1:177 char:1
+ $job_id_search=[regex]::Match($raw_content_output, "JID_.+?r").captures.groups[0 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentNullException

You cannot call a method on a null-valued expression.
At C:\apps\iDRAC-Redfish-Scripting-master\Redfish PowerShell\Set-ExportImportServerConfigurationProfileREDFISH_iDRAC8_o
nly\Set-ExportImportServerConfigurationProfileREDFISH_iDRAC8_only.psm1:178 char:1
+ $job_id=$job_id_search.Replace("\r","")
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Exception calling "Format" with "2" argument(s): "Value cannot be null.
Parameter name: args"
At C:\apps\iDRAC-Redfish-Scripting-master\Redfish PowerShell\Set-ExportImportServerConfigurationProfileREDFISH_iDRAC8_o
nly\Set-ExportImportServerConfigurationProfileREDFISH_iDRAC8_only.psm1:189 char:5
+     [String]::Format("- FAIL, statuscode {0} returned",$result1.StatusCode)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentNullException

**Comment by texroemer** [comment]
For method name, the value is case sensitive. Can you try passing in "Import" instead of "import", see if the command now works? I'll also update the cmdlet to handle this condition if user passes in invalid case.

**Comment by texroemer** [comment]
New cmdlet has been uploaded to ignore case for Method parameter value.
