### ISSUE TITLE
Connecting to ldap

### ISSUE THREAD

**Issue by beren41** [dell/iDRAC-Redfish-Scripting#110]
Hi
Thank you for your work. 
Is it possible to create a script for connecting to ldap ?
In https://topics-cdn.dell.com/pdf/idrac9-lifecycle-controller-v33-series_api-guide2_en-us.pdf no url for ldap.

**Comment by texroemer** [comment]
Hi @beren41 

To GET iDRAC LDAP attributes, GET on URI "redfish/v1/Managers/iDRAC.Embedded.1/Attributes" (you can use SetIdracLcSystemAttributesREDFISH.py script to get these attributes). This URI will get all iDRAC attributes but you will see these LDAP attributes stated:

LDAP.1.Port
LDAPRoleGroup.1.Privilege
LDAPRoleGroup.2.Privilege
LDAPRoleGroup.3.Privilege
LDAPRoleGroup.4.Privilege
LDAPRoleGroup.5.Privilege
LDAP.1.CertValidationEnable
LDAP.1.Enable
LDAP.1.GroupAttributeIsDN
LDAP.1.BaseDN
LDAP.1.BindDN
LDAP.1.GroupAttribute
LDAP.1.SearchFilter 
LDAP.1.Server
LDAP.1.UserAttribute
LDAPRoleGroup.1.DN
LDAPRoleGroup.2.DN 
LDAPRoleGroup.3.DN 
LDAPRoleGroup.4.DN 
LDAPRoleGroup.5.DN
LDAP.1.BindPassword

To set iDRAC LDAP attributes, execute PATCH on URI "redfish/v1/Managers/iDRAC.Embedded.1/Attributes".  Example below shows setting a few LDAP attributes for iDRAC.

C:\Python38-32>SetIdracLcSystemAttributesREDFISH.py -ip 192.168.0.120 -u root -p calvin -s idrac -an LDAP.1.Enable,LDAP.1.Server -av Enabled,"192.168.0.130"

- WARNING, changing "IDRAC" attributes -

 Attribute Name: LDAP.1.Enable, setting new value to: Enabled
 Attribute Name: LDAP.1.Server, setting new value to: 192.168.0.130

- PASS, Command passed to successfully set "IDRAC" attribute(s), status code 200 returned

- WARNING, getting new attribute values -

Attribute Name: LDAP.1.Enable, Attribute Value: Enabled
Attribute Name: LDAP.1.Server, Attribute Value: 192.168.0.130

**Comment by beren41** [comment]
Thanks. I'll try. If you have any questions, I will write here.
