### ISSUE TITLE
Insert VirtualMedia Payload issue

### ISSUE THREAD

**Issue by kgrvamsi** [dell/iDRAC-Redfish-Scripting#111]
Hi @texroemer 

When i try to insert a virtual media via postman i think the server is not accepting the boolean values as per the documentation

![image](https://user-images.githubusercontent.com/1199031/83542884-369b1d00-a4c1-11ea-8039-7d4c2ba49655.png)

REF url:
https://www.dell.com/support/manuals/id/en/idbiz1/idrac9-lifecycle-controller-v4.x-series/idrac9_4.00.00.00_redfishapiguide_pub/virtualmedia?guid=guid-44720af7-7951-49b2-89fc-01181a0edf92&lang=en-us

I tried the following

URL: https://{{DELL_SERVER}}/redfish/v1/Managers/iDRAC.Embedded.1/VirtualMedia/CD/Actions/VirtualMedia.InsertMedia

Method: POST

```
{
    "Image": "http://<webserver>/dell730raid.iso",
    "Inserted": 0,
    "WriteProtected": 0
}

{
    "Image": "http://<webserver>/dell730raid.iso",
    "Inserted": true,
    "WriteProtected": true
}

{
    "Image": "http://<webserver>/dell730raid.iso",
    "Inserted": "True",
    "WriteProtected": "True"
}
```

![image](https://user-images.githubusercontent.com/1199031/83543085-7c57e580-a4c1-11ea-9332-e06f0b7fb6ba.png)

**Comment by texroemer** [comment]
Hi @kgrvamsi 

I just tried using Postman with iDRAC 4.10, no issues.

![image](https://user-images.githubusercontent.com/30351677/83544493-9692c300-a4c3-11ea-851d-67ecc83ba4a5.png)

Did you also try python script or Powershell cmdlet, also fails?

Thanks

**Comment by kgrvamsi** [comment]
How about this version?

iDRAC Firmware Version | 4.00.00.00

**Comment by texroemer** [comment]
I rollback the iDRAC to 4.00, still works with no issues. The only way i repro the issue was passing in a boolean value of false which is not supported. 

Did you try removing WriteProtected from the JSON body, see if it passes?

**Comment by kgrvamsi** [comment]
@texroemer not sure on why my postman is not taking my request but i tried using the curl command

```
curl -v --location --request POST 'https://135.63.x.x/redfish/v1/Managers/iDRAC.Embedded.1/VirtualMedia/CD/Actions/VirtualMedia.InsertMedia' --header 'Authorization: Basic dtyUiopbDN5ZmM=' --header 'Content-Type: application/json' --data-raw '{
    "Image": "http://<web-Server>/dell730raid.iso",
    "Inserted": true,
    "WriteProtected": true
}' --insecure

Got this error which is more of networking issue from the idrac to web server

"error":{"@Message.ExtendedInfo":[{"Message":"The remote file location is not accessible or reachable.","MessageArgs":[],"MessageArgs@odata.count":0"
```

So i assume the above payload is working

**Comment by texroemer** [comment]
If works from curl but not Postman, seems to be issue specific to Postman now. I've been trying multiple scenarios to try and repro your issue with Postman but unable to.

For new issue now where it can't reach HTTP share, is your web server Apache or IIS?

**Comment by kgrvamsi** [comment]
we are using Nginx (Open Resty version) as the HTTP Server.

**Comment by texroemer** [comment]
Never used Nginx with OpenResty before for HTTP server. Did some research online and setup this HTTP server, works with no issues attaching ISO as vmedia.

Can you check directory permissions and firewall settings? I was able to repro your issue when i blocked the port but once i opened it, no issues with attach vmedia.
