### ISSUE TITLE
Redfish API for Remote File Share

### ISSUE THREAD

**Issue by kgrvamsi** [dell/iDRAC-Redfish-Scripting#112]
Hi @texroemer 

What is the redfish api that i can use to add remote file share with a iso hosted over http

![image](https://user-images.githubusercontent.com/1199031/83570820-5562d900-a4ec-11ea-82cf-2b6826af19ea.png)

**Comment by texroemer** [comment]
Hi @kgrvamsi 

There is no Redfish OEM support for iDRAC Remote File Share feature. You must use DMTF action VirtualMedia.InsertMedia to attach an ISO using HTTP share. 

iDRAC does support OEM action DellOSDeploymentService.ConnectNetworkISOImage but this action only supports NFS or CIFS network shares.

**Comment by kgrvamsi** [comment]
But Virtual Media Service will download the resource to IDRAC storage and then boot and Remote share is more of like booting the server over network right so for both scenarios we can use the VirtualMedia DMTF Action API?

**Comment by texroemer** [comment]
iDRAC Remote File Share (RFS) feature uses iDRAC virtual media implementation. Once attached, ISO is exposed to the server as virtual CD which you can then boot to. Same behavior for DMTF virtual media action where the ISO can be attached and boot to.
