### ISSUE TITLE
Set-IDRACUserPasswordREDFISH

### ISSUE THREAD

**Issue by jahedges-tp** [dell/iDRAC-Redfish-Scripting#114]
I am still working how to solve this but here is the issue - 

If the new_password contains a character like -  " '  -  then the convertto-json call on ln 149 will result in invalid json and script will throw error similar to this - 

Message                     : {"error":{"@Message.ExtendedInfo":[{"Message":"Unable to complete the operation because the JSON data format entered is invalid.","M
                              essageArgs":["{\"Password\":\"ommited\\\\\"ommited\"})"],"MessageArgs@odata.count":1,"MessageId":"IDRAC.2.1.SYS405","RelatedProperties"
                              :[],"RelatedProperties@odata.count":0,"Resolution":"Do the following and the retry the operation: 1) Enter the correct JSON data
                              format and retry the operation. 2) Make sure that no syntax error is present in JSON data format. 3) Make sure that a duplicate key
                              is not present in JSON data format.","Severity":"Critical"},{"Message":"The request body submitted was malformed JSON and could not
                              be parsed by the receiving service.","MessageArgs":["{\"Password\":\"ommited\\\\\"ommited\"})"],"MessageArgs@odata.count":1,"MessageId"
                              :"Base.1.5.MalformedJSON","RelatedProperties":[""],"RelatedProperties@odata.count":1,"Resolution":"Ensure that the request body is
                              valid JSON and resubmit the request.","Severity":"Critical"}],"code":"Base.1.5.GeneralError","message":"A general error has
                              occurred. See ExtendedInfo for more information"}}

**Comment by jahedges-tp** [comment]
Having looked more in-depth at this interaction between JSON and PowerShell, definitely recommend anyone to just avoid those quotation characters.  Still searching for an elegant solution though.

**Comment by texroemer** [comment]
Hi @jahedges-tp 

Thanks for still looking into this issue. I've also been trying to debug this issue for the past few days and still haven't been able to figure out how to get single or double quotes to work with JSON and Powershell. 

For single quote, it converts to unicode and then PATCH will pass but when you try the new password, it fails. You have to use the unicode conversion for the password to work which this behavior shouldn't happen. This behavior also only exists with Powershell, don't see this issue with Python.

Example after setting the password using Powershell with single quote:

PS C:\> racadm -r 192.168.0.120 -u tester -p "pass'word" --nocertwarn getversion
ERROR: Login failed - invalid username or password
PS C:\> racadm -r 192.168.0.120 -u tester -p "pass\u0027word" --nocertwarn getversion
Bios Version                     = 2.5.4

iDRAC Version                    = 4.10.10.10

Lifecycle Controller Version     = 4.10.10.10

IDSDM Version                    = NA

For double quote, both Powershell and Python fail for the same invalid JSON format error. Trying to escalate this issue to others on my team, see if they know how to get this to work.

**Comment by texroemer** [comment]
Hi @jahedges-tp 

I was able to get - and ' working for password, still trying to get " to work. New cmdlet has been updated to support - and '.

PS C:\> Set-IdracUserPasswordREDFISH -idrac_ip 192.168.0.120 -idrac_username tester -idrac_password "password" -idrac_user_id 3 -idrac_new_password 'pass-word'

- WARNING, executing PATCH command to change iDRAC user 'tester' password
- PASS, statuscode 200 returned successfully for PATCH command to change iDRAC user password
- WARNING, executing GET command with new user password to validate password was changed
- PASS, statuscode 200 returned successfully for GET command, iDRAC user password changed

PS C:\> Set-IdracUserPasswordREDFISH -idrac_ip 192.168.0.120 -idrac_username tester - idrac_password "pass-word" -idrac_user_id 3 -idrac_new_password "pass'word"


- WARNING, executing PATCH command to change iDRAC user 'tester' password
- PASS, statuscode 200 returned successfully for PATCH command to change iDRAC user password
- WARNING, executing GET command with new user password to validate password was changed
- PASS, statuscode 200 returned successfully for GET command, iDRAC user password changed

PS C:\> Set-IdracUserPasswordREDFISH -idrac_ip 192.168.0.120 -idrac_username tester -idrac_password "pass'word" -idrac_user_id 3 -idrac_new_password "password"


- WARNING, executing PATCH command to change iDRAC user 'tester' password
- PASS, statuscode 200 returned successfully for PATCH command to change iDRAC user password
- WARNING, executing GET command with new user password to validate password was changed
- PASS, statuscode 200 returned successfully for GET command, iDRAC user password changed
