### ISSUE TITLE
Is it possible to fetch all events without looping?

### ISSUE THREAD

**Issue by seitzbg** [dell/iDRAC-Redfish-Scripting#12]
I see if you fetch: /redfish/v1/Managers/iDRAC.Embedded.1/Logs/Lclog, it will only return a subset of the results with:

@odata.nextLink": "/redfish/v1/Managers/iDRAC.Embedded.1/Logs/Lclog?$skip=50

Is it possible to have it return all of the results in one go or do I have to keep making multiple requests ?

**Comment by texroemer** [comment]
iDRAC with Redfish can only return 50 entries at a time. You will need to run a GET on nextLink URI returned to see the next 50 entries and continue this process until GET command returns no data. 

I updated Python script "GetIdracLcLogsREDFISH.py" which will now handle getting the complete LC logs or the latest last 50 entries. 

Example of getting complete logs: GetIdracLcLogsREDFISH.py -ip 192.168.0.120 -u root -p calvin -c y

If you don't pass in -c argument, script will just get the latest last 50 entries. 

For future iDRAC releases, we are planning to add support to export the complete LC logs either locally or network share, similar to "racadm lclog export" behavior.

**Comment by seitzbg** [comment]
Yeah I did the same using the Redfish library here:

https://github.com/DMTF/python-redfish-library

Would be nice to as you said to be able to fetch the whole log at once.

Thanks!
