### ISSUE TITLE
Nit: Git clone issue on macOS Catalina - path collisions...

### ISSUE THREAD

**Issue by RevisionX** [dell/iDRAC-Redfish-Scripting#121]
Cloned repo, received the following error:

warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'Redfish Python/GetDHSDisksREDFISH.py'
  'Redfish Python/getDHSDisksREDFISH.py'

If files are identical, removing one (git rm GetDHSDisksREDFISH.py) will fix this.

**Comment by texroemer** [comment]
Hi @RevisionX 

Thanks for pointing this out. I made changes to the script name few days ago to be consistent with the other scripts, forgot to remove one of them. Script getDHSDisksREDFISH has been removed.

Thanks
