### ISSUE TITLE
Query Parameters

### ISSUE THREAD

**Issue by geoffguynn** [dell/iDRAC-Redfish-Scripting#123]
Will these scripts use the Query parameters at some point? I tried a rest call against the API like the DMTF  and DRAC documentation(s) state, but to no avail.

    New-DRACRestCall `
        -Method 'GET' `
        -EndPoint '/redfish/v1/Managers/iDRAC.Embedded.1/Jobs' `
        -Filter ('?$filter=JobState ne {0}' -f '"Completed"')
    ) | 
    Select -ExpandProperty content | ConvertFrom-Json

Most of the Redfish documentation lists them and examples of them as supported, but through testing I have not seen them return correct results.

Section: 6.4.2.4.1. Query parameters
https://redfish.dmtf.org/schemas/DSP0266_1.4.0.html

https://www.dell.com/support/manuals/us/en/19/poweredge-fc830/idrac8_redfishapiguide_2.70.70.70/query-parameters?guid=guid-37f5e656-acac-4999-a096-da7638838742&lang=en-us

I realize this may not be a direct issue with these scripts if the problem lies in the underlying Redfish implementation on the DRAC itself. However, I thought whomever is developing these scripts might have some insight from the developers on this issue? 

Thanks so much!

**Comment by texroemer** [comment]
Hi @geoffguynn 

For the URI you are using, you first need to expand the data using expand query parameter, then filter query parameter will work but currently iDRAC doesn't support passing in multiple query parameters for one URI. iDRAC will be adding support for using multiple query parameters in a future release.

Thanks

**Comment by geoffguynn** [comment]
Ah ok, I'm a bit overeager it seems. ;)
