### ISSUE TITLE
Certain argument names considered harmful

### ISSUE THREAD

**Issue by KeithBierman** [dell/iDRAC-Redfish-Scripting#125]
-ip  ... elided ... --ipaddress (for network shares). For clarity, I suggest these be changed to

-idracip .... --shareip

Or similarly distinct names indicating the IP address usage. Admittedly this is really only helpful to someone coming at the scripts cold, but since the entire point of the scripts is educational .... the value is nontrivial ;>

**Comment by texroemer** [comment]
@KeithBierman 

Thanks for the feedback, will look into improving argument names for the scripts. With any script, you can always execute with -h argument to return help text, gives a description of what each argument means.

**Comment by KeithBierman** [comment]
Thank you. Of course the help didn't really make it any clearer ...
admittedly once one gets it it's trivial. But as I was writing up usage
notes for within our company, I found it clearer to give them both
descriptive names (in our case, IDRACIP and RACKIP (Canonical MAAS, rack
controller, for whatever its worth).
Keith Bierman
khbkhb@gmail.com
303 997 2749
