### ISSUE TITLE
RFE/for discussion  notation changes

### ISSUE THREAD

**Issue by KeithBierman** [dell/iDRAC-Redfish-Scripting#127]
Consider messages like:
**- WARNING, JobStatus not completed, current status**:  
@odata.type: #DellManager.v1_0_0.ServerConfigurationProfileResults
DisplayValue: VD_R1_0
Name: VD_R1_0
NewValue: RAID 1,SSD 0,SSD 1,Virtual Disk Size in Bytes : 239990276096,Virtual Disk Stripe Size : 64 Kb,Physical Disks per Span : 2
**Severity: OK**

The "warnings" are (mostly) informative, job status shouldn't be "warning" when it's just a normal progress indicator. I appreciate the scripts are educational and not "production" but making a clear distinction between expected and unexpected is educational ;>

Severity OK is similarly unfortunate. Perhaps "Status" or "Result" with OK being obvious. Status: Critical Failure (rather than just Critical) would also be modestly clearer (less so, Critical outside of the context of a review (movie, play, book) is clearly a BadThing(tm) ;>

**Comment by texroemer** [comment]
SCP import python scripts have been updated based off your suggestions. 

Example below of running updated script (changes in bold)

C:\Python38-32>ImportSystemConfigurationLocalFilenameREDFISH.py -ip 192.168.0.120 -u root -p calvin -t IDRAC -f 2020-8-6_135718_export.xml

- JID_967658708518 successfully created for ImportSystemConfiguration method

**- INFO, JobStatus not completed, current status: "Importing Server Configuration Profile.", percent complete: "20"**
- FAIL, Job ID JID_967658708518 marked as Completed but detected issue(s). See detailed job results below for more information on failure

- Detailed configuration changes and job results for "JID_967658708518"

@odata.type: #DellManager.v1_0_0.ServerConfigurationProfileResults
DisplayValue: Enable or Disable IPMI over LAN
ErrCode: 0
Name: IPMILan.1#Enable
NewValue: Disabled
OldValue: Enabled
Severity: OK
**Status: Success**


@odata.type: #DellManager.v1_0_0.ServerConfigurationProfileResults
DisplayValue: Alert Enable
ErrCode: 0
Name: IPMILan.1#AlertEnable
NewValue: Disabled
OldValue: Enabled
Severity: OK
**Status: Success**


Message: Not one of the Possible Values for Attribute
MessageID: RAC015
@odata.type: #DellManager.v1_0_0.ServerConfigurationProfileResults
DisplayValue: Privilege Limit
ErrCode: 9240
Name: IPMILan.1#PrivLimit
NewValue: dministrator
OldValue: Administrator
Severity: Critical
**Status: Failure**


Message: Import of Server Configuration Profile operation completed with errors.
MessageArgs: []
MessageArgs@odata.count: 0
MessageId: SYS055

**Comment by KeithBierman** [comment]
Thank you!
