### ISSUE TITLE
Much less than 10hrs counts as past 10 hrs...

### ISSUE THREAD

**Issue by KeithBierman** [dell/iDRAC-Redfish-Scripting#128]
Ran again, with time 
- WARNING, job not marked completed, current job status is running, current job execution time: 0:59:47
- WARNING, job not marked completed, current job status is running, current job execution time: 0:59:57

- FAIL: Timeout of 10 hours has been hit, script stopped. Check iDRAC LC logs or Job Queue to debug.

real	60m10.480s
user	0m2.002s
sys	0m0.257s
khb@LB1EDGRACKCON01:~/iDrac_python/python$
....

Real time is sixty minutes, timeout says 10 hours. Since the estimated runtime for the extended test is relatively long, should we even have a 10 hour timeout? But if we do, shouldn't it actually measure 10 hours not 10x real time?

Original khb@LB1EDGRACKCON01:~/iDrac_python/python$ python3 ./RunDiagnosticsREDFISH.py  -uroot -p calvin -ip 10.192.3.36 -m 1 -r2

- WARNING, arguments and values for RunePSADiagnostics method

RebootJobType: PowerCycle
RunMode: ExpressAndExtended

- PASS: POST command passed for RunePSADiagnostics method, status code 202 returned
- PASS, job ID JID_973026374311 successfuly created for RunePSADiagnostics method

- WARNING, server will now automatically reboot and run remote diagnostics once POST completes. Script will check job status every 1 minute until marked completed

- WARNING, job not marked completed, current job status is running, current job execution time: 0:00:10
- WARNING, job not marked completed, current job status is running, current job execution time: 0:00:20
- WARNING, job not marked completed, current job status is running, current job execution time: 0:00:31
- WARNING, job not marked completed, current job status is running, current job execution time: 0:00:41
- WARNING, job not marked completed, current job status is running, current job execution time: 0:00:51
- WARNING, job not marked completed, current job status is running, current job execution time: 0:01:01
- WARNING, job not marked completed, current job status is running, current job execution time: 0:01:12
- WARNING, job not marked completed, current job status is running, current job execution time: 0:01:22
- WARNING, job not marked completed, current job status is running, current job execution time: 0:01:32
- WARNING, job not marked completed, current job status is running, current job execution time: 0:01:43
- WARNING, job not marked completed, current job status is running, current job execution time: 0:01:53
- WARNING, job not marked completed, current job status is running, current job execution time: 0:02:03
- WARNING, job not marked completed, current job status is running, current job execution time: 0:02:13
- WARNING, job not marked completed, current job status is running, current job execution time: 0:02:24
- WARNING, job not marked completed, current job status is running, current job execution time: 0:02:34
- WARNING, job not marked completed, current job status is running, current job execution time: 0:02:45
- WARNING, job not marked completed, current job status is running, current job execution time: 0:02:55
- WARNING, job not marked completed, current job status is running, current job execution time: 0:03:05
- WARNING, job not marked completed, current job status is running, current job execution time: 0:03:15
- WARNING, job not marked completed, current job status is running, current job execution time: 0:03:26
- WARNING, job not marked completed, current job status is running, current job execution time: 0:03:36
- WARNING, job not marked completed, current job status is running, current job execution time: 0:03:46
- WARNING, job not marked completed, current job status is running, current job execution time: 0:03:57
- WARNING, job not marked completed, current job status is running, current job execution time: 0:04:07
- WARNING, job not marked completed, current job status is running, current job execution time: 0:04:17
- WARNING, job not marked completed, current job status is running, current job execution time: 0:04:28
- WARNING, job not marked completed, current job status is running, current job execution time: 0:04:38
- WARNING, job not marked completed, current job status is running, current job execution time: 0:04:48
- WARNING, job not marked completed, current job status is running, current job execution time: 0:04:59
- WARNING, job not marked completed, current job status is running, current job execution time: 0:05:09
- WARNING, job not marked completed, current job status is running, current job execution time: 0:05:19
- WARNING, job not marked completed, current job status is running, current job execution time: 0:05:30
- WARNING, job not marked completed, current job status is running, current job execution time: 0:05:40
- WARNING, job not marked completed, current job status is running, current job execution time: 0:05:50
- WARNING, job not marked completed, current job status is running, current job execution time: 0:06:00
- WARNING, job not marked completed, current job status is running, current job execution time: 0:06:11
- WARNING, job not marked completed, current job status is running, current job execution time: 0:06:21
- WARNING, job not marked completed, current job status is running, current job execution time: 0:06:31
- WARNING, job not marked completed, current job status is running, current job execution time: 0:06:42
- WARNING, job not marked completed, current job status is running, current job execution time: 0:06:52
- WARNING, job not marked completed, current job status is running, current job execution time: 0:07:02
- WARNING, job not marked completed, current job status is running, current job execution time: 0:07:13
- WARNING, job not marked completed, current job status is running, current job execution time: 0:07:23
- WARNING, job not marked completed, current job status is running, current job execution time: 0:07:33
- WARNING, job not marked completed, current job status is running, current job execution time: 0:07:43
- WARNING, job not marked completed, current job status is running, current job execution time: 0:07:54
- WARNING, job not marked completed, current job status is running, current job execution time: 0:08:04
- WARNING, job not marked completed, current job status is running, current job execution time: 0:08:15
- WARNING, job not marked completed, current job status is running, current job execution time: 0:08:25
- WARNING, job not marked completed, current job status is running, current job execution time: 0:08:35
- WARNING, job not marked completed, current job status is running, current job execution time: 0:08:46
- WARNING, job not marked completed, current job status is running, current job execution time: 0:08:56
- WARNING, job not marked completed, current job status is running, current job execution time: 0:09:06
- WARNING, job not marked completed, current job status is running, current job execution time: 0:09:17
- WARNING, job not marked completed, current job status is running, current job execution time: 0:09:27
- WARNING, job not marked completed, current job status is running, current job execution time: 0:09:37
- WARNING, job not marked completed, current job status is running, current job execution time: 0:09:48
- WARNING, job not marked completed, current job status is running, current job execution time: 0:09:58
- WARNING, job not marked completed, current job status is running, current job execution time: 0:10:08
- WARNING, job not marked completed, current job status is running, current job execution time: 0:10:19
- WARNING, job not marked completed, current job status is running, current job execution time: 0:10:29
- WARNING, job not marked completed, current job status is running, current job execution time: 0:10:39
- WARNING, job not marked completed, current job status is running, current job execution time: 0:10:50
- WARNING, job not marked completed, current job status is running, current job execution time: 0:11:00
- WARNING, job not marked completed, current job status is running, current job execution time: 0:11:10
- WARNING, job not marked completed, current job status is running, current job execution time: 0:11:21
- WARNING, job not marked completed, current job status is running, current job execution time: 0:11:31
- WARNING, job not marked completed, current job status is running, current job execution time: 0:11:41
- WARNING, job not marked completed, current job status is running, current job execution time: 0:11:52
- WARNING, job not marked completed, current job status is running, current job execution time: 0:12:02
- WARNING, job not marked completed, current job status is running, current job execution time: 0:12:12
- WARNING, job not marked completed, current job status is running, current job execution time: 0:12:22
- WARNING, job not marked completed, current job status is running, current job execution time: 0:12:33
- WARNING, job not marked completed, current job status is running, current job execution time: 0:12:43
- WARNING, job not marked completed, current job status is running, current job execution time: 0:12:53
- WARNING, job not marked completed, current job status is running, current job execution time: 0:13:04
- WARNING, job not marked completed, current job status is running, current job execution time: 0:13:14
- WARNING, job not marked completed, current job status is running, current job execution time: 0:13:24
- WARNING, job not marked completed, current job status is running, current job execution time: 0:13:35
- WARNING, job not marked completed, current job status is running, current job execution time: 0:13:45
- WARNING, job not marked completed, current job status is running, current job execution time: 0:13:55
- WARNING, job not marked completed, current job status is running, current job execution time: 0:14:06
- WARNING, job not marked completed, current job status is running, current job execution time: 0:14:16
- WARNING, job not marked completed, current job status is running, current job execution time: 0:14:26
- WARNING, job not marked completed, current job status is running, current job execution time: 0:14:36
- WARNING, job not marked completed, current job status is running, current job execution time: 0:14:47
- WARNING, job not marked completed, current job status is running, current job execution time: 0:14:57
- WARNING, job not marked completed, current job status is running, current job execution time: 0:15:07
- WARNING, job not marked completed, current job status is running, current job execution time: 0:15:18
- WARNING, job not marked completed, current job status is running, current job execution time: 0:15:28
- WARNING, job not marked completed, current job status is running, current job execution time: 0:15:38
- WARNING, job not marked completed, current job status is running, current job execution time: 0:15:49
- WARNING, job not marked completed, current job status is running, current job execution time: 0:15:59
- WARNING, job not marked completed, current job status is running, current job execution time: 0:16:09
- WARNING, job not marked completed, current job status is running, current job execution time: 0:16:20
- WARNING, job not marked completed, current job status is running, current job execution time: 0:16:30
- WARNING, job not marked completed, current job status is running, current job execution time: 0:16:40
- WARNING, job not marked completed, current job status is running, current job execution time: 0:16:51
- WARNING, job not marked completed, current job status is running, current job execution time: 0:17:01
- WARNING, job not marked completed, current job status is running, current job execution time: 0:17:11
- WARNING, job not marked completed, current job status is running, current job execution time: 0:17:21
- WARNING, job not marked completed, current job status is running, current job execution time: 0:17:32
- WARNING, job not marked completed, current job status is running, current job execution time: 0:17:42
- WARNING, job not marked completed, current job status is running, current job execution time: 0:17:52
- WARNING, job not marked completed, current job status is running, current job execution time: 0:18:03
- WARNING, job not marked completed, current job status is running, current job execution time: 0:18:13
- WARNING, job not marked completed, current job status is running, current job execution time: 0:18:23
- WARNING, job not marked completed, current job status is running, current job execution time: 0:18:34
- WARNING, job not marked completed, current job status is running, current job execution time: 0:18:44
- WARNING, job not marked completed, current job status is running, current job execution time: 0:18:54
- WARNING, job not marked completed, current job status is running, current job execution time: 0:19:04
- WARNING, job not marked completed, current job status is running, current job execution time: 0:19:15
- WARNING, job not marked completed, current job status is running, current job execution time: 0:19:25
- WARNING, job not marked completed, current job status is running, current job execution time: 0:19:35
- WARNING, job not marked completed, current job status is running, current job execution time: 0:19:46
- WARNING, job not marked completed, current job status is running, current job execution time: 0:19:56
- WARNING, job not marked completed, current job status is running, current job execution time: 0:20:06
- WARNING, job not marked completed, current job status is running, current job execution time: 0:20:17
- WARNING, job not marked completed, current job status is running, current job execution time: 0:20:27
- WARNING, job not marked completed, current job status is running, current job execution time: 0:20:38
- WARNING, job not marked completed, current job status is running, current job execution time: 0:20:48
- WARNING, job not marked completed, current job status is running, current job execution time: 0:20:58
- WARNING, job not marked completed, current job status is running, current job execution time: 0:21:09
- WARNING, job not marked completed, current job status is running, current job execution time: 0:21:19
- WARNING, job not marked completed, current job status is running, current job execution time: 0:21:29
- WARNING, job not marked completed, current job status is running, current job execution time: 0:21:40
- WARNING, job not marked completed, current job status is running, current job execution time: 0:21:50
- WARNING, job not marked completed, current job status is running, current job execution time: 0:22:00
- WARNING, job not marked completed, current job status is running, current job execution time: 0:22:10
- WARNING, job not marked completed, current job status is running, current job execution time: 0:22:21
- WARNING, job not marked completed, current job status is running, current job execution time: 0:22:31
- WARNING, job not marked completed, current job status is running, current job execution time: 0:22:41
- WARNING, job not marked completed, current job status is running, current job execution time: 0:22:52
- WARNING, job not marked completed, current job status is running, current job execution time: 0:23:02
- WARNING, job not marked completed, current job status is running, current job execution time: 0:23:12
- WARNING, job not marked completed, current job status is running, current job execution time: 0:23:23
- WARNING, job not marked completed, current job status is running, current job execution time: 0:23:33
- WARNING, job not marked completed, current job status is running, current job execution time: 0:23:43
- WARNING, job not marked completed, current job status is running, current job execution time: 0:23:54
- WARNING, job not marked completed, current job status is running, current job execution time: 0:24:04
- WARNING, job not marked completed, current job status is running, current job execution time: 0:24:14
- WARNING, job not marked completed, current job status is running, current job execution time: 0:24:25
- WARNING, job not marked completed, current job status is running, current job execution time: 0:24:35
- WARNING, job not marked completed, current job status is running, current job execution time: 0:24:45
- WARNING, job not marked completed, current job status is running, current job execution time: 0:24:55
- WARNING, job not marked completed, current job status is running, current job execution time: 0:25:06
- WARNING, job not marked completed, current job status is running, current job execution time: 0:25:16
- WARNING, job not marked completed, current job status is running, current job execution time: 0:25:26
- WARNING, job not marked completed, current job status is running, current job execution time: 0:25:37
- WARNING, job not marked completed, current job status is running, current job execution time: 0:25:47
- WARNING, job not marked completed, current job status is running, current job execution time: 0:25:58
- WARNING, job not marked completed, current job status is running, current job execution time: 0:26:08
- WARNING, job not marked completed, current job status is running, current job execution time: 0:26:18
- WARNING, job not marked completed, current job status is running, current job execution time: 0:26:28
- WARNING, job not marked completed, current job status is running, current job execution time: 0:26:39
- WARNING, job not marked completed, current job status is running, current job execution time: 0:26:49
- WARNING, job not marked completed, current job status is running, current job execution time: 0:26:59
- WARNING, job not marked completed, current job status is running, current job execution time: 0:27:10
- WARNING, job not marked completed, current job status is running, current job execution time: 0:27:20
- WARNING, job not marked completed, current job status is running, current job execution time: 0:27:30
- WARNING, job not marked completed, current job status is running, current job execution time: 0:27:41
- WARNING, job not marked completed, current job status is running, current job execution time: 0:27:51
- WARNING, job not marked completed, current job status is running, current job execution time: 0:28:01
- WARNING, job not marked completed, current job status is running, current job execution time: 0:28:12
- WARNING, job not marked completed, current job status is running, current job execution time: 0:28:22
- WARNING, job not marked completed, current job status is running, current job execution time: 0:28:32
- WARNING, job not marked completed, current job status is running, current job execution time: 0:28:43
- WARNING, job not marked completed, current job status is running, current job execution time: 0:28:53
- WARNING, job not marked completed, current job status is running, current job execution time: 0:29:03
- WARNING, job not marked completed, current job status is running, current job execution time: 0:29:14
- WARNING, job not marked completed, current job status is running, current job execution time: 0:29:24
- WARNING, job not marked completed, current job status is running, current job execution time: 0:29:34
- WARNING, job not marked completed, current job status is running, current job execution time: 0:29:44
- WARNING, job not marked completed, current job status is running, current job execution time: 0:29:55
- WARNING, job not marked completed, current job status is running, current job execution time: 0:30:05
- WARNING, job not marked completed, current job status is running, current job execution time: 0:30:15
- WARNING, job not marked completed, current job status is running, current job execution time: 0:30:25
- WARNING, job not marked completed, current job status is running, current job execution time: 0:30:36
- WARNING, job not marked completed, current job status is running, current job execution time: 0:30:46
- WARNING, job not marked completed, current job status is running, current job execution time: 0:30:57
- WARNING, job not marked completed, current job status is running, current job execution time: 0:31:07
- WARNING, job not marked completed, current job status is running, current job execution time: 0:31:17
- WARNING, job not marked completed, current job status is running, current job execution time: 0:31:27
- WARNING, job not marked completed, current job status is running, current job execution time: 0:31:38
- WARNING, job not marked completed, current job status is running, current job execution time: 0:31:48
- WARNING, job not marked completed, current job status is running, current job execution time: 0:31:58
- WARNING, job not marked completed, current job status is running, current job execution time: 0:32:09
- WARNING, job not marked completed, current job status is running, current job execution time: 0:32:19
- WARNING, job not marked completed, current job status is running, current job execution time: 0:32:29
- WARNING, job not marked completed, current job status is running, current job execution time: 0:32:40
- WARNING, job not marked completed, current job status is running, current job execution time: 0:32:50
- WARNING, job not marked completed, current job status is running, current job execution time: 0:33:00
- WARNING, job not marked completed, current job status is running, current job execution time: 0:33:11
- WARNING, job not marked completed, current job status is running, current job execution time: 0:33:21
- WARNING, job not marked completed, current job status is running, current job execution time: 0:33:31
- WARNING, job not marked completed, current job status is running, current job execution time: 0:33:42
- WARNING, job not marked completed, current job status is running, current job execution time: 0:33:52
- WARNING, job not marked completed, current job status is running, current job execution time: 0:34:02
- WARNING, job not marked completed, current job status is running, current job execution time: 0:34:12
- WARNING, job not marked completed, current job status is running, current job execution time: 0:34:23
- WARNING, job not marked completed, current job status is running, current job execution time: 0:34:33
- WARNING, job not marked completed, current job status is running, current job execution time: 0:34:43
- WARNING, job not marked completed, current job status is running, current job execution time: 0:34:54
- WARNING, job not marked completed, current job status is running, current job execution time: 0:35:04
- WARNING, job not marked completed, current job status is running, current job execution time: 0:35:14
- WARNING, job not marked completed, current job status is running, current job execution time: 0:35:25
- WARNING, job not marked completed, current job status is running, current job execution time: 0:35:35
- WARNING, job not marked completed, current job status is running, current job execution time: 0:35:45
- WARNING, job not marked completed, current job status is running, current job execution time: 0:35:55
- WARNING, job not marked completed, current job status is running, current job execution time: 0:36:06
- WARNING, job not marked completed, current job status is running, current job execution time: 0:36:16
- WARNING, job not marked completed, current job status is running, current job execution time: 0:36:26
- WARNING, job not marked completed, current job status is running, current job execution time: 0:36:37
- WARNING, job not marked completed, current job status is running, current job execution time: 0:36:47
- WARNING, job not marked completed, current job status is running, current job execution time: 0:36:57
- WARNING, job not marked completed, current job status is running, current job execution time: 0:37:08
- WARNING, job not marked completed, current job status is running, current job execution time: 0:37:18
- WARNING, job not marked completed, current job status is running, current job execution time: 0:37:28
- WARNING, job not marked completed, current job status is running, current job execution time: 0:37:38
- WARNING, job not marked completed, current job status is running, current job execution time: 0:37:49
- WARNING, job not marked completed, current job status is running, current job execution time: 0:37:59
- WARNING, job not marked completed, current job status is running, current job execution time: 0:38:10
- WARNING, job not marked completed, current job status is running, current job execution time: 0:38:20
- WARNING, job not marked completed, current job status is running, current job execution time: 0:38:30
- WARNING, job not marked completed, current job status is running, current job execution time: 0:38:40
- WARNING, job not marked completed, current job status is running, current job execution time: 0:38:51
- WARNING, job not marked completed, current job status is running, current job execution time: 0:39:01
- WARNING, job not marked completed, current job status is running, current job execution time: 0:39:11
- WARNING, job not marked completed, current job status is running, current job execution time: 0:39:22
- WARNING, job not marked completed, current job status is running, current job execution time: 0:39:32
- WARNING, job not marked completed, current job status is running, current job execution time: 0:39:42
- WARNING, job not marked completed, current job status is running, current job execution time: 0:39:53
- WARNING, job not marked completed, current job status is running, current job execution time: 0:40:03
- WARNING, job not marked completed, current job status is running, current job execution time: 0:40:13
- WARNING, job not marked completed, current job status is running, current job execution time: 0:40:24
- WARNING, job not marked completed, current job status is running, current job execution time: 0:40:34
- WARNING, job not marked completed, current job status is running, current job execution time: 0:40:44
- WARNING, job not marked completed, current job status is running, current job execution time: 0:40:55
- WARNING, job not marked completed, current job status is running, current job execution time: 0:41:05
- WARNING, job not marked completed, current job status is running, current job execution time: 0:41:15
- WARNING, job not marked completed, current job status is running, current job execution time: 0:41:26
- WARNING, job not marked completed, current job status is running, current job execution time: 0:41:36
- WARNING, job not marked completed, current job status is running, current job execution time: 0:41:46
- WARNING, job not marked completed, current job status is running, current job execution time: 0:41:56
- WARNING, job not marked completed, current job status is running, current job execution time: 0:42:07
- WARNING, job not marked completed, current job status is running, current job execution time: 0:42:17
- WARNING, job not marked completed, current job status is running, current job execution time: 0:42:27
- WARNING, job not marked completed, current job status is running, current job execution time: 0:42:38
- WARNING, job not marked completed, current job status is running, current job execution time: 0:42:48
- WARNING, job not marked completed, current job status is running, current job execution time: 0:42:58
- WARNING, job not marked completed, current job status is running, current job execution time: 0:43:09
- WARNING, job not marked completed, current job status is running, current job execution time: 0:43:19
- WARNING, job not marked completed, current job status is running, current job execution time: 0:43:29
- WARNING, job not marked completed, current job status is running, current job execution time: 0:43:40
- WARNING, job not marked completed, current job status is running, current job execution time: 0:43:50
- WARNING, job not marked completed, current job status is running, current job execution time: 0:44:00
- WARNING, job not marked completed, current job status is running, current job execution time: 0:44:11
- WARNING, job not marked completed, current job status is running, current job execution time: 0:44:21
- WARNING, job not marked completed, current job status is running, current job execution time: 0:44:31
- WARNING, job not marked completed, current job status is running, current job execution time: 0:44:41
- WARNING, job not marked completed, current job status is running, current job execution time: 0:44:52
- WARNING, job not marked completed, current job status is running, current job execution time: 0:45:02
- WARNING, job not marked completed, current job status is running, current job execution time: 0:45:13
- WARNING, job not marked completed, current job status is running, current job execution time: 0:45:23
- WARNING, job not marked completed, current job status is running, current job execution time: 0:45:33
- WARNING, job not marked completed, current job status is running, current job execution time: 0:45:44
- WARNING, job not marked completed, current job status is running, current job execution time: 0:45:54
- WARNING, job not marked completed, current job status is running, current job execution time: 0:46:05
- WARNING, job not marked completed, current job status is running, current job execution time: 0:46:15
- WARNING, job not marked completed, current job status is running, current job execution time: 0:46:25
- WARNING, job not marked completed, current job status is running, current job execution time: 0:46:36
- WARNING, job not marked completed, current job status is running, current job execution time: 0:46:46
- WARNING, job not marked completed, current job status is running, current job execution time: 0:46:56
- WARNING, job not marked completed, current job status is running, current job execution time: 0:47:07
- WARNING, job not marked completed, current job status is running, current job execution time: 0:47:17
- WARNING, job not marked completed, current job status is running, current job execution time: 0:47:27
- WARNING, job not marked completed, current job status is running, current job execution time: 0:47:37
- WARNING, job not marked completed, current job status is running, current job execution time: 0:47:48
- WARNING, job not marked completed, current job status is running, current job execution time: 0:47:58
- WARNING, job not marked completed, current job status is running, current job execution time: 0:48:08
- WARNING, job not marked completed, current job status is running, current job execution time: 0:48:19
- WARNING, job not marked completed, current job status is running, current job execution time: 0:48:29
- WARNING, job not marked completed, current job status is running, current job execution time: 0:48:39
- WARNING, job not marked completed, current job status is running, current job execution time: 0:48:50
- WARNING, job not marked completed, current job status is running, current job execution time: 0:49:00
- WARNING, job not marked completed, current job status is running, current job execution time: 0:49:10
- WARNING, job not marked completed, current job status is running, current job execution time: 0:49:20
- WARNING, job not marked completed, current job status is running, current job execution time: 0:49:31
- WARNING, job not marked completed, current job status is running, current job execution time: 0:49:41
- WARNING, job not marked completed, current job status is running, current job execution time: 0:49:51
- WARNING, job not marked completed, current job status is running, current job execution time: 0:50:02
- WARNING, job not marked completed, current job status is running, current job execution time: 0:50:12
- WARNING, job not marked completed, current job status is running, current job execution time: 0:50:22
- WARNING, job not marked completed, current job status is running, current job execution time: 0:50:33
- WARNING, job not marked completed, current job status is running, current job execution time: 0:50:43
- WARNING, job not marked completed, current job status is running, current job execution time: 0:50:53
- WARNING, job not marked completed, current job status is running, current job execution time: 0:51:04
- WARNING, job not marked completed, current job status is running, current job execution time: 0:51:14
- WARNING, job not marked completed, current job status is running, current job execution time: 0:51:24
- WARNING, job not marked completed, current job status is running, current job execution time: 0:51:35
- WARNING, job not marked completed, current job status is running, current job execution time: 0:51:45
- WARNING, job not marked completed, current job status is running, current job execution time: 0:51:55
- WARNING, job not marked completed, current job status is running, current job execution time: 0:52:06
- WARNING, job not marked completed, current job status is running, current job execution time: 0:52:16
- WARNING, job not marked completed, current job status is running, current job execution time: 0:52:26
- WARNING, job not marked completed, current job status is running, current job execution time: 0:52:37
- WARNING, job not marked completed, current job status is running, current job execution time: 0:52:47
- WARNING, job not marked completed, current job status is running, current job execution time: 0:52:57
- WARNING, job not marked completed, current job status is running, current job execution time: 0:53:08
- WARNING, job not marked completed, current job status is running, current job execution time: 0:53:18
- WARNING, job not marked completed, current job status is running, current job execution time: 0:53:28
- WARNING, job not marked completed, current job status is running, current job execution time: 0:53:38
- WARNING, job not marked completed, current job status is running, current job execution time: 0:53:49
- WARNING, job not marked completed, current job status is running, current job execution time: 0:53:59
- WARNING, job not marked completed, current job status is running, current job execution time: 0:54:09
- WARNING, job not marked completed, current job status is running, current job execution time: 0:54:20
- WARNING, job not marked completed, current job status is running, current job execution time: 0:54:30
- WARNING, job not marked completed, current job status is running, current job execution time: 0:54:40
- WARNING, job not marked completed, current job status is running, current job execution time: 0:54:50
- WARNING, job not marked completed, current job status is running, current job execution time: 0:55:01
- WARNING, job not marked completed, current job status is running, current job execution time: 0:55:11
- WARNING, job not marked completed, current job status is running, current job execution time: 0:55:21
- WARNING, job not marked completed, current job status is running, current job execution time: 0:55:32
- WARNING, job not marked completed, current job status is running, current job execution time: 0:55:42
- WARNING, job not marked completed, current job status is running, current job execution time: 0:55:52
- WARNING, job not marked completed, current job status is running, current job execution time: 0:56:03
- WARNING, job not marked completed, current job status is running, current job execution time: 0:56:13
- WARNING, job not marked completed, current job status is running, current job execution time: 0:56:23
- WARNING, job not marked completed, current job status is running, current job execution time: 0:56:33
- WARNING, job not marked completed, current job status is running, current job execution time: 0:56:44
- WARNING, job not marked completed, current job status is running, current job execution time: 0:56:54
- WARNING, job not marked completed, current job status is running, current job execution time: 0:57:04
- WARNING, job not marked completed, current job status is running, current job execution time: 0:57:15
- WARNING, job not marked completed, current job status is running, current job execution time: 0:57:25
- WARNING, job not marked completed, current job status is running, current job execution time: 0:57:35
- WARNING, job not marked completed, current job status is running, current job execution time: 0:57:46
- WARNING, job not marked completed, current job status is running, current job execution time: 0:57:56
- WARNING, job not marked completed, current job status is running, current job execution time: 0:58:06
- WARNING, job not marked completed, current job status is running, current job execution time: 0:58:17
- WARNING, job not marked completed, current job status is running, current job execution time: 0:58:27
- WARNING, job not marked completed, current job status is running, current job execution time: 0:58:37
- WARNING, job not marked completed, current job status is running, current job execution time: 0:58:47
- WARNING, job not marked completed, current job status is running, current job execution time: 0:58:58
- WARNING, job not marked completed, current job status is running, current job execution time: 0:59:08
- WARNING, job not marked completed, current job status is running, current job execution time: 0:59:18
- WARNING, job not marked completed, current job status is running, current job execution time: 0:59:29
- WARNING, job not marked completed, current job status is running, current job execution time: 0:59:39
- WARNING, job not marked completed, current job status is running, current job execution time: 0:59:49

- FAIL: Timeout of 10 hours has been hit, script stopped. Check iDRAC LC logs or Job Queue to debug.

Wallclock time is less than 5 hrs ... surely asking for the express+full diagnostics shouldn't time out (actually, I think it's about 3 hours, but I left the system, unattended for a while, and am unsure of exactly when it timed out).

As in another issue, I'd be happier with s/WARNING/STATUS/ but that's a spelling nit ;>
Having the deep diagnostics die due to a timeout is a bit of a fatal issue though.

btw: is -m1 any different than the LC "through" memory test and such? Same as 
racadm diagnostics run -m <mode> -r <reboot type> -s <start time> -e
<expiration time> ... although if I read the racadm manual correctly -m2 maps into the Python m1 ?

**Comment by texroemer** [comment]
Hi @KeithBierman 

Fixed script bug with max timeout for job status polling, new script has been uploaded.

I changed the wording for job status message from WARNING to STATUS.

RACADM command and Redfish script arguments are not the same. For Redfish script, i created the argument -m which maps to string values based off the schema. From the schema:


#DellLCService.RunePSADiagnostics |  
-- | --
RebootJobType@Redfish.AllowableValues |  
0 | "GracefulRebootWithForcedShutdown"
1 | "GracefulRebootWithoutForcedShutdown"
2 | "PowerCycle"
RunMode@Redfish.AllowableValues |  
0 | "Express"
1 | "ExpressAndExtended"
2 | "Extended"
target | "/redfish/v1/Dell/Managers/iDRAC.Embedded.1/DellLCService/Actions/DellLCService.RunePSADiagnostics"
