### ISSUE TITLE
unfortunate error message from DeviceFirmwareSimpleUpdateREDFISH.py

### ISSUE THREAD

**Issue by KeithBierman** [dell/iDRAC-Redfish-Scripting#130]
when given the wrong password, the error message I'm receiving is
"WARNING, iDRAC version installed does not support this feature using Redfish API" rather than an authentication focused message.

A meta note, it would be kind to NOT embed spaces in the critical directory names (indeed, any really) for cross platform simplicity.

**Comment by texroemer** [comment]
Hi @KeithBierman 

Script was not handling status code 401 correctly when executing first GET request to valid successful iDRAC connection. Script has been updated and new version uploaded.

Thanks
