### ISSUE TITLE
Invalid Request Method when POST to DellLCService.ExportLCLog

### ISSUE THREAD

**Issue by jkdba** [dell/iDRAC-Redfish-Scripting#131]
I am attempted to post to /redfish/v1/Managers/iDRAC.Embedded.1/DellLCService/Actions/DellLCService.ExportLCLog

I get an invalid request method error:

```json
{
    "error": {
        "@Message.ExtendedInfo": [
            {
                "Message": "Unable to run the method because the requested HTTP method is not allowed.",
                "MessageArgs": [],
                "MessageArgs@odata.count": 0,
                "MessageId": "IDRAC.1.6.SYS402",
                "RelatedProperties": [],
                "RelatedProperties@odata.count": 0,
                "Resolution": "Enter a valid HTTP method and retry the operation. For information about valid methods, see the Redfish Users Guide available on the support site.",
                "Severity": "Informational"
            }
        ],
        "code": "Base.1.2.GeneralError",
        "message": "A general error has occurred. See ExtendedInfo for more information"
    }
}
```

The account I am running as has highest privileges.

Example of Body I am posting:

```json
{
    "Password":  "password",
    "ShareName":  "sharename",
    "IPAddress":  "192.168.1.99",
    "UserName":  "svcAccount",
    "FileName":  "logile.log",
    "ShareType":  "CIFS"
}
```

I reviewed the documentation [here](https://topics-cdn.dell.com/pdf/idrac9-lifecycle-controller-v4x-series_api-guide_en-us.pdf) on page 130.

Running: **Idrac 9**, firmware: **3.34.34.34**

**Comment by texroemer** [comment]
Hi @jkdba 

The URI you are using is incorrect, it should be:

redfish/v1/**Dell**/Managers/iDRAC.Embedded.1/DellLCService/Actions/DellLCService.ExportLCLog

See page 77 in the API guide which shows this URI:

https://topics-cdn.dell.com/pdf/idrac9-lifecycle-controller-v3303030_api-guide_en-us.pdf

Thanks
Tex

**Comment by jkdba** [comment]
Thanks
