### ISSUE TITLE
Converting Event Message Ids to full description

### ISSUE THREAD

**Issue by jkdba** [dell/iDRAC-Redfish-Scripting#132]
I am building a custom log collection services that utilizes these endpoints:
- /redfish/v1/Managers/iDRAC.Embedded.1/Logs/Lclog
- /redfish/v1/Managers/iDRAC.Embedded.1/Logs/Sel

I noticed the resulting output contains a "MessageId" property with value such as `JCP042` is seems to be an "Event Message Id" that can be looked up [here](https://www.dell.com/support/manuals/it/it/itbsdt1/openmanage-software-9.0.1/eemi%2014g_1.00/jcp-event-messages?guid=guid-0e625f53-a82f-4f7d-9781-b5b1853174ee&lang=it-it). 

I did not find reference in the API [doc](https://topics-cdn.dell.com/pdf/idrac9-lifecycle-controller-v4x-series_api-guide_en-us.pdf) on how to retrieve the "Event Message Id" definition programmatically.

**Is this possible?**

I noted that the following endpoint for exporting the Lclog resulting file contains some form of translation of these Ids.

- /redfish/v1/Dell/Managers/iDRAC.Embedded.1/DellLCService/Actions/DellLCService.ExportLCLog

Unfortunately using this _action_ is unacceptable within my application.

I did attempt to looks at a log entry specifically with hopes it may contain more detail but was unsuccessful, it returns the same entry that is return from the collection service call.

- /redfish/v1/Managers/iDRAC.Embedded.1/Logs/Lclog/<-Id->

**Comment by texroemer** [comment]
Hi @jkdba 

To get details for a message ID, GET on URI "redfish/v1/Registries/Messages/EEMIRegistry" will have this information.

Example of running script to get details for message ID JCP042:

```
C:\Python38-32>GetIdracMessageRegistryREDFISH.py -ip 192.168.0.120 -u root -p calvin -s JCP042

Message ID: JCP042
Description: The (installation or configuration) job identified in the message cannot be run. For more information, see the Job Queue.
Message: Unable to run the (installation or configuration) job %1 because %2.
Severity: Warning
NumberOfArgs: 2
ParamTypes: ['string', 'string']
Resolution: Review the LC Log for related update, configuration, or collection job errors. Retry the operation. If the problem persists, contact your service provider.
```

**Comment by jkdba** [comment]
@texroemer thanks much this really reveals how terrible I am at searching pdf documentation. 😒

**Comment by jkdba** [comment]
@texroemer can you speak to the format of the MessageId Property of the Sel Log Collection Entry.

### Example:
**MessageId 800 = OSD063**

Sel Entry Sample
```PowerShell
@odata.id               : /redfish/v1/Managers/iDRAC.Embedded.1/Logs/Sel/89
@odata.type             : #LogEntry.v1_0_2.LogEntry
Created                 : 2020-01-07T10:33:03-05:00
Description             :  Log Entry 89
EntryCode               : {@{Member=Assert}}
EntryType               : SEL
Id                      : 89
Links                   :
Message                 : The process of installing an operating system or hypervisor is successfully completed.
MessageArgs             : {}
MessageArgs@odata.count : 0
MessageId               : 800
Name                    :  Log Entry 89
SensorNumber            : 0
SensorType              : {@{Member=BaseOSBoot/InstallationStatus}}
Severity                : OK
```
Upon Searching the Message Registry via Message text comparison Identify that the messageId in the registry is `OSD063`

```PowerShell
OSD063
Description  : The process of installing an operating system or hypervisor is successfully completed.
Message      : The process of installing an operating system or hypervisor is successfully completed.
NumberOfArgs : 0
Resolution   : No response action is required.
Severity     : Informational
```
Where the MessageId is stored in the same format as the registry in the Lclog.

**Comment by texroemer** [comment]
Hi @jkdba 

For SEL entry, refer to "redfish/v1/Schemas/LogEntry_v1.xml" schema for details on how these property values are calculated. For how to interpret the Message ID, IPMI spec has details of how Event Data 1,2,3 are used. Most of the time it is OEM information embedded based on different requirements of sensors. Please refer to IPMI Spec Section#29.7 and IPMI Spec section 29.4. 

https://www.intel.com/content/www/us/en/products/docs/servers/ipmi/ipmi-second-gen-interface-spec-v2-rev1-1.html
