### ISSUE TITLE
Downgrade versions

### ISSUE THREAD

**Issue by shaikk-arch** [dell/iDRAC-Redfish-Scripting#133]
Hi , 

I have list of servers which needs a Downgrade from Latest versions on both Bios and iLo firmware , Is there any specific RACADM command that i need follow ?

command - racadm -r <IP> -u <> -p <> update  /path of the file/.EXE 

This command doesn't work when i try to downgrade both firmware and bios 

FC630 - latest we are using 
BIOS Latest  - BIOS_2228J_WN64_2.9.1_01.EXE (2.9.1)
Firmware Latest - 2.70.70

Can you check and confirm , thank you.

**Comment by texroemer** [comment]
Hi @shaikk-arch 

Rollback FW for a device using RACADM, you need to use "racadm rollback" command but there must be a rollback version stored in the iDRAC itself for this to be supported on that device. If you are just trying to update to N-1 version of the BIOS, you can leverage "racadm update" command. 

If the update command is failing, can you tell me the exact error you are seeing? Is the command itself failing? Is the update job ID failing?

Thanks

**Comment by shaikk-arch** [comment]
Hi Texroemer,


I have tried with the same "racadm update" command to downgrade from latest BIOS version (2.91) to (2.80) it worked  on FC630 model. But do you think we need to follow for both firmwares while upgrade and downgrade versions vise from a to b , b to c  and c to d?
if so what are the mandate versions need to be followed do you know ?

Because i am noting these commands all in a script to make automation - what should be the consistency for upgrades on any versions ?because we have very old servers which are in 2.1.0 bios and 2.30 idrac versions which needs upgrades to 2.90 bios , 2.70 firmware

Thank you

**Comment by texroemer** [comment]
Hi @shaikk-arch 

Here's an article on which version you must update to first before going to latest for iDRAC firmware. Since you;re at 2.30, you need to update to 2.50 first, then you can update to 2.75 which is the latest.

https://www.dell.com/support/article/en-us/sln316137/idrac7-idrac8-red007-error-when-applying-latest-idrac-firmware-from-out-of-band-interface?lang=en

For BIOS, you should be able to update to the latest.

**Comment by shaikk-arch** [comment]
Ok thanks, do you suggest to upgrade Firmware to the latest first and then Bios ?
Because Bios - from 2.1.0 to 2.9.0 is failing , i will have to go version wise.
I have seen first upgrading Firmware first and then bios upgrade version wise works.

**Comment by texroemer** [comment]
Yes, i would recommend flashing iDRAC to latest first, then update the BIOS.

**Comment by shaikk-arch** [comment]
okay! sure! thanks again 

One more last quick question 

can you paste here correct racadm command to Power ON/OFF/RESET the server

**Comment by texroemer** [comment]
```
C:\Python38-32>racadm -r 192.168.0.120 -u root -p calvin --nocertwarn help serveraction

serveraction -- perform system power management operations

Usage:

racadm serveraction <action>
racadm serveraction <action> -f

-------------------------------------------------------------------------------

Valid Options:

-f        : Force the server power management operation.
            This option is applicable only for the POWEREDGE-VRTX platform.
            This option can be used with powerdown, powercycle and hardreset.
<action>  : server power management operation to perform.  Must be one of:
             graceshutdown   : perform a graceful shutdown of server
             powerdown       : power server off
             powerup         : power server on
             powercycle      : perform server power cycle
             hardreset       : force hard server power reset
             powerstatus     : display current power status of server
             nmi             : Genarate Non-Masking Interrupt to halt system operation

-------------------------------------------------------------------------------

Usage Examples:

- Power down server.
  racadm serveraction powerdown

- Get power status.
  racadm serveraction powerstatus

-------------------------------------------------------------------------------

For help on viewing the properties of a group, run the command - racadm help get
For help on configuring the properties of a group, run the command - racadm help set

-----------------------------------------------------------------------
```

**Comment by shaikk-arch** [comment]
Awesome! Thank you! Have a nice day!

**Comment by texroemer** [comment]
No problem, glad to help!
