### ISSUE TITLE
iDrac python scripts or request API for IPMI settings

### ISSUE THREAD

**Issue by Cheshir74** [dell/iDRAC-Redfish-Scripting#137]
Hello. How can i get and change  IPMI User Privileges ('Maximum LAN User Privilege Granted' and 'Enable Serial Over LAN') and IPMI Settings ('Enable IPMI Over LAN')? I don't find operation for it. Can you help me, Please? Which is request need?

**Comment by Cheshir74** [comment]
Wow! Maybe can i use racadm?

**Comment by texroemer** [comment]
Hi @Cheshir74 

GET on URI "redfish/v1/Managers/iDRAC.Embedded.1/Attributes" will return all iDRAC attributes which will list the attributes you want to change. PATCH on the same URI will set this attributes.

See example below where i'm setting these attributes using python script. Also this PATCH command is only supported on iDRAC 9. If using iDRAC 7/8, this PATCH operation is not supported and you will have to leverage using Server Configuration Profile (SCP) feature. If you are using iDRAC 7/8, let me know and i can give you an example using SCP to set these attributes.

```
C:\Python38-32>SetIdracLcSystemAttributesREDFISH.py -ip 192.168.0.130 -u root -p calvin -s idrac -an Users.3.IpmiLanPrivilege,Users.3.SolEnable,IPMILan.1.Enable -av Administrator,Enabled,Enabled

- INFO, configuring "IDRAC" attributes

 Attribute Name: Users.3.IpmiLanPrivilege, setting new value to: Administrator
 Attribute Name: Users.3.SolEnable, setting new value to: Enabled
 Attribute Name: IPMILan.1.Enable, setting new value to: Enabled

- PASS, PATCH command passed to successfully set "IDRAC" attribute(s), status code 200 returned

- INFO, getting new attribute current values

Attribute Name: Users.3.IpmiLanPrivilege, Attribute Value: Administrator
Attribute Name: Users.3.SolEnable, Attribute Value: Enabled
Attribute Name: IPMILan.1.Enable, Attribute Value: Enabled
```

**Comment by Cheshir74** [comment]
Unfortunately, i have few Dell with iDrac 7.

**Comment by texroemer** [comment]
For SCP, use "ImportSystemConfigurationLocalREDFISH" script. You will first need to modify the payload in the script for the POST command before executing it. Example below is executing the script to set these iDRAC attributes along with an example of the payload i passed in for POST. 

If you want to get all iDRAC attributes and current settings, use script "ExportSystemConfigurationLocalREDFISH.py".

```
C:\Python38-32>ImportSystemConfigurationLocalREDFISH.py -ip 192.168.0.130 -u root -p calvin

- JID_015974733082 successfully created for ImportSystemConfiguration method

- INFO, JobStatus not completed, current status: "Importing Server Configuration Profile.", percent complete: "20"
- PASS, job ID JID_015974733082 successfully marked completed

- Detailed configuration changes and job results for "JID_015974733082"

@odata.type: #DellManager.v1_0_0.ServerConfigurationProfileResults
DisplayValue: User Admin IPMI LAN Privilege
ErrCode: 0
Name: Users.3#IpmiLanPrivilege
NewValue: Administrator
OldValue: Operator
Severity: OK
Status: Success


@odata.type: #DellManager.v1_0_0.ServerConfigurationProfileResults
DisplayValue: User Admin SOL Enable
ErrCode: 0
Name: Users.3#SolEnable
NewValue: Enabled
OldValue: Disabled
Severity: OK
Status: Success


@odata.type: #DellManager.v1_0_0.ServerConfigurationProfileResults
DisplayValue: Enable or Disable IPMI over LAN
ErrCode: 0
Name: IPMILan.1#Enable
NewValue: Enabled
OldValue: Disabled
Severity: OK
Status: Success


Message: Successfully imported and applied Server Configuration Profile.
MessageArgs: []
MessageArgs@odata.count: 0
MessageId: SYS053


- JID_015974733082 completed in: 0:00:07

Payload example:

payload = {"ShareParameters":{"Target":"ALL"},"ImportBuffer":"<SystemConfiguration><Component FQDD=\"iDRAC.Embedded.1\"><Attribute Name=\"Users.3#IpmiLanPrivilege\">Administrator</Attribute><Attribute Name=\"Users.3#SolEnable\">Enabled</Attribute><Attribute Name=\"IPMILan.1#Enable\">Enabled</Attribute></Component></SystemConfiguration>"}
```

**Comment by Cheshir74** [comment]
Sorry, but i want change this parametr for each Dell with scripts. I before get users parametrs, after change it and send for each server. Maybe easier use racadm for it? Because too much operation with using SCP?

**Comment by texroemer** [comment]
If you are wanting to apply these attribute changes on multiple servers but each server have different settings, i would modify the script and pass in the attribute values as arguments to make the payload dynamic. Or you can create unique SCP files for each configuration and use ImportSystemConfigurationLocalFilenameREDFISH.py script to import the SCP file to each iDRAC.

**Comment by Cheshir74** [comment]
Ok, Thank you. I realized. I try it. But why you not recommend use racadm?

**Comment by texroemer** [comment]
You can use RACADM but you have to run set command for each attribute you want to configure. RACADM doesn't support setting multiple attributes using one command.

RACADM example running set command multiple times to set each attribute.

```
C:\Python38-32>racadm -r 192.168.0.130 -u root -p calvin --nocertwarn set idrac.Users.3.IpmiLanPrivilege Administrator
[Key=idrac.Embedded.1#Users.3]
Object value modified successfully

C:\Python38-32>racadm -r 192.168.0.130 -u root -p calvin --nocertwarn set idrac.Users.3.SolEnable Enabled
[Key=idrac.Embedded.1#Users.3]
Object value modified successfully

C:\Python38-32>racadm -r 192.168.0.130 -u root -p calvin --nocertwarn set idrac.IPMILan.Enable Enabled
[Key=idrac.Embedded.1#IPMILan.1]
Object value modified successfully
```

**Comment by Cheshir74** [comment]
Thank You
