### ISSUE TITLE
GetFirmwareInventoryREDFISH.py failure

### ISSUE THREAD

**Issue by KeithBierman** [dell/iDRAC-Redfish-Scripting#139]
Running GFI against 18 systems, 3 failed.
- WARNING, get current firmware version(s) for all devices in the system iDRAC supports

Traceback (most recent call last):
  File "/export/vol01/DELL/REDFISH/iDRAC-Redfish-Scripting/RedfishPyhon/GetFirmwareInventoryREDFISH.py", line 99, in <module>
    get_FW_inventory()
  File "/export/vol01/DELL/REDFISH/iDRAC-Redfish-Scripting/RedfishPyhon/GetFirmwareInventoryREDFISH.py", line 68, in get_FW_inventory
    for i in data[u'Members']:
KeyError: 'Members'
=======
Like various other scripts "WARNING" seems overly alarming, INFO or just the message would suffice ;>
But more problematic is that no inventory is being produced. All three produce this same error message. Since the other 15 execute fine, is there something in the system configuration that could be failing to meet with the scripts expectations?

**Comment by texroemer** [comment]
Hi @KeithBierman 

Returning no Members URIs in JSON output should never happen for GET response on URI "redfish/v1/UpdateService/FirmwareInventory/", seems iDRAC is in a bad state. Using a browser, can you manually run GET on URI "redfish/v1/UpdateService/FirmwareInventory/", see if Members property shows URIs?

I'm currently in the process of updating all scripts to change logging messaging. GetFirmwareInventoryREDFISH.py has been updated which i also added error handing for checking Members property in JSON output.

Thanks
Tex

**Comment by KeithBierman** [comment]
Using a browser I get into the idrac GUI and all looks sane. Due to
firewall/VPN complexity, I have to reverse tunnel and use localhost.

http://localhost:8443/%20redfish/v1/UpdateService/FirmwareInventory

which failed because it wanted https, and then https

https://localhost:8443/%20redfish/v1/UpdateService/FirmwareInventory
The requested URL / redfish/v1/UpdateService/FirmwareInventory was not
found on this server.

so I'm probably mangling that manual step.

But since the idrac seems completely sane (and system is up and
operational) it would be unfortunate if the idrac can be sane wrt GUI and
CLI, but only fail wrt redfish

**Comment by texroemer** [comment]
Can you try the new script i posted, see what it returns?

**Comment by KeithBierman** [comment]
git pull then reexecuted (same script, right?)
 dell_firminfo 10.192.9.156 Amazon123
iDRACIP                 = 10.192.9.156

- WARNING, get current firmware version(s) for all devices in the system
iDRAC supports

Traceback (most recent call last):
  File
"/export/vol01/DELL/REDFISH/iDRAC-Redfish-Scripting/RedfishPyhon/GetFirmwareInventoryREDFISH.py",
line 99, in <module>
    get_FW_inventory()
  File
"/export/vol01/DELL/REDFISH/iDRAC-Redfish-Scripting/RedfishPyhon/GetFirmwareInventoryREDFISH.py",
line 68, in get_FW_inventory
    for i in data[u'Members']:
KeyError: 'Members'


:/export/vol01/DELL/REDFISH/iDRAC-Redfish-Scripting/RedfishPy
hon$ git pull
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 3), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (4/4), done.
From https://github.com/dell/iDRAC-Redfish-Scripting
   5ac6673..97fe20d  master     -> origin/master
Updating 5ac6673..97fe20d
Fast-forward
 Redfish Python/GetFirmwareInventoryREDFISH.py | 32
++++++++++++++++++---------
 1 file changed, 22 insertions(+), 10 deletions(-)

Keith Bierman
khbkhb@gmail.com
303 997 2749

**Comment by texroemer** [comment]
Looks like it didn't pull the latest script version (version 5 is the latest) because the error still shows unicode for Members property in the code which i also removed. Can you confirm the script you downloaded is version 5?

**Comment by KeithBierman** [comment]
git pull shows no changes, but the script I have remains

# GetFirmwareInventoryREDFISH. Python script using Redfish API DMTF method
to ge
t current firmware version for all devices iDRAC supports for updates.
#....
# _author_ = Texas Roemer <Texas_Roemer@Dell.com>
# _version_ = 4.0
#...

git pull
Already up to date.
khb@UC1EDGPRDRAKC01
:/export/vol01/DELL/REDFISH/iDRAC-Redfish-Scripting/RedfishPy
hon$
Keith Bierman
khbkhb@gmail.com
303 997 2749

**Comment by texroemer** [comment]
Can you try git pull again? I just checked "https://github.com/dell/iDRAC-Redfish-Scripting/blob/master/Redfish%20Python/GetFirmwareInventoryREDFISH.py" and it shows version 5 reported.

**Comment by KeithBierman** [comment]
hon$ date && git pull
Mon Oct 19 15:54:41 UTC 2020
Already up to date.
khb@UC1EDGPRDRAKC01
:/export/vol01/DELL/REDFISH/iDRAC-Redfish-Scripting/RedfishPy
hon$
Keith Bierman
khbkhb@gmail.com
303 997 2749

**Comment by KeithBierman** [comment]
hon$ git remote -v
origin https://github.com/dell/iDRAC-Redfish-Scripting.git (fetch)
origin https://github.com/dell/iDRAC-Redfish-Scripting.git (push)
khb@UC1EDGPRDRAKC01
:/export/vol01/DELL/REDFISH/iDRAC-Redfish-Scripting/RedfishPy
hon$
Keith Bierman
khbkhb@gmail.com
303 997 2749

**Comment by KeithBierman** [comment]
FWIW, greping for version, this is after yet another pull (which claims
there's no updates)

AssignHotSpareREDFISH.py:# _version_ = 2
BackupRestoreImageREDFISH.py:# _version_ = 1.0
BiosChangePasswordREDFISH.py:# _version_ = 1.0
BiosDeviceRecoveryREDFISH.py:# _version_ = 1.0
BiosGetAttributesREDFISH.py:# _version_ = 3.0
BiosResetToDefaultsREDFISH.py:# _version_ = 2.0
BiosSetAttributeREDFISH.py:# _version_ = 11.0
BootToNetworkIsoOsdREDFISH.py:# _version_ = 1.0
CancelCheckConsistencyVirtualDiskREDFISH.py:# _version_ = 1.0
ChangeBiosBootOrderDMTF_REDFISH.py:# _version_ = 8.0
ChangeBootOrderBootSourceStateREDFISH.py:# _version_ = 3.0
ChangeIdracUserPasswordREDFISH.py:# _version_ = 8.0
CheckConsistencyVirtualDiskREDFISH.py:# _version_ = 4.0
ClearForeignConfigREDFISH.py:# _version_ = 6.0
ConvertToNonRAIDREDFISH.py:# _version_ = 2.0
ConvertToRAIDREDFISH.py:# _version_ = 2.0
CreateDeleteIdracUserREDFISH.py:# _version_ = 1.0
CreateIdracUserPasswordREDFISH.py:# _version_ = 1.0
CreateVirtualDiskREDFISH.py:# _version_ = 10.0
CreateXAuthTokenSessionREDFISH.py:# _version_ = 1.0
DeleteFirmwarePackageREDFISH.py:# _version_ = 1.0
DeleteJobIdREDFISH.py:# _version_ = 1.0
DeleteJobQueueREDFISH.py:# _version_ = 2.0
DeleteVirtualDiskREDFISH.py:# _version_ = 5.0
DellSlotCollectionREDFISH.py:# _version_ = 1.0
DellSwitchConnectionCollectionREDFISH.py:# _version_ = 2.0
DeviceFirmwareDellUpdateServiceREDFISH.py:# _version_ = 10.0
DeviceFirmwareDellUpdateServiceREDFISH.py:        idrac_version_verify =
int(major_number+minor_number)
DeviceFirmwareDellUpdateServiceREDFISH.py:        if idrac_version_verify
>= 330:
DeviceFirmwareSimpleUpdateREDFISH.py:# _version_ = 8.0
DeviceFirmwareSimpleUpdateTransferProtocolREDFISH.py:# _version_ = 6.0
EnableControllerEncryptionREDFISH.py:# _version_ = 2.0
ExportFactoryConfigurationREDFISH.py:# _version_ = 1.0
ExportHWInventoryREDFISH.py:# _version_ = 4.0
ExportImportSSLCertificateREDFISH.py:# _version_ = 1.0
ExportLCLogREDFISH.py:# _version_ = 2.0
ExportServerScreenShotREDFISH.py:# _version_ = 1.0
ExportSystemConfigurationLocalREDFISH.py:# _version_ = 6.0
ExportSystemConfigurationNetworkShareREDFISH.py:# _version_ = 8.0
ExportTechSupportReportREDFISH.py:# _version_ = 2.0
ExportThermalHistoryREDFISH.py:# _version_ = 1.0
ExportVideoLogREDFISH.py:# _version_ = 1.0
GetAssemblyInventoryREDFISH.py:# _version_ = 1.0
GetAvailableDisksREDFISH.py:# _version_ = 2.0
GetBiosBootOrderBootSourceStateREDFISH.py:# _version_ = 2.0
GetDeleteiDRACSessionsREDFISH.py:# _version_ = 2.0
GetDeleteJobQueueREDFISH.py:# _version_ = 1.0
GetDHSDisksREDFISH.py:# _version_ = 2.0
GetDiskOperationREDFISH.py:# _version_ = 2.0
GetEthernetInterfacesREDFISH.py:# _version_ = 3.0
GetFirmwareInventoryREDFISH.py:# _version_ = 4.0
GetIdracLcLogsREDFISH.py:# _version_ = 2.0
GetIdracLcSystemAttributesREDFISH.py:# _version_ = 6.0
GetIdracMessageRegistryREDFISH.py:# _version_ = 1.0
GetIdracServerSlotInformationREDFISH.py:# _version_ = 4.0
GetNvDimmInventoryREDFISH.py:# _version_ = 1.0
GetOSInformationREDFISH.py:# _version_ = 2.0
GetOSNetworkInformationREDFISH.py:# _version_ = 1.0
GetPCIeDeviceInventoryREDFISH.py:# _version_ = 2.0
GetPowerStateREDFISH.py:# _version_ = 2.0
GetRAIDLevelsREDFISH.py:# _version_ = 3.0
GetRemoteServicesAPIStatusREDFISH.py:# _version_ = 1.0
GetSchemaPrivilegesREDFISH.py:# _version_ = 1.0
GetSetBiosAttributesREDFISH.py:# _version_ = 12.0
GetStorageInventoryREDFISH.py:# _version_ = 3.0
GetSystemHWInventoryREDFISH.py:# _version_ = 7.0
IdracLicenseManagementREDFISH.py:# _version_ = 4.0
IdracRecurringJobOemREDFISH.py:# _version_ = 1.0
IdracResetToDefaultsREDFISH.py:# _version_ = 1.0
ImportForeignConfigREDFISH.py:# _version_ = 1.0
ImportSystemConfigurationLocalFilenameREDFISH.py:# _version_ = 14.0
ImportSystemConfigurationLocalREDFISH.py:# _version_ = 12.0
ImportSystemConfigurationNetworkSharePreviewREDFISH.py:# _version_ = 2.0
ImportSystemConfigurationNetworkShareREDFISH.py:# _version_ = 14.0
ImportSystemConfigurationPreviewLocalFilenameREDFISH.py:# _version_ = 1.0
InitializeVirtualDiskREDFISH.py:# _version_ = 4.0
InsertEjectVirtualMediaREDFISH.py:# _version_ = 2.0
InstallFromRepositoryREDFISH.py:# _version_ = 8.0
LCWipeREDFISH.py:# _version_ = 1.0
LockVirtualDiskREDFISH.py:# _version_ = 4.0
ManageIdracTimeREDFISH.py:# _version_ = 1.0
PrepareToRemoveREDFISH.py:# _version_ = 1.0
ReKeyREDFISH.py:# _version_ = 6.0
RemoveControllerKeyREDFISH.py:# _version_ = 2.0
RenameVdREDFISH.py:# _version_ = 1.0
ResetConfigStorageREDFISH.py:# _version_ = 3.0
ResetIdracREDFISH.py:# _version_ = 3.0
RunDiagnosticsREDFISH.py:# _version_ = 2.0
SecureBootResetKeysREDFISH.py:# _version_ = 1.0
SecureEraseDevicesREDFISH.py:# _version_ = 12.0
SensorCollectionREDFISH.py:# _version_ = 1.0
SetBiosDefaultSettingsREDFISH.py:# _version_ = 3.0
SetBootVdREDFISH.py:# _version_ = 1.0
SetChassisIndicatorLedREDFISH.py:# _version_ = 1.0
SetControllerKeyREDFISH.py:# _version_ = 2.0
SetEnclosureAssetTagREDFISH.py:# _version_ = 2.0
SetIdracDefaultSettingsREDFISH.py:# _version_ = 2.0
SetIdracLcSystemAttributesREDFISH.py:# _version_ = 8.0
SetNetworkDevicePropertiesREDFISH.py:# _version_ = 6.0
SetNextOneTimeBootDeviceREDFISH.py:# _version_ = 4.0
SetNextOneTimeBootVirtualMediaDeviceOemREDFISH.py:# _version_ = 2.0
SetPowerStateREDFISH.py:# _version_ = 3.0
SubmitTestEventREDFISH.py:# _version_ = 4.0
SubscriptionManagementREDFISH.py:# _version_ = 1.0
SupportAssistCollectionLocalREDFISH.py:# _version_ = 2.0
SupportAssistCollectionNetworkShareREDFISH.py:# _version_ = 1.0
SystemEraseREDFISH.py:# _version_ = 3.0
TestNetworkShareREDFISH.py:# _version_ = 1.0
UnpackAndAttachOsdREDFISH.py:# _version_ = 1.0

**Comment by KeithBierman** [comment]
I haven't managed to recreate this failure with version 5. Unclear to me why the git pull wasn't updating the localcodebase  (other updates had worked fine) but deleting and recloning seems to have worked). 

It would be a kindness to change Redfish\ $flavor to _ or - in place of the space. Although I can imagine that change might be disruptive for folks who factored the spaces into their flows.
