### ISSUE TITLE
GetFirmwareInventory

### ISSUE THREAD

**Issue by KeithBierman** [dell/iDRAC-Redfish-Scripting#141]
- Firmware inventory output is also captured in "fw_inventory.txt" file

It would be nice if either this was "write/append" or fw_inventory$counter so when running against an ensemble of systems we save all the data (obviously, its easy to wrap with | tee  or whatever, so this is a very low priority RFE at best.

**Comment by texroemer** [comment]
Hi @KeithBierman 

I updated the script to now generate unique filename based off the iDRAC IP.
