### ISSUE TITLE
CreateVirtualDiskREDFISH.py script does not support RAID-6 creation

### ISSUE THREAD

**Issue by disk91** [dell/iDRAC-Redfish-Scripting#142]
The API does not support RAID-6 Virtual disk creation when the controller supports it.

**Comment by texroemer** [comment]
Hi @disk91 

RAID 6 and 60 support using DMTF Redfish with iDRAC will be coming in next iDRAC release 4.40. This iDRAC release will be posted next month for download on Dell support site. 

Thanks

**Comment by disk91** [comment]
Thank you for your quick response !

**Comment by texroemer** [comment]
No problem!
