### ISSUE TITLE
Submit to PowerShell Gallery

### ISSUE THREAD

**Issue by benwa** [dell/iDRAC-Redfish-Scripting#143]
By including these modules in powershellgallery.com, customers can easily install them and keep them up-to-date.

**Comment by texroemer** [comment]
Hi @benwa 

Thanks for the suggestion, will work on getting these cmdlets added to Powershell gallery.

**Comment by texroemer** [comment]
Hi @benwa 

All cmdlets have been uploaded to Powershell gallery, search for keyword "iDRAC".

Thanks
