### ISSUE TITLE
ImportSystemConfigurationPreviewLocalFilenameREDFISH.py ERROR: read() takes no keyword arguments

### ISSUE THREAD

**Issue by dante-packet** [dell/iDRAC-Redfish-Scripting#151]
Hi 
I'm trying to run ImportSytemConfigurationPerviewLocalFileanmeREDFISH.py with the below command.
`python3 ImportSystemConfigurationPreviewLocalFilenameREDFISH.py -ip server_ip -u root -p calvin -f 2021-1-16_134041_export.xml`
But I'm getting this error
`Traceback (most recent call last):
  File "ImportSystemConfigurationPreviewLocalFilenameREDFISH.py", line 47, in <module>
    z=f.read(header=None,encoding='unicode_escape')
TypeError: read() takes no keyword arguments`

Thanks

**Comment by texroemer** [comment]
Hi @dante-packet 

Looks to be a python issue, can you tell me which version of Python 3 you are using? I just tried 3.8 in Windows and 3.6 in RHEL, unable to repro the issue you are seeing.

Thanks

**Comment by dante-packet** [comment]
Hi @texroemer,

I'm running `Python 3.8.2` installed in MacOS BigSur 11.1. I'll try to run it on my Linux machine and see if the will still occur. Thanks

**Comment by dante-packet** [comment]
Hey @texroemer, it seems like working now after upgrading python3.9.1. Thank you

**Comment by texroemer** [comment]
Great, good to hear!
