### ISSUE TITLE
Set-DeviceFirmwareSimpleUpdateREDFISH Gen8 iDrac not working

### ISSUE THREAD

**Issue by droorda** [dell/iDRAC-Redfish-Scripting#152]
When attempting to use Set-DeviceFirmwareSimpleUpdateREDFISH against Gen 8 iDracs the command works up till it attempts to upload a firmware package. The upload returns 'The underlying connection was closed: The connection was closed unexpectedly.'
The upload work correctly on Gen 9 idracs. I have ttried running a ticket through dell to correct the issue, but was not able to find the cause of the issue. 
The python script does not have the issue, and curl does not have the issue. This is specific to the method used by powershell. 
The things I have seen in my testing that may be helpful. 
When Curl encodes the uploads the file it is twice the size of when powershell does it. 
When using fiddler to monitor the upload, the connection is dropped at the end of the file upload. even if it should have extra boundary lines after the file they are not captured, instead I was regularly seeing a few extra hex characters HEX(43,40,3F,3F,02)

Testing was done with 
idrac firmware 2.75.75.75
Powershell 5.1 running on windows 10
Also tested with PWSH 7 and also fails

**Comment by texroemer** [comment]
Hi @droorda 

Thanks for bringing up this issue with Powershell and iDRAC8. I've escalated the issue to Dell iDRAC team, will give you an update once i find out any details. 

Thanks

**Comment by Iznik285** [comment]
Hi Tex, 

I've tested with 2.75.100.75 on iDRAC8 using Powershell 5.1 on Windows 10 and it also displays the same error as above. Are there any further updates?

**Comment by texroemer** [comment]
Hi @Iznik285  and @droorda 

I updated the cmdlet with a workaround to handle iDRAC 7/8 which leverages curl for the download of the firmware image. Curl is natively installed with newer versions of Windows (Examples: Windows 10, Windows Server 2019), if using older version of Windows, please install curl before running the cmdlet. 

Thanks
Tex
