### ISSUE TITLE
KeyError with iDrac 8

### ISSUE THREAD

**Issue by KCS007** [dell/iDRAC-Redfish-Scripting#154]
Maybe I'm not using it right, as my only purpose using this script is to export the iDRAC 7/8 license to a local directory (how do I set that directory?) without going through the web GUI. 

Running this command: 
`python3 ExportSystemConfigurationLocalREDFISH.py -ip 192.168.0.120 -u root -p calvin -t IDRAC -f XML`

Returns: 

```
- Job ID "JID_123808423055" successfully created for ExportSystemConfiguration method

Traceback (most recent call last):
  File "C:\Users\user\Downloads\iDRAC-Redfish-Scripting-master\ExportSystemConfigurationLocalREDFISH.py", line 177, in <module>
    print("- WARNING, JobStatus not completed, current status: \"%s\", percent complete: \"%s\"" % (data[u'Oem'][u'Dell'][u'Message'],data[u'Oem'][u'Dell'][u'PercentComplete']))
KeyError: 'Message'
```
Sometimes KeyError is 'Oem' as well.
iDRAC lifecycle logs show a successful connection and export:

`Successfully exported Server Configuration Profile.`

Navigating to URL https://192.168.0.120/redfish/v1/Managers/iDRAC.Embedded.1 returns: 
`{"@odata.context":"/redfish/v1/$metadata#Managers/Members/$entity","@odata.id":"/redfish/v1/Managers/iDRAC.Embedded.1","@odata.type":"#Managers.1.0.0.Manager","Actions":{"#Manager.Reset":{"ResetType@Redfish.AllowableValues":["GracefulRestart"],"target":"/redfish/v1/Managers/iDRAC.Embedded.1/Actions/Manager.Reset"}},"CommandShell":{"ConnectTypesSupported":["SSH, Telnet, IPMI"],"MaxConcurrentSessions":5,"ServiceEnabled":true},"DateTime":"2021-02-03T20:21:38-06:00","DateTimeLocalOffset":"-06:00","Description":"BMC","EthernetInterfaces":{"@odata.id":"/redfish/v1/Managers/iDRAC.Embedded.1/EthernetInterfaces"},"FirmwareVersion":"2.30.30.30","GraphicalConsole":{"ConnectTypesSupported":["KVMIP"],"MaxConcurrentSessions":6,"ServiceEnabled":true},"Id":"iDRAC.Embedded.1","Links":{"ManagerForChassis":[{"@odata.id":"/redfish/v1/Chassis/System.Embedded.1"}],"ManagerForServers":[{"@odata.id":"/redfish/v1/Systems/System.Embedded.1"}]},"LogServices":{"@odata.id":"/redfish/v1/Managers/iDRAC.Embedded.1/LogServices"},"ManagerType":"BMC","Model":"13G Monolithic","Name":"Manager","NetworkProtocol":{"@odata.id":"/redfish/v1/Managers/iDRAC.Embedded.1/NetworkProtocol"},"SerialInterfaces":{"@odata.id":"/redfish/v1/Managers/iDRAC.Embedded.1/SerialInterfaces"},"Status":{"Health":"Ok","State":"Enabled"},"UUID":"ffffffff-ffff-ffff-ffff-ffffffffffff","VirtualMedia":{"@odata.id":"/redfish/v1/Managers/iDRAC.Embedded.1/VirtualMedia"}}`

**Comment by texroemer** [comment]
@KCS007 

The script error was for querying the job ID, the job ID will still get marked completed by the iDRAC as you verified in the LC logs. I updated the script to handle this error condition, uploaded new version.

The script you're using is for exporting server configuration settings, it will not export the iDRAC license. There is Redfish support for exporting the iDRAC license but only for iDRAC9. If using iDRAC 7/8, you will need to use RACADM command (see below)


```
C:\Python39>racadm -r 192.168.0.120 -u root -p calvin --nocertwarn help license

License -- License Manager commands
Required License -- Licensing Management

License has multiple subcommands, view the help
as shown below.

Usage:

racadm license help view
racadm license help delete
racadm license help replace
racadm license help import
racadm license help export

-----------------------------------------------------

For help on viewing the properties of a group, run the command - racadm help get
For help on configuring the properties of a group, run the command - racadm help set

-----------------------------------------------------------------------


C:\Python39>racadm -r 192.168.0.120 -u root -p calvin --nocertwarn license help export

License export - Exports licenses from various devices on the server.

Usage:

racadm license export -u <username> -p <password> -f <license file name>\
-l <NFS/CIFS share>  -t <transaction ID>

racadm license export -u <username> -p <password> -f <license file name>\
-l <NFS/CIFS share>  -e <entitlement ID>

racadm license export -u <username> -p <password> -f <license file name>\
-l <NFS/CIFS share>  -c  <FQDD>

------------------------------------------------------------------------------

Valid Options:

-c: FQDD name of the device from where the license file has to be exported.
-e: Entitlement ID of the license to be exported.
-t: Transaction ID of the license to be exported.
-l: Network share location (see Usage Examples section for NFS or CIFS share)
    or local file system to which the  license file must be exported.
-f: Destination license file name. If a filename is not entered, the license
    file is assigned  <servicetag>_<entitlement ID>.xml
-u: Username of the system where the file will be exported.
-p: Password of the user on the system where the file will be exported.


NOTE: This command supports both IPV4 and IPV6 formats. IPV6 is applicable only for CIFS remote share.

------------------------------------------------------------------------------

Usage Examples:

-Export license to a NFS share using transaction ID,
 in this case transaction 27 :
 racadm license export -f License.xml -l 192.168.2.140:/licshare -t 27

-Export license to a CIFS share specifying the entitlement ID,
 in this case abcdxyz :
 racadm license export -u admin -p passwd -f License.xml
 -l //192.168.2.140/licshare -e abcdxyz

-Export license to a CIFS share specifying the FQDD. While using the
 -c option and exporting license(s) from a device, more than one license file
 may be exported. Therefore if a file name is given, an index will be
 appended to the end of the file name such as LicenseFile0.xml,
 LicenseFile1.xml and so on. In this case, the device is Embedded iDrac :
 racadm license export -u root -p calvin -f LicenseFile.xml
 -l //192.168.2.140/licshare -c idrac.embedded.1
```

**Comment by KCS007** [comment]
Took me a while, but I found a RACADM command that will export the license to the location it is run. RACADM is very picky about syntax and the order of the options. Anything without `-c` will not work. Can't get it to export to any other local folder with `-l` either.

`racadm -r 192.168.0.120 -u root -p calvin license export -c idrac.embedded.1 --nocertwarn`

**Comment by texroemer** [comment]
Are you saying -t or -e is not working for export command? -l argument is only used if you are exporting to a network share. If you want to export locally to a certain directory path, use -f argument passing in directory path with unique file name.

Examples of using -t and -f below. -t example will export the license with transaction ID 3 to the same directory i'm running the RACADM command from. 

```
C:\Python39>racadm -r 192.168.0.120 -u root -p calvin --nocertwarn license export -t 3
License file exported successfully.

C:\Python39>racadm -r 192.168.0.120 -u root -p calvin --nocertwarn license export -t 3 -f C:\R630_iDRAC_license.xml
License file exported successfully.

```
