### ISSUE TITLE
The time lifecycle of task for redfish firmware simple-update 

### ISSUE THREAD

**Issue by Kdy77k** [dell/iDRAC-Redfish-Scripting#160]
Hi
I do the following operation:
post https://<ip>/redfish/v1/UpdateService/Actions/UpdateService.SimpleUpdate
{
"ImageURI":"<ip2>/firmware/Dell/iDRAC-with-Lifecycle-Controller_Firmware_62GW1_WN64_4.40.00.00_A00.EXE",
    "TransferProtocol":"HTTP",
    "UserName":"a",
    "Password":"b"
}
The head field "location" of response is the task url.
**My question is how long does the task still last after the firmware updating finishing or terminated
I find that the task will last extra about 10 sec after the firmware updating finishing or terminated.
How to adjust the extra last time of task?
Idrac redfish also supports "job" in job-services with the same taskId. Does the "job" last forever till reboot or reset. Is it right?**

**Comment by texroemer** [comment]
Hi @Kdy77k 

Current behavior for TaskService/Tasks/<job ID> is once the job ID is marked completed, within a few seconds the job will get auto deleted. Coming in iDRAC 5.00.00 this June, this task job ID will not get auto deleted until after 10 minutes. Also in future iDRAC releases, we are looking into adding an option where the user can configure this timeout (currently not supported).

As a workaround, you can use JobService/Jobs/<job ID> to check the job status which this URI doesn't get auto deleted. 

Thanks
