### ISSUE TITLE
Improvement Ideas

### ISSUE THREAD

**Issue by EugenStelea** [dell/iDRAC-Redfish-Scripting#162]
Greetings!
First of all thank you for this great repo! It's really useful, and I use a lot of modules / functions.
However, there are some things that can be improved in my opinion.

1. The structure seems to be overcomplicated. Why having a lot of psm1 files, each one in it's own folder and not a single module with all the functions included? It would be a lot easier to maintain (from a customer perspective). I ended up creating my own module where I copied all the functions I use from this repo. But if a function gets updated, I have download it and update my module as well.
I see the same (more or less) modules published individually on PowerShell gallery. 
A single module with all functions built-in would be a great plus.

2. I have a little problem with the output of the functions.
For example, this is the output of the Get-StorageInventoryRedfish function:

```
- PASS, statuscode 200 returned successfully to get storage controller(s)

- Server controllers detected -

RAID.Slot.6-1
AHCI.Embedded.1-1
AHCI.Embedded.2-1
```

The "useful" data is mixed with the REST Status code and some other text.
Is it very tricky to:
- extract the "useful" data
- manage error handling.
To accomplish a more elaborate task (such as creating a virtual disk), you need to call the function several times (to get the controllers, disks and so on). When the output is like this, it's really tricky to get it working out-of-the box.
I ended up commenting all the lines that output informational stuff.
I would prefer that the functions return an PSobject where they can have a status code (Error / OK, or whatever) and relevant data that can be further manipulated.

Of course, I can simply take the code blocks that I need and use them however I want, but it is time consuming and if there will be any change in the API, I would have to start from scratch.
This is meant to be constructive feed-back and I hope it is not off-topic.
Many thanks again!

**Comment by texroemer** [comment]
Hi @EugenStelea 

Thank you for the feedback, will work on incorporating this to improve Powershell support.

Thanks

**Comment by texroemer** [comment]
Hi @EugenStelea 

Wanted to give you an update on improving the cmdlets, i created IdracRedfishSupport module which will load all cmdlets available on GitHub. This module is also available on Powershell gallery to install. 

For each cmdlet loaded, i added Get-Credential and X-auth token session support to execute them besides using iDRAC username and password arguments. The are also multiple new cmdlets uploaded (Few examples: launch remote kvm session, export video log, generate CSR). 

Thanks
Tex

**Comment by EugenStelea** [comment]
Hi, @texroemer 
Looking good!
Thank you!
