### ISSUE TITLE
Generating CSR with python redfish

### ISSUE THREAD

**Issue by djcutch** [dell/iDRAC-Redfish-Scripting#163]
So i seem to find an issue with the script not liking - in the name of the email address.

{'CertificateCollection': '/redfish/v1/Managers/iDRAC.Embedded.1/NetworkProtocol/HTTPS/Certificates', 'City': 'some city', 'CommonName': 'servername.fdqn', 'Email': 'user-home@company.com', 'Country': 'US', 'Organization': 'org', 'OrganizationalUnit': 'home', 'State': 'mi'}
- FAIL, generate CSR failed, status code 400 returned, detailed error results: 
{'error': {'@Message.ExtendedInfo': [{'Message': 'Invalid value for the parameter, Email.', 'MessageArgs': ['Email'], 'MessageArgs@odata.count': 1, 'MessageId': 'IDRAC.2.2.LC017', 'RelatedProperties': [], 'RelatedProperties@odata.count': 0, 'Resolution':

**Comment by texroemer** [comment]
Hi @djcutch 

Thank you for escalating this which is an issue in the iDRAC code, dash in string value for Email parameter is failing. I have escalated this issue and will be fixed in next iDRAC release 5.00.00 scheduled to be released this June.

Thanks
Tex
