### ISSUE TITLE
About the credentials of http image server for redfish simple update

### ISSUE THREAD

**Issue by Kdy77k** [dell/iDRAC-Redfish-Scripting#165]
I use the following post command to update firmware and get command to track the progress of provisioning:

post https://192.168.1.1/redfish/v1/UpdateService/Actions/UpdateService.SimpleUpdate
{
    "ImageURI":"http://abc:123@192.168.100.100/firmware/idrac8/iDRAC-with-Lifecycle-Controller_Firmware_DPV0R_WN64_2.75.100.75_A00.EXE",
    "TransferProtocol":"HTTP"
}
or
{
    "ImageURI":"http://192.168.100.100/firmware/Dell/iDRAC-with-Lifecycle-Controller_Firmware_DPV0R_WN64_2.75.100.75_A00.EXE",
    "TransferProtocol":"HTTP",
    "UserName":"abc",
    "Password":"123"
}

get https://192.168.1.1/redfish/v1/TaskService/Tasks/JID_171396510696

{
    "@odata.context": "/redfish/v1/$metadata#Task.Task",
    "@odata.id": "/redfish/v1/TaskService/Tasks/JID_171396510696",
    "@odata.type": "#Task.v1_1_1.Task",
    "Description": "Server Configuration and other Tasks running on iDRAC are listed here",
    "EndTime": "2021-03-30T16:27:47-05:00",
    "Id": "JID_171396510696",
    "Messages": [
        {
            "Message": "The specified user credentials necessary for downloading an update package were not correct.",
            "MessageArgs": [],
            "MessageArgs@odata.count": 0,
            "MessageId": "RED050"
        }
    ],
    "Messages@odata.count": 1,
    "Name": "Firmware Update: Generic",
    "Oem": {
        "Dell": {
            "@odata.type": "#DellJob.v1_0_1.DellJob",
            "CompletionTime": "2021-03-30T16:27:47",
            "Description": "Job Instance",
            "EndTime": null,
            "Id": "JID_171396510696",
            "JobState": "Completed",
            "JobType": "FirmwareUpdate",
            "Message": "The specified user credentials necessary for downloading an update package were not correct.",
            "MessageArgs": [],
            "MessageId": "RED050",
            "Name": "Firmware Update: Generic",
            "PercentComplete": 0,
            "StartTime": "TIME_NOW",
            "TargetSettingsURI": null
        }
    },
    "StartTime": "",
    "TaskState": "Completed",
    "TaskStatus": "Critical"
}
The credentials for image http server (192.168.1.1) are correct. But why the Idrac server always returns error code "RED050"

**Comment by Kdy77k** [comment]
@texroemer

**Comment by texroemer** [comment]
Hi @Kdy77k 

Found out there are no future plans to add HTTP auth support to iDRAC 7/8. If you're unable to use HTTP with no auth as a workaround, you'll need to escalate this concern to Dell tech support team which this will go through the issue escalation process. 

Thanks

**Comment by Kdy77k** [comment]
@texroemer 
Thank you for your reply.
1. I want to know whether Idrac9 also don't support Http authentication?
2. If there is a plan to support Https in the future on Idrac8 and Idrac9 platform?

**Comment by Kdy77k** [comment]
Thank you so much. :)

**Comment by texroemer** [comment]
No problem, glad to help.
