### ISSUE TITLE
Firmware Inventory not showing info for some interfaces

### ISSUE THREAD

**Issue by kgrvamsi** [dell/iDRAC-Redfish-Scripting#167]
Hello @texroemer 

i followed this script with the redfish api and i see that its missing showing some of the interfaces info

https://github.com/dell/iDRAC-Redfish-Scripting/blob/master/Redfish%20Python/GetFirmwareInventoryREDFISH.py

Interfaces server have : 

```
"Members": [
        {
            "@odata.id": "/redfish/v1/Systems/System.Embedded.1/EthernetInterfaces/NIC.Integrated.1-2-1"
        },
        {
            "@odata.id": "/redfish/v1/Systems/System.Embedded.1/EthernetInterfaces/NIC.Integrated.1-3-1"
        },
        {
            "@odata.id": "/redfish/v1/Systems/System.Embedded.1/EthernetInterfaces/NIC.Integrated.1-4-1"
        },
        {
            "@odata.id": "/redfish/v1/Systems/System.Embedded.1/EthernetInterfaces/NIC.Integrated.1-1-1"
        },
        {
            "@odata.id": "/redfish/v1/Systems/System.Embedded.1/EthernetInterfaces/NIC.Slot.7-2-1"
        },
        {
            "@odata.id": "/redfish/v1/Systems/System.Embedded.1/EthernetInterfaces/NIC.Slot.7-1-1"
        },
        {
            "@odata.id": "/redfish/v1/Systems/System.Embedded.1/EthernetInterfaces/NIC.Slot.5-2-1"
        },
        {
            "@odata.id": "/redfish/v1/Systems/System.Embedded.1/EthernetInterfaces/NIC.Slot.5-1-1"
        },
        {
            "@odata.id": "/redfish/v1/Systems/System.Embedded.1/EthernetInterfaces/NIC.Slot.2-2-1"
        },
        {
            "@odata.id": "/redfish/v1/Systems/System.Embedded.1/EthernetInterfaces/NIC.Slot.2-1-1"
        }
    ],
```

The Firmware Inventory API shows data for the following

```
@odata.id": "/redfish/v1/Dell/UpdateService/FirmwareInventory/DellSoftwareInventory/DCIM:CURRENT_0x23_701__NIC.Slot.5-1-1",
"@odata.id": "/redfish/v1/Dell/UpdateService/FirmwareInventory/DellSoftwareInventory/DCIM:CURRENT_0x23_701__NIC.Slot.5-2-1",
"@odata.id": "/redfish/v1/Dell/UpdateService/FirmwareInventory/DellSoftwareInventory/DCIM:CURRENT_0x23_701__NIC.Integrated.1-2-1",
"@odata.id": "/redfish/v1/Dell/UpdateService/FirmwareInventory/DellSoftwareInventory/DCIM:CURRENT_0x23_701__NIC.Slot.7-1-1",
"@odata.id": "/redfish/v1/Dell/UpdateService/FirmwareInventory/DellSoftwareInventory/DCIM:INSTALLED_0x23_701__NIC.Slot.7-2-1",
"@odata.id": "/redfish/v1/Dell/UpdateService/FirmwareInventory/DellSoftwareInventory/DCIM:INSTALLED_0x23_701__NIC.Slot.5-1-1",
"@odata.id": "/redfish/v1/Dell/UpdateService/FirmwareInventory/DellSoftwareInventory/DCIM:INSTALLED_0x23_701__NIC.Slot.5-2-1",
"@odata.id": "/redfish/v1/Dell/UpdateService/FirmwareInventory/DellSoftwareInventory/DCIM:INSTALLED_0x23_701__NIC.Integrated.1-2-1",
"@odata.id": "/redfish/v1/Dell/UpdateService/FirmwareInventory/DellSoftwareInventory/DCIM:INSTALLED_0x23_701__NIC.Slot.7-1-1",
"@odata.id": "/redfish/v1/Dell/UpdateService/FirmwareInventory/DellSoftwareInventory/DCIM:PREVIOUS_0x23_701__NIC.Slot.5-1-1",
"@odata.id": "/redfish/v1/Dell/UpdateService/FirmwareInventory/DellSoftwareInventory/DCIM:PREVIOUS_0x23_701__NIC.Slot.5-2-1",
"@odata.id": "/redfish/v1/Dell/UpdateService/FirmwareInventory/DellSoftwareInventory/DCIM:PREVIOUS_0x23_701__NIC.Integrated.1-2-1",
"@odata.id": "/redfish/v1/Dell/UpdateService/FirmwareInventory/DellSoftwareInventory/DCIM:PREVIOUS_0x23_701__NIC.Slot.7-1-1",
```

Any idea on how to fetch the other interface firmware details?

**Comment by texroemer** [comment]
Hi @kgrvamsi 

The behavior you are seeing is not correct. For the integrated network card you should be seeing a FW entry for each port on the card. Are you using latest iDRAC9 4.40? If not, can you update to 4.40 and once iDRAC is back up, reboot the server to run Collecting Inventory after POST which will refresh iDRAC FW inventory. Then check from Redfish to see if its reporting FW inventory correctly now. 

Thanks
Tex

**Comment by capriguy84** [comment]
I noticed something slightly different on my boxes. The version string is empty for PCI slot nics and URLs contain space in them. FTR, I am seeing this on idrac9 4.40. The NIC version is empty for PCI slot card name "Intel(R) Ethernet Server Adapter X520-2 - $MACADDR". I started seeing this recently and this has persisted reboot and also re-inventory by LC.

    {
      "@odata.id": "/redfish/v1/UpdateService/FirmwareInventory/Installed-0-        __NIC.Slot.1-1"
    },
    {
      "@odata.id": "/redfish/v1/UpdateService/FirmwareInventory/Installed-0-        __NIC.Slot.1-2"
    },
    {
      "@odata.id": "/redfish/v1/UpdateService/FirmwareInventory/Installed-0-        __NIC.Slot.2-1"
    },
    {
      "@odata.id": "/redfish/v1/UpdateService/FirmwareInventory/Installed-0-        __NIC.Slot.2-2"
    }

**Comment by texroemer** [comment]
Hi @capriguy84 

Can you update to latest FW version for the Intel card which is 19.5.12 on Dell support site, see if issue is resolved. If issue still exists after updating the NIC FW, you will need to escalate this issue to Dell support so they can debug the server.

Thanks
Tex
