### ISSUE TITLE
Question: Can the Redfish API change the BIOS clock?

### ISSUE THREAD

**Issue by bbollard** [dell/iDRAC-Redfish-Scripting#170]
Hello,
I am wondering if there is capability within the Redfish API to set the system BIOS clock time (not the iDRAC time/time zone). The systems I am working on are Dell R740xd systems with various iDRAC firmware versions.

Thank you for your help.

Regards,
Brian

**Comment by texroemer** [comment]
Hi @bbollard 

Currently there is no remote way to configure BIOS time and date, only supported from BIOS F2 Setup. But when an OS is installed, BIOS date/time will automatically get synced with OS time/date. 

Are you seeing an issue where you have OS installed and BIOS time/date is not in sync with the OS?

Thanks
Tex

**Comment by bbollard** [comment]
@texroemer,
This is an edge case situation where we are attempting to deploy headless Dell VxRail nodes at remote datacenters which have ESX running DHCP. Before we run the VxRail set up we want to have all nodes clock's close to in sync otherwise the set up process may fail (cert issues, etc.). So I am evaluating various means to set the clock. Right now it's a struggle but I get the Host OS IP from the PT Agent info in iDRAC using WS-MAN then connect to ESX and set the time. Connecting to the iDRAC which has by this point already been configured with a static IP and known hostname and invoking a simple Redfish API would have been easier.

Thanks for the reply.

Regards,
Brian
