### ISSUE TITLE
Is HTTPs supported for updating firmware using SimpleUpdate on iDRAC 9?

### ISSUE THREAD

**Issue by ylvmw** [dell/iDRAC-Redfish-Scripting#172]
I just have a question about is HTTPs supported for updating firmware using SimpleUpdate? I know HTTP is supported, either with the [doc](https://www.dell.com/support/manuals/en-in/idrac9-lifecycle-controller-v3.36.36.36/idrac9_3.36_redfishapiguide/updating-firmware-using-simpleupdate?guid=guid-97450585-1a7c-48a4-b7e5-8385585e2d8b&lang=en-us) or trying the API, but failed with HTTPs. And I also tried the "https://<idrac>/redfish/v1/UpdateService" API, it returns 
            "TransferProtocol@Redfish.AllowableValues": [
                "HTTP"
            ],
seems only HTTP supported.

Actually we'd like to put the firmwares to be installed on the HTTPs servers for security.

So I want to double confirm with you if the HTTPs supported or not. Thanks!

**Comment by texroemer** [comment]
Hi @ylvmw 

Current latest shipping iDRAC, only HTTP is supported but coming in iDRAC 5.00.00 which is scheduled to be released this June, HTTPS/NFS/CIFS/TFTP support has been added to TransferProtocol.

If you need to leverage HTTPS support now, use OEM action DellSoftwareInstallationService.InstallFromURI. 

Thanks

**Comment by ylvmw** [comment]
Thank you so much @texroemer. Could the Dell R740 be upgraded to iDRAC 5.00.00?

**Comment by texroemer** [comment]
@ylvmw 

Yes it will be supported on R740 platform. Sorry I forgot to mention 5.00.00 will be iDRAC9 release.

Thanks
