### ISSUE TITLE
iDRAC Version Check

### ISSUE THREAD

**Issue by Iznik285** [dell/iDRAC-Redfish-Scripting#174]
Hi Tex

Many thanks for this repository.  It's full of very useful information that has helped me with automating my work.
I am primarily using the Powershell scripts. 

As part of a script I am developing I wondered if it is possible to identify an IDRAC card as version 8 or 9 using Redfish?
I can get the iDRAC version number and could convert it but is there was a more straight forward way?  

Your recommendations would be very helpful.

**Comment by texroemer** [comment]
Hi @Iznik285 

Best way to tell if the server is using iDRAC 7/8 or 9 is to check the server model. GET on URI "redfish/v1/Managers/iDRAC.Embedded.1?$select=Model", if 14G or 15G, iDRAC 9. If 12G or 13G, iDRAC 7/8.

Thanks
Tex

**Comment by Iznik285** [comment]
I've tested and it's worked as you've suggested. Many thanks for your help.
