### ISSUE TITLE
Set-IdracLcSystemAttributesREDFISH IPv4.1.Gateway not applied

### ISSUE THREAD

**Issue by lupuscon** [dell/iDRAC-Redfish-Scripting#178]
**Hardware:**
Dell PowerEdge R740
Dell PowerEdge R7515 (iDrac9-Version: 5.00.00.00)

**PSVersionTable:**
Name                           Value                                                                                                     
----                           -----                                                                                                     
PSVersion                      5.1.17763.1852                                                                                            
PSEdition                      Desktop                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                   
BuildVersion                   10.0.17763.1852                                                                                           
CLRVersion                     4.0.30319.42000                                                                                           
WSManStackVersion              3.0                                                                                                       
PSRemotingProtocolVersion      2.3                                                                                                       
SerializationVersion           1.1.0.1

**Latest Commit Uppon Download**: 0e30fe18e3dbdb05ffe6bacf26e9e93016ea8840

**Script:**
```
#Variables (actually feed via json, the three lines below just show which value they have before the actual command) 
$server.iDRAC_StaticHostIP = "10.130.1.143"
$server.iDRAC_Gateway = "10.130.1.254"
$server.iDRAC_Subnet = "255.255.255.0"

# Set Network Configuration (IPv4,Gateway,Subnet)
   $iDRAC_settings= "IPv4.1.DHCPEnable:Disabled|IPv4.1.Address:$($server.iDRAC_StaticHostIP)|IPv4.1.Gateway:$($server.iDRAC_Gateway)|IPv4.1.Netmask:$($server.iDRAC_Subnet)"
   Set-Content "$configPath\multiple_idrac_lc_system_attributes.txt" $iDRAC_settings
   Set-IdracLcSystemAttributesREDFISH -attribute_group idrac -idrac_ip $server.iDRAC_DhcpIP -idrac_password $server.iDRAC_DefaultPW -idrac_username root -file_path $configPath
```
   
 **Expected behavior:**
![iDRac_IPv4](https://user-images.githubusercontent.com/19332227/126286172-a9dfbd7c-b067-4a40-b876-60baf51e0e78.png)

**Actual behavior:**
![iDRac_IPv4_actual](https://user-images.githubusercontent.com/19332227/126286948-ffae6e6f-e524-402a-87ab-988d35636423.png)

**Description:**
Somehow the gateway has a static value anywhere in the API of iDRAC.
I checked my script and also the module i used, none of them set it to this value, which raises the question, where the entry comes from.
DISCLAIMER: I had to manually create the screenshot with the value i saw, because at the time i faced it i did not thought it might be a iDRAC or REDFISH issue but more a issue with my own script.

**Comment by lupuscon** [comment]
I just deployed a second Dell Server (PowerEdge R7515), i faced a similar issue.
The selected value for the Default Gateway was once again ignored and set to 192.168.0.1
Additionally the iDrac Static IP i selected was ignored and instead set to 192.168.0.120

**Comment by texroemer** [comment]
Hi @lupuscon 

For configuring iDRAC static IP address, gateway and subnet, you must use attributes:

IPv4Static.1.Address
IPv4Static.1.Netmask
IPv4Static.1.Gateway

See example below where i disabled DHCP and set static network for iDRAC, confirmed attributes were changed using RACADM.

```
PS C:\Users\administrator> Set-IdracLcSystemAttributesREDFISH -idrac_ip 100.65.84.160 -idrac_username root -idrac_password calvin -attribute_group idrac -file_path C:\Users\Texas_Roemer\Documents\WindowsPowerShell\Modules\Set-IdracLcSystemAttributesREDFISH

- WARNING, attribute IPv4Static.1.Address current value is: 192.168.0.120, setting new value to: 100.65.84.30
- WARNING, attribute IPv4.1.DHCPEnable current value is: Enabled, setting new value to: Disabled
- WARNING, attribute IPv4Static.1.Netmask current value is: 255.255.255.0, setting new value to: 255.255.255.0
- WARNING, attribute IPv4Static.1.Gateway current value is: 192.168.0.254, setting new value to: 100.65.84.254

- PASS, statuscode 200 returned to successfully set "IDRAC" attributes

- PASS, statuscode 200 returned successfully to get "IDRAC" attributes

- PASS, attribute IPv4Static.1.Address current value is successfully set to: 100.65.84.30
- PASS, attribute IPv4.1.DHCPEnable current value is successfully set to: Disabled
- PASS, attribute IPv4Static.1.Netmask current value is successfully set to: 255.255.255.0
- PASS, attribute IPv4Static.1.Gateway current value is successfully set to: 100.65.84.254
PS C:\Users\administrator> racadm -r 100.65.84.30 -u root -p calvin get idrac.ipv4static --nocertwarn
[Key=idrac.Embedded.1#IPv4Static.1]
Address=100.65.84.30
DNS1=192.168.0.120
DNS2=192.168.0.130
DNSFromDHCP=Disabled
Gateway=100.65.84.254
Netmask=255.255.255.0
```

**Comment by lupuscon** [comment]
Hi @texroemer 

Thank you for the hint, i did not notice these values exist.
Since i was not able to find a mapout of attributes i used the output i got from reading all the attributes via Powershell.

Can you point me into the right direction how to find the correct attributes without having to bother you for every single attribute i am using? Would really appreciate it.

Thank you in advance.

KR
Oliver
