### ISSUE TITLE
How to cancel the firmware updating procedure and/or Ramdisk #redfish

### ISSUE THREAD

**Issue by Kdy77k** [dell/iDRAC-Redfish-Scripting#180]
How to cancel the provisioning procedure via standard redfish simple-Update spec? I invoke a firmware updating or setup/boot-up with Ramdisk, I want to know how to cancel the firmware update and/or Ramdisk via redfish standard spec?

**Comment by texroemer** [comment]
Hi @Kdy77k 

Can you give more details on what device did you execute firmware update for? Was it an immediate update device (example: iDRAC) or a staged update device (example: BIOS)? If immediate update device, there is no way to cancel the update once the process has started. If staged update device, if the server hasn't rebooted and started the execution of the update task, then it can be cancelled by deleting the job ID.

Thanks
Tex

**Comment by Kdy77k** [comment]
@texroemer  Thank you for your reply. Will Idrac support something like "cancel" or "hang-on" interface as standard or OEM redfish interface in the future? :)
