### ISSUE TITLE
InitializeVirtualDiskREDFISH.py fails saying resource not found

### ISSUE THREAD

**Issue by stranger12345678** [dell/iDRAC-Redfish-Scripting#183]
`./InitializeVirtualDiskREDFISH.py $args -v RAID.Slot.5-1
`
- Virtual disk(s) detected for controller RAID.Slot.5-1 -

Disk.Virtual.0:RAID.Slot.5-1, Volume Type: NonRedundant
Disk.Virtual.1:RAID.Slot.5-1, Volume Type: NonRedundant
Disk.Virtual.2:RAID.Slot.5-1, Volume Type: NonRedundant
Disk.Virtual.3:RAID.Slot.5-1, Volume Type: NonRedundant

`./InitializeVirtualDiskREDFISH.py $args -V Disk.Virtual.1:RAID.Slot.5-1 --init Slow
`
- FAIL, POST command failed, status code is 404

- POST command failure is:
 {u'error': {u'code': u'Base.1.2.GeneralError', u'message': u'A general error has occurred. See ExtendedInfo for more information', u'@Message.ExtendedInfo': [{u'Severity': u'Critical', u'RelatedProperties': [], u'MessageId': u'IDRAC.1.6.SYS403', u'MessageArgs@odata.count': 1, u'RelatedProperties@odata.count': 0, u'Message': u'Unable to complete the operation because the resource /redfish/v1/Systems/System.Embedded.1/Storage/RAID.Slot.5-1/Volumes/Disk.Virtual.1:RAID.Slot.5-1/Actions/Volume.Initialize entered in not found.', u'Resolution': u'Enter the correct resource and retry the operation. For information about valid resource, see the Redfish Users Guide available on the support site.', u'MessageArgs': [u'/redfish/v1/Systems/System.Embedded.1/Storage/RAID.Slot.5-1/Volumes/Disk.Virtual.1:RAID.Slot.5-1/Actions/Volume.Initialize']}, {u'Severity': u'Critical', u'RelatedProperties': [u''], u'MessageId': u'Base.1.2.ResourceMissingAtURI', u'MessageArgs@odata.count': 1, u'RelatedProperties@odata.count': 1, u'Message': u'The resource at the URI /redfish/v1/Systems/System.Embedded.1/Storage/RAID.Slot.5-1/Volumes/Disk.Virtual.1:RAID.Slot.5-1/Actions/Volume.Initialize was not found.', u'Resolution': u'Place a valid resource at the URI or correct the URI and resubmit the request.', u'MessageArgs': [u'/redfish/v1/Systems/System.Embedded.1/Storage/RAID.Slot.5-1/Volumes/Disk.Virtual.1:RAID.Slot.5-1/Actions/Volume.Initialize']}]}}

**Comment by texroemer** [comment]
Hi @stranger12345678 

This was an old script bug which has been resolved but newer version was never uploaded to GitHub. I've uploaded new version (version 5), can you try that version and see if issue has been resolved.

Thanks

**Comment by stranger12345678** [comment]
Hi @texroemer 
Tested version 5 as well, it still doesn't work

**Comment by stranger12345678** [comment]
Actually this URI worked: https://172.31.32.26/redfish/v1/Systems/System.Embedded.1/Storage/Volumes/Disk.Virtual.0:RAID.Slot.5-1

And I made this change in InitializeVirtualDiskREDFISH.py, and VD initialize worked :)

diff InitializeVirtualDiskREDFISH.py InitializeVirtualDiskREDFISH.py.modified 
167c167
<     url = 'https://%s/redfish/v1/Systems/System.Embedded.1/Storage/Volumes/%s/Actions/Volume.Initialize' % (idrac_ip, virtual_disk)
---
>     url = 'https://%s/redfish/v1/Systems/System.Embedded.1/Storage/%s/Volumes/%s/Actions/Volume.Initialize' % (idrac_ip, controller, virtual_disk)


python InitializeVirtualDiskREDFISH.py $args -V Disk.Virtual.1:RAID.Slot.5-1 --init Fast

- PASS: POST command passed to Fast initialize "Disk.Virtual.1:RAID.Slot.5-1" virtual disk, status code 202 returned

- PASS, "realtime" JID_333545656301 jid successfully created for initialize virtual disk

- INFO, JobStatus not completed, current status: "Job in progress."
- INFO, JobStatus not completed, current status: "Job in progress."
- INFO, JobStatus not completed, current status: "Job in progress."
- INFO, JobStatus not completed, current status: "Job in progress."
- INFO, JobStatus not completed, current status: "Job in progress."
- INFO, JobStatus not completed, current status: "Job in progress."
- INFO, JobStatus not completed, current status: "Job in progress."
- INFO, JobStatus not completed, current status: "Job in progress."
- INFO, JobStatus not completed, current status: "Job in progress."
- INFO, JobStatus not completed, current status: "Job in progress."
- INFO, JobStatus not completed, current status: "Job in progress."
- INFO, JobStatus not completed, current status: "Job in progress."
- INFO, JobStatus not completed, current status: "Job in progress."
- INFO, JobStatus not completed, current status: "Job in progress."
- INFO, JobStatus not completed, current status: "Job in progress."
- INFO, JobStatus not completed, current status: "Job in progress."
- INFO, JobStatus not completed, current status: "Job in progress."
- INFO, JobStatus not completed, current status: "Job in progress."
- INFO, JobStatus not completed, current status: "Job in progress."
- INFO, JobStatus not completed, current status: "Job in progress."
- INFO, JobStatus not completed, current status: "Job in progress."
- INFO, JobStatus not completed, current status: "Job in progress."
- INFO, JobStatus not completed, current status: "Job in progress."
- INFO, JobStatus not completed, current status: "Job in progress."

--- PASS, Final Detailed Job Status Results ---

JobState: Completed
Description: Job Instance
CompletionTime: 2021-10-04T06:37:26
PercentComplete: 100
StartTime: TIME_NOW
MessageId: PR19
Message: Job completed successfully.
EndTime: TIME_NA
Id: JID_333545656301
JobType: RealTimeNoRebootConfiguration
Name: Config:RAID:RAID.Slot.5-1

**Comment by texroemer** [comment]
Can you let me know which iDRAC version you're using?

**Comment by stranger12345678** [comment]
`{"@odata.context":"/redfish/v1/$metadata#Manager.Manager","@odata.id":"/redfish/v1/Managers/iDRAC.Embedded.1","@odata.type":"#Manager.v1_3_3.Manager","FirmwareVersion":"3.36.36.36"}`

**Comment by texroemer** [comment]
Thanks. 3.36 iDRAC was not DMTF compliant and wasn't using the correct URI structure for init VD. Latest iDRAC 9 version posted on Dell support is 5.00.00 which does use the correct URI structure. If you have to use 3.36 version, you'll need to modify the script as you already did to get it passing.

**Comment by stranger12345678** [comment]
sure, thanks..
