### ISSUE TITLE
Support for firmware updates in 13G/iDrac 8 servers

### ISSUE THREAD

**Issue by nidmat** [dell/iDRAC-Redfish-Scripting#19]
Is there redfish api support for firmware updates (BIOS/RAID etc) on 13G servers with iDrac 8?

**Comment by texroemer** [comment]
Hi,

Current iDRAC version 2.52 does not support it but 2.60 version will support it which is planned to be posted next week for download on Dell support site.

**Comment by nidmat** [comment]
Thank you. 

Will that version support http boot in UEFI mode too?

**Comment by texroemer** [comment]
HTTP boot in UEFI mode is a 14G only feature and not supported in 13G. This was a new feature added by BIOS in 14G which iDRAC 9 added support.
