### ISSUE TITLE
Boot Config Drives/User Data using Redfish API

### ISSUE THREAD

**Issue by harish0619** [dell/iDRAC-Redfish-Scripting#191]
I'm trying to push dynamic data into the baremetal node ( like hostname, ip address, etc.. ), during boot. 

Is it also possible to inject a configuration drive and user data and have them executed during boot using redfish api? or somehow have this data included when redfish issues a command to boot the baremetal node?

**Comment by texroemer** [comment]
Hi @harish0619 

For deploying a configuration file to a baremetal server, i would leverage iDRAC AutoConfig feature. See whitepaper below which explains this feature. You can push configuration settings using Redfish but there is no way to tell the server to automatically do this when the server first boots. But you can do this using AutoConfig feature. 

https://downloads.dell.com/manuals/all-products/esuprt_solutions_int/esuprt_solutions_int_solutions_resources/enterprise-solution-resources_white-papers1_en-us.pdf

Thanks
Tex
