### ISSUE TITLE
PowerShell - Invoke-ChangeIdracUserPassword - Script doesn't complete

### ISSUE THREAD

**Issue by Godeck99** [dell/iDRAC-Redfish-Scripting#195]
Hello,

I'm using PowerShell 7.2.0 and tried to change the iDRAC's password.

The output will only be "- INFO, executing PATCH command to change iDRAC user password" and terminate immediately.

After checking the function I found on the line 205:
`$result1 = Invoke-WebRequest -UseBasicParsing SkipHeaderValidation -SkipCertificateCheck -Uri $uri -Credential $credential -Method Patch -Body $JsonBody -ContentType 'application/json' -Headers @{"Accept"="application/json"} -ErrorVariable RespErr`

After adding a  "-" on the parameter  `SkipHeaderValidation` it works fine.

Thank you for this very helpful module!

**Comment by texroemer** [comment]
@Godeck99 

Thanks for pointing out this issue. I fixed the cmdlet and uploaded new version to GitHub.

Thanks
Tex
