### ISSUE TITLE
How to subscribe the DELL Server's IDRAC event?

### ISSUE THREAD

**Issue by libo500k** [dell/iDRAC-Redfish-Scripting#2]
Hi, 

I wanna monitor the DELL servers' RAID card's event, like disk error through Redfish API, how to subscribe an RAID card's event? Thanks!

Bo

**Comment by texroemer** [comment]
By default iDRAC is already monitoring storage for any errors related to drives, controllers, backplanes, etc and any type of event will be logged in the iDRAC Lifecycle Logs (example: Drive predictive failure or foreign configuration detected). Using Redfish API (GET on URI redfish/v1/Managers/iDRAC.Embedded.1/Logs/Lclog), you can view the Lifecycle logs for any current storage events that occur. 

Or are you looking for setting up iDRAC alerts for storage events and once an event is detected,  it would send an event to a specific location (example: send email or snmp trap).

**Comment by earankyk** [comment]
I'm looking to setup iDRAC alerts for critical errors. Is there a way to do this programatically without using the web gui? Also, could you give me an example on how to listen to the Redfish Event alerts configured in the Configuration->Systems Settings page of the gui.

**Comment by texroemer** [comment]
@earankyk 

First you would need to enable alerts for iDRAC and then set the event filters for what entries you want to receive using Redfish Event Listener. Easiest way to do this is to use Server Configuration Profile (SCP) feature (script "ExportSystemConfigurationLocalREDFISH.py") . 

Example of running the script:

C:\Python27>ExportSystemConfigurationLocalREDFISH.py -ip 192.168.0.120 -u root -p calvin -t idrac,eventfilters

Perform an export and for Target, you will only need iDRAC and EventFilters values. By only passing in these targets, you will only export these settings. Under iDRAC FQDD node, you will see attribute "IPMILan.1#AlertEnable". This attribute enables iDRAC alerts so set this attribute to "Enabled". Under the EventFilters FQDD node, you will see event filters for multiple devices (HDs, PSU, battery, etc). For the device you want an alert sent to Redfish event listener, set attribute "Alert#RedfishEventing" to "Enabled". Example for battery event which i enabled Redfish:

```
<!-- <Attribute Name="BAT_1_3#DisplayName">Battery Event (Informational)</Attribute>--> 
 <Attribute Name="BAT_1_3#Alert#Email">Enabled</Attribute> 
 <Attribute Name="BAT_1_3#Alert#SNMP">Disabled</Attribute> 
 <Attribute Name="BAT_1_3#Alert#IPMI">Disabled</Attribute> 
 <Attribute Name="BAT_1_3#Alert#SysLog">Disabled</Attribute> 
 <Attribute Name="BAT_1_3#Alert#WSEventing">Disabled</Attribute> 
 <Attribute Name="BAT_1_3#Alert#OSLog">Disabled</Attribute> 
 <Attribute Name="BAT_1_3#Alert#RedfishEventing">Enabled</Attribute>
```

Once you have edited the SCP file with all your changes, import this SCP file to apply the changes. You can use script "ImportSystemConfigurationLocalFilenameREDFISH.py". 

Example of running the script:

C:\Python27>ImportSystemConfigurationLocalFilenameREDFISH.py -ip 192.168.0.120 -u root -p calvin -t all -f 2018-9-7_124423_export.xml

Next step is to set up a Redfish subscription. You can use script "SubmitTestEventREDFISH.py" to set this up. 

Example of running the script. 192.168.0.130 is my client IP which will have Redfish event listener running:

C:\Python27>SubmitTestEventREDFISH.py -ip 192.168.0.120 -u root -p calvin -c y -D https://192.168.0.130 -E Alert

Final step is to setup Redfish listener on the client. You can use this Redfish event listener on GitHub. Link has setup instructions on how to set this up:

https://github.com/DMTF/Redfish-Event-Listener
