### ISSUE TITLE
ExportHWInventory - Internal error while exporting inventory

### ISSUE THREAD

**Issue by grantcurell** [dell/iDRAC-Redfish-Scripting#201]
There seems to be a bug in the redfish interface. Tested against both Samba on CentOS and Windows SMB share. Running in the UI works without issue and running against older versions of iDRAC work without issue (tested against iDRAC 4.10.10.10 (32)). However both versions fail against Samba v4.13 with the internal error. To make sure that the issue is not with the share I manually mounted the samba share from Windows. This succeeded.

idrac version 5.00.10.20
BIOS: 2.10.2
License: Datacenter
Samba version: 4.13 (OS: CentOS 8.4)
Windows SMB: 

```powershell
PS C:\Users\grant> Get-SmbServerConfiguration | Select EnableSMB2Protocol

EnableSMB2Protocol
------------------
              True
```

![image](https://user-images.githubusercontent.com/35169230/151066013-4cdca772-787c-4c37-bf1a-6be9cb3f1339.png)

**Comment by texroemer** [comment]
Issue reproduced and bug has been submitted internally to iDRAC team for tracking the fix, closing this issue.
