### ISSUE TITLE
How to resolve remoteimage command with Redfish Api

### ISSUE THREAD

**Issue by kgrvamsi** [dell/iDRAC-Redfish-Scripting#22]
How to use the following commands over Redfish API?

```
remoteimage -d
remoteimage -s
remoteimage -c -u 'root' -p 'cavin' -l 10.0.0.6:/home/ubuntu/export/isos/out.iso
```

**Comment by texroemer** [comment]
@kgrvamsi 

This iDRAC feature is currently not supported using Redfish but will be supported in next iDRAC9 3.30 release which is scheduled to be posted early next year.

Thanks

**Comment by kgrvamsi** [comment]
@texroemer Thanks for the info

**Comment by sknewcomb** [comment]
Any hard date set for when this will be released? I would love to have this functionality.

**Comment by texroemer** [comment]
Hi @sknewcomb, 

3.30 iDRAC9 is scheduled to be released this March.

Thanks
