### ISSUE TITLE
Question: Credentials

### ISSUE THREAD

**Issue by blazarmilkywayflybee** [dell/iDRAC-Redfish-Scripting#221]
Hi @texroemer,

I was just wondering if there was a particular use case as to why all input credentials are strings instead of PSCredential objects?

**Comment by texroemer** [comment]
Hi @blazarmilkywayflybee 
 
For all cmdlets, if you don't pass in arguments for iDRAC username and password, it will prompt you to pass this information which leverages Get-Credential. 

Example:

![image](https://user-images.githubusercontent.com/30351677/183943375-d5ddb4bf-511e-41ad-a5aa-f73a59309af5.png)

Thanks
Tex

**Comment by blazarmilkywayflybee** [comment]
I probably should have provided a little bit more context. I'm hoping to run this non-interactively against 50 odd servers, with differing credentials.

The issue is, even if I was to create the same logic in my wrapper function it would still require moving it back into plaintext to pass it into `Invoke-CreateXauthTokenSessionREDFISH`. 

Ideally it would be nice to leverage PSCredential objects that can then be passed around. I'll create a pull for this module and show you what I'm thinking.

**Comment by texroemer** [comment]
Yes please send either pseudo code workflow or submit pull request for the solution you're looking for.

Would creating X-auth token variable work for your solution?

```
PS C:\> $R640_iDRAC_token = Invoke-CreateXauthTokenSessionREDFISH -idrac_ip 192.168.0.120 -create_x_auth_token_session y

cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters:
Credential

- PASS, new iDRAC token session successfully created

PS C:\> Invoke-CreateVirtualDiskREDFISH -idrac_ip 192.168.0.120 -x_auth_token $R640_iDRAC_token."X-Auth-Token" -get_storage_controllers y

- PASS, statuscode 200 returned successfully to get storage controller(s)

- Server controllers detected -

RAID.SL.3-1
AHCI.Embedded.2-1
AHCI.SL.6-1
AHCI.Embedded.1-1
```

**Comment by blazarmilkywayflybee** [comment]
That would be an option. I did want to avoid the plaintext, but it's kinda unavoidable.

Rather than reworking your code base I think the best option will be to just wrap this in a function and convert to plaintext.
eg. [Working with string passwords](https://docs.microsoft.com/en-us/powershell/scripting/learn/deep-dives/add-credentials-to-powershell-functions?view=powershell-7.2#working-with-string-passwords)

```
function Example-Function {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $true)]
        [string[]]$iDRAC_IP,
        [ValidateNotNull()]
        [System.Management.Automation.PSCredential]
        [System.Management.Automation.Credential()]
        $Credential = [System.Management.Automation.PSCredential]::Empty
    )

    $username = $Credential.UserName
    $password = $Credential.GetNetworkCredential().Password

    foreach ($ip in $iDRAC_IP) {
        $session = Invoke-CreateXauthTokenSessionREDFISH -idrac_ip $ip -$idrac_username $username -$idrac_password $password -create_x_auth_token_session y

        # Using X-Auth-Token do required work

        # Disconnect session
        Invoke-CreateXauthTokenSessionREDFISH -idrac_ip $ip -x_auth_token $($session.'X-Auth-Token') -delete_idrac_session $($session.'Location')
    }
}
```
