### ISSUE TITLE
createvirtualdisk.py is failing with KeyError on 'JobType' with Dell R750 servers  

### ISSUE THREAD

**Issue by dbf1234** [dell/iDRAC-Redfish-Scripting#224]
We were using a Dell R840 (idrac firmware 4.40.40) to test the createvirtualdisk.py script found out on  
https://github.com/dell/iDRAC-Redfish-Scripting/blob/master/      Has worked great in all our testing.   

Received in some Dell R750’s for another project (iDrac firmware 5.10.30) and keeps failing at random times with same error.  See below. createvirtualdisk.py will start creating virtual disks we pass in script... and then we get KeyError on ‘JobType’
It’s pretty random.  I’ve seen it fail all over the place.  Sometimes it fails right out of the box on the first drive.  On Saturday we had a server that ran all the way through with no errors at all, i.e. created all the VD’s.  

Downloaded latest version and seeing the same issue. These are Hadoop servers with 14 disks     1x  raid1 and 12 x raid 0       Not sure if api call is not returning dict value consistently?    

for loop running
os.system('python3 createvirtdisk.py -ip x.x.x.x -u root -p calvin --create ' + array['controller'] + ' --raid-level ' + str(vd['level']) + ' --disks ' + vd['disks'] )

Output snippet. Successfully created 5 Virtual disks and then crashed on the 6th disk.   

- PASS: POST command passed to create "RAID0" virtual disk, status code 202 returned
- PASS, realtime jid "JID_618081473830" successfully created. Server will apply the configuration changes in real time, no server reboot needed
- INFO, job status not completed, current status: "Job in progress."
- INFO, job status not completed, current status: "Job in progress."
- INFO, job status not completed, current status: "Job in progress."
- INFO, job status not completed, current status: "Job in progress."
- INFO, job status not completed, current status: "Job in progress."
- INFO, job status not completed, current status: "Job in progress."
- INFO, job status not completed, current status: "Job in progress."
- INFO, job status not completed, current status: "Job in progress."
- INFO, job status not completed, current status: "Job in progress."
- INFO, job status not completed, current status: "Job in progress."
--- PASS, Final Detailed Job Status Results ---

('@odata.context', '/redfish/v1/$metadata#DellJob.DellJob')
('@odata.id',
'/redfish/v1/Managers/iDRAC.Embedded.1/Oem/Dell/Jobs/JID_618081473830')
('@odata.type', '#DellJob.v1_2_0.DellJob')
('ActualRunningStartTime', '2022-08-29T16:22:28')
('ActualRunningStopTime', '2022-08-29T16:24:07')
('CompletionTime', '2022-08-29T16:24:07')
('Description', 'Job Instance')
('EndTime', 'TIME_NA')
('Id', 'JID_618081473830')
('JobState', 'Completed')
('JobType', 'RealTimeNoRebootConfiguration')
('Message', 'Job completed successfully.')
('MessageArgs', [])
('MessageArgs@odata.count', 0)
('MessageId', 'PR19')
('Name', 'Configure: RAID.Slot.3-1')
('PercentComplete', 100)
('StartTime', '2022-08-29T16:22:27')
('TargetSettingsURI', None)

- PASS: POST command passed to create "RAID0" virtual disk, status code 202 returned
Traceback (most recent call last):
  File "createvirtdisk.py", line 502, in <module>
    create_raid_vd()
  File "createvirtdisk.py", line 302, in create_raid_vd
    if data['JobType'] == "RAIDConfiguration":
KeyError: 'JobType'

- FAIL, POST command failed, status code is 400

**Comment by texroemer** [comment]
Hi @dbf1234 

I was able to reproduce the issue you hit with iDRAC 5.10.30. Looks to be an intermittent timing issue in the iDRAC firmware, not a script issue which i'll need to escalate this issue to the iDRAC team internally. 

I went ahead and updated the script to have a 10 second sleep delay after POST command passes before checking the job type in the JSON response. I also added retry logic if the JSON output does not return JobType. I looped the updated script overnight and wasn't able to hit the issue anymore. 

Can you go ahead and test with latest updated script. If you still see failures please let me know. 

Thanks
Tex

**Comment by dbf1234** [comment]
Thank you Tex.

Will download latest updated script and test.  Will let you know.

Thanks! Doug

**Comment by gint914** [comment]
The first test with the new script to create 6 VDs worked great.  I need to delete 13 disks on some other servers to give it a full test.  But looks great so far!  Thank you.

**Comment by gint914** [comment]
I see the DeleteVirtualDiskREDFISH.py script has this new retry logic added.  I'm going to have to try that because the previous version had the same issue.
[DeleteVirtualDiskREDFISH.py](https://github.com/dell/iDRAC-Redfish-Scripting/blob/master/Redfish%20Python/DeleteVirtualDiskREDFISH.py)

**Comment by texroemer** [comment]
Yes i also made same changes to DeleteVirtualDiskREDFISH.py and InitializeVirtualDiskREDFISH.py scripts since they both leverage the same logic as create VD script.

Let me know how your testing goes with delete VD script.

Thanks
Tex

**Comment by gint914** [comment]
Thank you VERY much.   Both create and delete scripts work great.  

I tested the create script on 5 servers at the same time and got consistent results, run once and done.

The delete script outputs the VD name that it's deleting.  It would be great if the create script did something similar.  It doesn't affect automation usage, but when running to test and develop this would be a great feature.

- PASS: DELETE command passed to delete "Disk.Virtual.6:RAID.Slot.3-1" virtual disk, status code 202 returned

**Comment by dbf1234** [comment]
Same result as gint914.    13 virtual disks created without issue on the test I ran last night.         thanks!

**Comment by texroemer** [comment]
Hi @gint914 

Implemented your suggestion and uploaded new script to report new VD FQDD created. See example below (new log message in bold):

C:\Python39>CreateVirtualDiskREDFISH.py -ip 192.168.0.120 -u root -p calvin --get-virtualdisks RAID.SL.3-1

- Volume(s) detected for RAID.SL.3-1 controller -

Disk.Virtual.0:RAID.SL.3-1, Volume type: NonRedundant
Disk.Virtual.2:RAID.SL.3-1, Volume type: NonRedundant

C:\Python39>CreateVirtualDiskREDFISH.py -ip 192.168.0.120 -u root -p calvin --create RAID.SL.3-1 --disks Disk.Bay.2:Enclosure.Internal.0-1:RAID.SL.3-1 --raid-level 0

- PASS: POST command passed to create "RAID0" virtual disk, status code 202 returned
- PASS, realtime job ID "JID_620519710365" successfully created. Server will apply the configuration changes in real time, no server reboot needed
- INFO, job not completed, current status: "Job in progress"
- INFO, job not completed, current status: "Job in progress"
- INFO, job not completed, current status: "Job in progress"
- INFO, job not completed, current status: "Job in progress"
- INFO, job not completed, current status: "Job in progress"
- INFO, job not completed, current status: "Job in progress"
- INFO, job not completed, current status: "Job in progress"

--- PASS, Final Detailed Job Status Results ---

('@odata.context', '/redfish/v1/$metadata#DellJob.DellJob')
('@odata.id',
 '/redfish/v1/Managers/iDRAC.Embedded.1/Oem/Dell/Jobs/JID_620519710365')
('@odata.type', '#DellJob.v1_2_0.DellJob')
('ActualRunningStartTime', '2022-09-01T12:06:12')
('ActualRunningStopTime', '2022-09-01T12:07:32')
('CompletionTime', '2022-09-01T12:07:32')
('Description', 'Job Instance')
('EndTime', 'TIME_NA')
('Id', 'JID_620519710365')
('JobState', 'Completed')
('JobType', 'RealTimeNoRebootConfiguration')
('Message', 'Job completed successfully.')
('MessageArgs', [])
('MessageArgs@odata.count', 0)
('MessageId', 'PR19')
('Name', 'Configure: RAID.SL.3-1')
('PercentComplete', 100)
('StartTime', '2022-09-01T12:06:11')
('TargetSettingsURI', None)

**- INFO, new VD FQDD created: Disk.Virtual.1:RAID.SL.3-1**

C:\Python39>CreateVirtualDiskREDFISH.py -ip 192.168.0.120 -u root -p calvin --get-virtualdisks RAID.SL.3-1

- Volume(s) detected for RAID.SL.3-1 controller -

Disk.Virtual.0:RAID.SL.3-1, Volume type: NonRedundant
Disk.Virtual.2:RAID.SL.3-1, Volume type: NonRedundant
Disk.Virtual.1:RAID.SL.3-1, Volume type: NonRedundant

**Comment by gint914** [comment]
I'll try that out.  I wanted to do another test run anyway.  Thank you very much sir!
