### ISSUE TITLE
Redfish API for switch connection information

### ISSUE THREAD

**Issue by vnikolin** [dell/iDRAC-Redfish-Scripting#226]
I'm working with Dell R650/740/750 and iDRAC 5.x. I'm looking for Redfish API that would provide network connection switch information ie. mac/switch name/port name etc. Similar information can be fetched with "racadm switchconnection view" or viewed from iDRAC UI "Switch Connection ID" and "Switch Port Connection ID". I see some reference in Redfish documentation it but I'm unable to find API in actual system. Any suggestions pls lmk.

Thanks!
V

URL
/redfish/v1/Dell/Systems/<ComputerSystem-Id>/NetworkPorts/DellSwitchConnection/<SwitchConnectionID>

**Comment by texroemer** [comment]
Hi @vnikolin 

GET on URI "redfish/v1/Managers/iDRAC.Embedded.1", under Oem you should see URI "/redfish/v1/Systems/System.Embedded.1/NetworkPorts/Oem/Dell/DellSwitchConnections". Run GET on this URI to get the switch details you're looking for, same output as RACADM and GUI. 

![image](https://user-images.githubusercontent.com/30351677/190235097-78f4405c-b2f2-416f-89d2-2d0174146110.png)

Let me know if you don't see this URI under Oem.

Thanks
Tex

**Comment by vnikolin** [comment]
Thanks for the follow up Tex! Found it.

Just a quick follow up... is there any other API to provide any other switch information ie. switch name etc?

![image](https://user-images.githubusercontent.com/94382787/190241785-a5957eb4-9df6-42cb-84bf-ec52beaf3275.png)

**Comment by texroemer** [comment]
Currently not supported by iDRAC to get switch details like model, manufacturer, firmware version, etc using any iDRAC interface. DMTF does support Switch resource but iDRAC currently doesn't support. I'll escalate this request to Dell internal teams to see if this support can be added in a future iDRAC release.

Thanks
Tex

**Comment by vnikolin** [comment]
Thanks again for the quick follow up Tex!

Regards,
V

**Comment by texroemer** [comment]
No problem, glad to help!

-Tex
