### ISSUE TITLE
Typo in Invoke-CreateVirtualDiskREDFISH.ps1

### ISSUE THREAD

**Issue by delfim-dacosta** [dell/iDRAC-Redfish-Scripting#228]
In description stripesize is in kilobytes in the powershell script as it's in bytes in python script and it must be in bytes.

**Comment by texroemer** [comment]
Hi @delfim-dacosta 

Thanks for the catch, i corrected the help text string, bytes is the correct value type for stripesize argument. 

Thanks
Tex
