### ISSUE TITLE
Redfish logs to fetch Boot Process 

### ISSUE THREAD

**Issue by kgrvamsi** [dell/iDRAC-Redfish-Scripting#23]
Is there any api to fetch the boot process log from the Os running on the baremetal?

**Comment by texroemer** [comment]
Hi @kgrvamsi 

We currently don't support getting OS boot process logs using iDRAC but we are working on expanding iDRAC support for future releases to gather even more OS information than what we currently support today. I'll escalate your request to add support for getting OS boot process logs.

Thanks
