### ISSUE TITLE
Can't open grafana web site

### ISSUE THREAD

**Issue by huazhou007** [dell/iDRAC-Redfish-Scripting#234]
all thing look is ok,Redfish Telemetry Service Configuration web site XXX.XXX.XXX.XXX:8080 is ok and then add idrac ip infomation,influxdb web site also can open xxx.xxx.xxx.xxx:8086,but when open granfana website https://xxx.xxx.xxx.xxx:3000 can't open,and then use docker ps -a find like this  grafana docker exited!  how to fixed it?
![image](https://user-images.githubusercontent.com/52940678/210291127-f28a53c3-6918-469f-8ce2-28810d2e2da9.png)

**Comment by huazhou007** [comment]
try  restart grafana docker find it also exited

**Comment by texroemer** [comment]
Hi @huazhou007 

I don't have expertise in Grafana but i asked for input from iDRAC Telemetry team internally at Dell . Here is their response:

_Need more details on how Grafana is being accessed and how Grafana docker container is started?
 If so, access Grafana UI (http://localhost:3000/) using default credentials: admin/admin)

This is the WP mainly focusses on using Telemetry Reference tools for data visualization using Grafana etc.  Not Grafana in general.

https://dl.dell.com/content/manual3687441-idrac9-telemetry-reference-tools-data-visualization.pdf?language=en-us_

Thanks
Tex

**Comment by sankunny** [comment]
Chcek the dockers logs for the Grafana container.

**Comment by texroemer** [comment]
Closing as completed, if you still run into issues please post them on the iDRAC Telemetry page.

https://github.com/dell/iDRAC-Telemetry-Scripting

Thanks
Tex
