### ISSUE TITLE
Possible mismatch values for StripeSize

### ISSUE THREAD

**Issue by ddcdk** [dell/iDRAC-Redfish-Scripting#235]
Hi,

When creating a Virtual disk The parameter "**OptimumIOSizeBytes**" must be IO size byte, this means that for 128 KB i use 131072 bytes. This is verified when getting the properties of this virtual disk that show :  "StripeSize": "128KB" and "OptimumIOSizeBytes": 131072.
When Getting this Raid configuration from Raid Profile with (_/redfish/v1/Managers/iDRAC.Embedded.1/Actions/Oem/EID_674_Manager.ExportSystemConfiguration"_) value for StripedSize is **256** and not **128**.
When I Set the Raid configuration by importing the previous generated configuration the StripSize which has a value of 256 in the profile file has the right value of 128KB as well as OptimumIOSizeBytes.

It seems that value for StripSize in import/esport raid profile mechanisms is wrong and that this value is the double of the good value : 256 is 128KB, 128 is 64KB...

Best Regards,
Delfim Da Costa

**Comment by texroemer** [comment]
Hi @ddcdk 

For virtual disk stripesize property, you will see different behavior between OEM Server Configuration Profile (SCP) feature and DMTF. DMTF will report the actual stripesize value in KB but for SCP a converted integer value will get reported. Please refer to the iDRAC attribute registry for conversion value details. 

https://dl.dell.com/content/manual11886670-integrated-dell-remote-access-controller-9-attribute-registry.pdf?language=en-us&ps=true

![image](https://user-images.githubusercontent.com/30351677/210616698-dbfee143-dcb3-42b5-8128-41223948761d.png)

Thanks
Tex
