### ISSUE TITLE
Can we use redfish api to execute a command/get output remotely on the idrac console.	iDRAC Firmware Version	5.10.30.00

### ISSUE THREAD

**Issue by sivakumarv47** [dell/iDRAC-Redfish-Scripting#238]
I did not find any api call in the documentation https://developer.dell.com/apis/2978/versions/5.xx/docs/0WhatsNew.md

**Comment by texroemer** [comment]
Hi @sivakumarv47 

Can i get more details about your ask? What do you mean by iDRAC console? Are you asking if you can make a Redfish GET request from a client system to the iDRAC? 

Thanks
Tex

**Comment by sivakumarv47** [comment]
Hi Tex, I am asking can we use redfish api to execute a command or get output on the virtual console of the server.

Thanks
Siva

**Comment by texroemer** [comment]
Ok, so from the virtual console or local operating system, this is no local Redfish support like local RACADM where with local RACADM you don't need to pass in iDRAC IP and creds to run local RACADM commands. If running Redfish commands from within the OS, you can leverage either iDRAC IP or iDRAC USB-NIC IP.

See example below where i use iDRAC USB-NIC IP to run Redfish GET request.

![image](https://user-images.githubusercontent.com/30351677/215566781-5dbce60d-157a-4c4a-9c0f-90a007e02aa0.png)

![image](https://user-images.githubusercontent.com/30351677/215566856-33b0f5aa-eaa1-495a-baa2-3d9e38aef8b5.png)

Thanks
Tex

**Comment by sivakumarv47** [comment]
Thanks Tex for the answer. But i think there is a confusion in my question

I am  asking is there any way from redfish api or any other automated way to execute command on the virtual console.

For E.g. ls -ltr command on virtual console and get the output
Attaching the screenshot.

Thanks
Siva



<img width="1723" alt="Screenshot 2023-01-31 at 9 33 45 PM" src="https://user-images.githubusercontent.com/10721154/215817211-a956c1d2-f16b-498a-a1a3-086e6b820744.png">

<img width="1492" alt="Screenshot 2023-01-31 at 9 41 50 PM" src="https://user-images.githubusercontent.com/10721154/215817358-887494a6-a35d-4ad6-a490-25266378526c.png">

**Comment by sshnaidm** [comment]
@texroemer wouldn't be SOL (serial-over-lan) useful here? Or it's only for output?

**Comment by texroemer** [comment]
Yes you can use SOL to run OS linux commands but you must first configure grub in the OS, configure iDRAC and BIOS settings. 

1. Add these 3 lines to /etc/default/grub file (I used RHEL 8.5 OS):

GRUB_CMDLINE_LINUX_DEFAULT="console=tty0 console=ttyS0,115200n8"
GRUB_TERMINAL=serial
GRUB_SERIAL_COMMAND="serial --speed=115200 --unit=0 --word=8 --parity=no --stop=1"

2. Then run "grub2-mkconfig -o /etc/grub2-efi.cfg" to compile the changes.

3. Make iDRAC changes for IPMI and SOL:

- Enable IPMI 
- Enable SOL
- Baud Rate 115200
- Redirect enabled

4. Make BIOS changes under Serial Communication:

- On with Console Redirection 
- Serial Port Address set to Com1
- Failsafe Baud rate 115200

From your client system, you can use the following two methods to start the SOL session to the OS:

1. SSH to the iDRAC, then at the RACADM prompt type "connect com2"
2. Run "ipmitool.exe -U <iDRAC username> -P <iDRAC password> -H <iDRAC IP> -I lanplus sol activate"
