### ISSUE TITLE
How to get fru info

### ISSUE THREAD

**Issue by scut33** [dell/iDRAC-Redfish-Scripting#25]
how to get fru infos through redfish api?  or any node related to fru info? such as power?

**Comment by texroemer** [comment]
Hi @scut33 

Running GET on URI "redfish/v1/Systems/System.Embedded.1" will give overall system information along with URIs for each device which you can execute a GET on for detailed information. URIs returned for fans, power supplies, memory, processors, network, storage (Example GET URI for PSU: "/redfish/v1/Chassis/System.Embedded.1/Power/PowerSupplies/PSU.Slot.1").

**Comment by texroemer** [comment]
No problem, glad to help out!
