### ISSUE TITLE
Redfish not matching iDRAC webui and racadm status for health and network info requires iDRAC reset

### ISSUE THREAD

**Issue by vnikolin** [dell/iDRAC-Redfish-Scripting#251]
Hi Tex,

I'm working with Dell R650/R750 iDRAC firmware 5.10.10.05/6.10.00.00. Please note that I've also seen similar issues with GET requests on other models and iDRAC versions.

I've been seeing intermittent discrepancy where Redfish GET details are not matching iDRAC webui and racadm status for health and network info. I'm seeing this for Broadcom/Mellanox nics on R750/650 servers and various health APIs. I've included a few sample APIs below.

Sample APIs for GET request are:
/redfish/v1/Chassis/System.Embedded.1/NetworkAdapters/NIC.Slot.6/NetworkPorts/NIC.Slot.6-1 (seeing LinkStatus is "" vs "Up" or "Down")
/redfish/v1/Chassis/System.Embedded.1/NetworkAdapters/NIC.Slot.6/NetworkPorts/NIC.Slot.6-2 (seeing LinkStatus is "" vs expected "Up" or "Down")

/redfish/v1/Systems/System.Embedded.1/Processors/CPU.Socket.1 (seeing Health/State is ""/"" vs "OK"/"Enabled")
/redfish/v1/Systems/System.Embedded.1/Processors/CPU.Socket.2 (seeing Health/State is ""/"" vs "OK"/"Enabled")

I typically do an iDRAC reset then wait ~ 5-7 minutes and retry.

For monitoring and health check usage of Redfish APIs I'm trying to figure out what is best practice for getting clean GET results? Perhaps bouncing OS and/or iDRAC itself or maybe incorporate virtual flea drain etc. I'm basically trying to get a fool proof way for getting consistent GET results for a given test.

Any insight from your side is greatly appreciated.

Thanks!
V

**Comment by texroemer** [comment]
Hi @vnikolin 

Thanks for bringing up this concern and i've also repro this issue in my lab with Broadcom NIC. I tried same workflow on another server with Intel NIC and don't see the issue. Currently i'm working with iDRAC internal teams on this issue and will update you once i have any new information. 

When you hit this issue for reporting empty string or null for LinkStatus property, does it eventually report Up or Down value or it never does and you have to reset the iDRAC to report a valid value? When i hit the issue, i would keep running GET command in a loop and after a couple of minutes it finally reported a valid value of Up or Down. 

Thanks
Tex
