### ISSUE TITLE
minor issue

### ISSUE THREAD

**Issue by abjoint** [dell/iDRAC-Redfish-Scripting#253]
https://github.com/dell/iDRAC-Redfish-Scripting/blob/af90e320ea8da5b1de721770d0c1761bbfe5bdea/Redfish%20Python/DeviceFirmwareSimpleUpdateREDFISH.py#L155

**Comment by texroemer** [comment]
Hi @abjoint, thanks for the catch, issue has been fixed. 

Thanks
Tex
