### ISSUE TITLE
SyntaxError: invalid syntax on line 157

### ISSUE THREAD

**Issue by OmarReygaert** [dell/iDRAC-Redfish-Scripting#259]
https://github.com/dell/iDRAC-Redfish-Scripting/blob/63e0a0886411e84fccd6b67e3cfc05de16251369/Redfish%20Python/CreateVirtualDiskREDFISH.py#L157

it seems that python gives an error for this line:

`iDRAC-Redfish-Scripting/Redfish Python/CreateVirtualDiskREDFISH.py", line 157
    print(data), print("\n")
                     ^
SyntaxError: invalid syntax`

**Comment by OmarReygaert** [comment]
This can be fixed by putting the second print on a new line

**Comment by texroemer** [comment]
Hi @OmarReygaert 

I don't see this issue when i run the script (Python 3.10) but looks to be an issue with certain version of Python not liking this format. I went ahead and moved the print new line to the next line.

Thanks
Tex

**Comment by OmarReygaert** [comment]
Thanks @texroemer  for the fast resolving.
I'm running python3.6
It's working perfectly now.
