### ISSUE TITLE
PowerShell Help does not work

### ISSUE THREAD

**Issue by laplantj** [dell/iDRAC-Redfish-Scripting#26]
After the modules have been placed in a module folder I found that the help was not working as it should in Powershell. When I run get-help Set-IdracUserPasswordREDFISH for example I do not get the synopsis, and description that was defined. The same issue exists for the examples when the -example switch is used with the command. 

To  resolve this issue i had to relocate the author, version, and copyright info. Once the modules were updated the help and example details in Powershell displayed as expected.

**Comment by texroemer** [comment]
Hi @laplantj,

Can you tell me which version of Powershell you are using? I'm on 5.1 and don't see this issue. I know if an extra line is added between the comment blocks and the function, i've seen the issue where Get-Help doesn't work correctly.

Thanks
