### ISSUE TITLE
InsertEjectVirtualMediaREDFISH.py  always gives "remote file location is not accessible"

### ISSUE THREAD

**Issue by eedelk** [dell/iDRAC-Redfish-Scripting#265]
Hi,
for a Dell  server with iDRAC version 6.10.30.00
I am running command:
InsertEjectVirtualMediaREDFISH.py -ip IP -u root -p PWD --action insert --device cd --uripath http://WEBSERVER_IP/xxx.iso

The command always fails with error:

- FAIL, POST command InsertMedia action failed, detailed error message: b'{"error":{"@Message.ExtendedInfo":[{"Message":"The remote file location is not accessible or reachable.","MessageArgs":[],"MessageArgs@odata.count":0,"MessageId":"IDRAC.2.8.RAC0904","RelatedProperties":[],"RelatedProperties@odata.count":0,"Resolution":"Confirm that the path and credentials to remote file are correct, and check that the iDRAC can connect to the network address.","Severity":"Warning"}],"code":"Base.1.12.GeneralError","message":"A general error has occurred. See ExtendedInfo for more information"}}'

The uripath however is correct and working for sure.
I can run: 
wget <uripath>

I also tried with uripath: https://releases.ubuntu.com/jammy/ubuntu-22.04.3-desktop-amd64.iso
and get the same error.

Anyone has an idea what could be the root cause?
//Thank you

**Comment by texroemer** [comment]
Hi @eedelk 

Starting in iDRAC version 6.00.02 insert / eject virtual media now uses Systems schema where you pass in the index ID for the virtual media device. See below example where i was able to attach the ISO using the index ID.

```
C:\Python310>racadm -r 192.168.0.120 -u root -p calvin --nocertwarn getversion
 Bios Version                     = 1.11.2

 iDRAC Version                    = 6.10.30.00

 Lifecycle Controller Version     = 6.10.30.00

 IDSDM Version                    = NA



C:\Python310>python InsertEjectVirtualMediaREDFISH.py -ip 192.168.0.120 -u root -p calvin --action insert --index 1 --uripath https://releases.ubuntu.com/jammy/ubuntu-22.04.3-desktop-amd64.iso

- PASS, POST command passed to successfully insert virtual media, status code 204 returned
```

Let me know if you're still seeing issues when using the index ID to attach virtual media.

Thanks
Tex

**Comment by eedelk** [comment]
Hi Tex,
thanks for your hint.
But I still have the problem:

# racadm -r <ip> -u root -p '*****' --nocertwarn getversion
 Bios Version                     = 2.17.1                                   

 iDRAC Version                    = 6.10.30.00

 Lifecycle Controller Version     = 6.10.30.00

 IDSDM Version                    = NA

I added printout of version and payload also:

# python /usr/local/bin/InsertEjectVirtualMediaREDFISH.py -ip <ip> -u root -p '*****' --action insert --index 1 --uripath https://releases.ubuntu.com/jammy/ubuntu-22.04.3-desktop-amd64.iso
iDRAC_version: new
payload: {'Image': 'https://releases.ubuntu.com/jammy/ubuntu-22.04.3-desktop-amd64.iso', 'Inserted': True, 'WriteProtected': True}

- FAIL, POST command InsertMedia action failed, detailed error message: b'{"error":{"@Message.ExtendedInfo":[{"Message":"Unable to locate the ISO or IMG image file in the network share location because the file path or the user credentials entered may be incorrect.","MessageArgs":["https://releases.ubuntu.com/jammy/ubuntu-22.04.3-desktop-amd64.iso"],"MessageArgs@odata.count":1,"MessageId":"IDRAC.2.8.RAC0720","RelatedProperties":["#/Image"],"RelatedProperties@odata.count":1,"Resolution":"Ensure that you provide the correct file path and credentials, and then retry the operation.","Severity":"Informational"}],"code":"Base.1.12.GeneralError","message":"A general error has occurred. See ExtendedInfo for more information"}}'


Credentials are correct for sure.
Inserting virtual media manually via the GUI  and then running
"InsertEjectVirtualMediaREDFISH.py"
is working.

I also tried other locally availably ISOs but always get above error :-(

Thank you
eedelk

**Comment by texroemer** [comment]
Since you have RACADM installed can you try using remoteimage command to mount the ISO, see if that also fails or passes. If it fails then we'll know its not an interface issue.

Example of using RACADM command:

```
[root@SCPexport opt]# racadm -r 192.168.0.120 -u root -p calvin remoteimage -s
Security Alert: Certificate is invalid - self signed certificate
Continuing execution. Use -S option for racadm to stop execution on certificate-related errors.
Remote File Share is Disabled
UserName
Password
ShareName

[root@SCPexport opt]# racadm -r 192.168.0.120 -u root -p calvin remoteimage -l https://releases.ubuntu.com/jammy/ubuntu-22.04.3-desktop-amd64.iso -c
Security Alert: Certificate is invalid - self signed certificate
Continuing execution. Use -S option for racadm to stop execution on certificate-related errors.
Remote Image is now Configured

[root@SCPexport opt]# racadm -r 192.168.0.120 -u root -p calvin remoteimage -s
Security Alert: Certificate is invalid - self signed certificate
Continuing execution. Use -S option for racadm to stop execution on certificate-related errors.
Remote File Share is Enabled
UserName
Password
ShareName https://releases.ubuntu.com/jammy/ubuntu-22.04.3-desktop-amd64.iso
```

Thanks
Tex

**Comment by eedelk** [comment]
Hi Tex,

I tried racadm also and it failed:

```
racadm -r IP -u root -p PWD remoteimage -l https://releases.ubuntu.com/jammy/ubuntu-22.04.3-desktop-amd64.iso -c
Security Alert: Certificate is invalid - self signed certificate
Continuing execution. Use -S option for racadm to stop execution on certificate-related errors.
ERROR: RAC0720: Unable to locate the ISO or IMG image file in the network share        
             location because the file path or the user credentials entered may be        
             incorrect. Ensure that you provide the correct file path and credentials,        
             and then retry the operation.
```

Thank you
eedelk
Probably it is something related to my environment :-(
I tried with a local iso and then it seems it is doing something (at least it took a while until the error popped up)
But finally failed also:

```
racadm -r IP -u root -p PWD remoteimage -l MY_ISO -c
Security Alert: Certificate is invalid - self signed certificate
Continuing execution. Use -S option for racadm to stop execution on certificate-related errors.
ERROR: Unable to perform requested operation.  
```
