### ISSUE TITLE
Virtual Console example?

### ISSUE THREAD

**Issue by brook-w** [dell/iDRAC-Redfish-Scripting#267]

**Comment by texroemer** [comment]
Hi @brook-w 

Can you give me some details about the example you're looking for? Are you looking for an example where you can launch an iDRAC virtual console session using Redfish?

Thanks
Tex

**Comment by brook-w** [comment]
@texroemer  yes
I hope to start Virtual Console through Redfish. I tried the official VNC service, but it always has some problems. It is very unstable when I do n’t know how to happen. For example It is only necessary to restart the VNC Server repeatedly, so I want to find a Redfish solution that can start Virtual Console through HTTP, because Virtual Console is always stable. If you can start Virtual Console through Redfish, it will be great.

**Comment by brook-w** [comment]
If the Virtual Console can be activated through Redfish, there is a way to optimize VNC, which bother me. VNC is sometimes good at work, but sometimes it is not good enough. , My current environment is IDRAC7/8 without IDRAC9

**Comment by texroemer** [comment]
Launching virtual console session is supported using Redfish but only on iDRAC 9. iDRAC 8 currently does not support this feature with Redfish. 

If you have servers with iDRAC 9 please leverage script below:

https://github.com/dell/iDRAC-Redfish-Scripting/blob/master/Redfish%20Python/LaunchIdracRemoteKvmHtmlSessionREDFISH.py

Thanks
Tex
