### ISSUE TITLE
pxe boot job id no long working

### ISSUE THREAD

**Issue by Gerardwx** [dell/iDRAC-Redfish-Scripting#275]
We have been PXE booting via Python iDRAC for a year or so. 

This week, the job id we are getting back from the iDrac is no longer querable. The job IDs appear in the lifecycle controller log. 

[log.txt](https://github.com/dell/iDRAC-Redfish-Scripting/files/13476487/log.txt)
![lclog](https://github.com/dell/iDRAC-Redfish-Scripting/assets/2816043/c818eb52-b0ab-42aa-a05a-4d03d60d749d)

PowerEdge R740 withiDRAC Firmware Version 	7.00.00.00

**Comment by texroemer** [comment]
Hi @Gerardwx 

There is a known bug in current shipping iDRAC where once the job ID is marked completed, within a couple of seconds it will get auto deleted from "TaskService/Tasks" endpoint. I confirmed with internal teams at Dell this bug has been resolved and the fix will be available in iDRAC 7.10.30 scheduled to be released March 2024. 

As a workaround you can leverage "JobService/Jobs" endpoint where the job ID will still be reported and will not auto delete after getting marked completed.

Thanks
Tex
