### ISSUE TITLE
DELL/iDRAC -Redfish

### ISSUE THREAD

**Issue by yograj099** [dell/iDRAC-Redfish-Scripting#277]
While retrieving the information through Redfish ,Do we need to provide "Headers" ?
If yes , for Dell what is the Key-Value pair I have to provide ? I am using Postman tool for this.
If we do not provide , whether it will read info through DCI ? 
Thanks in advance !

**Comment by yograj099** [comment]
https://10.x.x.x/redfish/v1/Chassis/System.Embedded.1/NetworkAdapters/FC.Slot.2/

How can I make sure that the information which I am getting is through RDE ? Is there any particular parameter ?

**Comment by yograj099** [comment]
For other OEM  (while using Postman) , If I dont apply header value as "RDE" , information is retrieved through DCI. Is it same for DELL ?

**Comment by texroemer** [comment]
Currently iDRAC supports pulling data from devices using PLDM but have future plans to add RDE.

Thanks
Tex

**Comment by yograj099** [comment]
Thank you for the info !!!
