### ISSUE TITLE
Can add an example for querying from iDrac KeyVault by Redfish API? 

### ISSUE THREAD

**Issue by poisson0106** [dell/iDRAC-Redfish-Scripting#282]
Hi
Recently I have a request to store some sensitive data in node level. As I check the iDrac document and find that there is a credential vault function provided by iDrac side.
![4a827ca0-ef7c-44bf-b4a2-8a900d16d474](https://github.com/dell/iDRAC-Redfish-Scripting/assets/3365321/bd18fe9e-01db-46e2-a699-b579239df3d2)
So I wonder to know if the examples about how to get/set credential to this credential vault by redfish can be added? Or where I can find  these examples?

Thanks

**Comment by texroemer** [comment]
Hi @poisson0106 

Credential Vault details stated in iDRAC security document is used internally by iDRAC to store iDRAC settings (passwords, certificate private keys, etc), it is not a general-purpose storage device that can be leveraged by end users. 

Thanks
Tex

**Comment by poisson0106** [comment]
Thanks, I will close this issue.
