### ISSUE TITLE
InsertEjectVirtualMediaREDFISH.py unable to insert ISO file residing on CIFS share; works from iDRAC GUI

### ISSUE THREAD

**Issue by srcauley** [dell/iDRAC-Redfish-Scripting#284]
I can successfully mount this ISO via the iDRAC GUI...

![image](https://github.com/dell/iDRAC-Redfish-Scripting/assets/160793246/dc666e48-33a8-441e-8216-fe88c8bbe21f)

I can see the ISO is mounted using the InsertEjectVirtualMediaREDFISH.py  --get argument...

![image](https://github.com/dell/iDRAC-Redfish-Scripting/assets/160793246/71ff6dbf-7b06-4a0b-bea0-f29cf68ef82b)

I can eject the virtual media...

![image](https://github.com/dell/iDRAC-Redfish-Scripting/assets/160793246/7ab63a59-a744-4586-b61b-93df703f6953)

But the following command fails.  Note I copied and pasted the URI from the working GUI setting. Am I missing something?

![image](https://github.com/dell/iDRAC-Redfish-Scripting/assets/160793246/2b4d68e0-a8d2-4925-97d3-4e3bf81c247b)

Version info...

![image](https://github.com/dell/iDRAC-Redfish-Scripting/assets/160793246/1c03315b-c513-452d-9e68-d09366756d3c)

**Comment by srcauley** [comment]
Not sure if it is because of special characters in my password, but I had to enclose the CIFS username and and password in double quotes to get it to work. Issue resolved.

![image](https://github.com/dell/iDRAC-Redfish-Scripting/assets/160793246/82eb195e-c3a8-4977-acb8-6c866534d640)

**Comment by srcauley** [comment]
Not sure if it is because of special characters in my password, but I had to enclose the CIFS username and and password in double quotes to get it to work. Issue resolved.

![image](https://github.com/dell/iDRAC-Redfish-Scripting/assets/160793246/4645f926-db8c-4b24-933f-0321d8bd087b)

**Comment by texroemer** [comment]
Hi @srcauley 

Thanks for root causing the issue and yes if your network share password has special characters surround the string with quotes. I'll update the argument help text to state this info. 

Thanks
Tex

**Comment by srcauley** [comment]
@texroemer Ugh, sorry I got ahead of myself.  I had started using RACADM to accomplish the ISO virtual media mount and initially had the same issue. I discovered that the quotes resolved the issue with RACADM, not InsertEjectVirtualMediaREDFISH.py I subsequently tried the same with the Python script and it still results in the same error.  I have Re-opened the issue.

**Comment by texroemer** [comment]
Ok can you share the special character(s) you're using in the password string.

**Comment by srcauley** [comment]
> Ok can you share the special character(s) you're using in the password string.

There is a ^ in my password.

**Comment by srcauley** [comment]
I will get with my lab admin and see if there is another account I can use to rule out the special characters being the cause. I will let you know.

**Comment by texroemer** [comment]
Tested CIFS user password with ^ and no issues with attach virtual media. Are you still seeing Redfish action fail?

```
C:\Python310>python InsertEjectVirtualMediaREDFISH.py -ip 192.168.0.120 -u root -p calvin --action insert --index 1 --uripath //192.168.0.130/sambashare/boot.iso --username tester --password "Test123^"

- PASS, POST command passed to successfully insert virtual media, status code 204 returned
```

**Comment by vincent-tang1** [comment]
> python InsertEjectVirtualMediaREDFISH.py -ip 192.168.0.120 -u root -p calvin --action insert --index 1 --uripath //192.168.0.130/sambashare/boot.iso --username tester --password "Test123^"

sorry, may i have a extenstion question, above examples seems like no **Donain Name** required in sabma. If **Donain Name** is needed, what should the **'--uripath'** value in redfish script is like ? Thanks

**Comment by srcauley** [comment]
> Tested CIFS user password with ^ and no issues with attach virtual media. Are you still seeing Redfish action fail?
> 
> ```
> C:\Python310>python InsertEjectVirtualMediaREDFISH.py -ip 192.168.0.120 -u root -p calvin --action insert --index 1 --uripath //192.168.0.130/sambashare/boot.iso --username tester --password "Test123^"
> 
> - PASS, POST command passed to successfully insert virtual media, status code 204 returned
> ```

Closing this as issue is no longer reproducible.  Using double quotes around passwords with special characters works as demonstrated in Tex's example.

**Comment by vincent-tang1** [comment]
> > > python InsertEjectVirtualMediaREDFISH.py -ip 192.168.0.120 -u root -p calvin --action insert --index 1 --uripath //192.168.0.130/sambashare/boot.iso --username tester --password "Test123^"
> > 
> > 
> > sorry, may i have a extenstion question, above examples seems like no **Donain Name** required in sabma. If **Donain Name** is needed, what should the **'--uripath'** value in redfish script is like ? Thanks
> 
> Perhaps try.... --username "DOMAIN_NAME/username" ###make sure to enclose in quotes. This is my best guess.
> 
> I'm no sure if that will work. I do not have to specify the domain name in my use case.

Thanks @srcauley reply,

@texroemer  because we have not the device to try in hand currently, but hope first understand related behavior.
could you help to clarify @srcauley reply ? many thanks

**Comment by vincent-tang1** [comment]
> Hi @vincent-tang1
> 
> I currently don't have access to a samba share setup as a domain controller but if you do have to pass in the domain name to access the SMB share @srcauley response should work. Action VirtualMedia.InsertMedia DMTF does not support domain or workgroup properties to pass in for the body.
> 
> Thanks Tex

Not sure if you would like to add statement about 'Donain Name' operation to this "InsertEjectVirtualMediaREDFISH.py" script help?

**Comment by texroemer** [comment]
@vincent-tang1 

Thanks for pointing this out, I've updated the help text with this information.

-Tex
