### ISSUE TITLE
Traceback error running ExportSystemConfigurationLocalREDFISH.py

### ISSUE THREAD

**Issue by srcauley** [dell/iDRAC-Redfish-Scripting#287]
Windows output:
![image](https://github.com/dell/iDRAC-Redfish-Scripting/assets/160793246/a6d64cdf-4bfb-42d8-b58d-5ee63b24d8b2)

Linux output:
![image](https://github.com/dell/iDRAC-Redfish-Scripting/assets/160793246/47c7d404-f505-41ef-8740-51f081e32439)

Other python scripts seem to be executing without issue to the same server:
![image](https://github.com/dell/iDRAC-Redfish-Scripting/assets/160793246/c20de873-ff16-4984-8897-e3a9457e4f65)

Any ideas what is causing this?

**Comment by texroemer** [comment]
Hi @srcauley 

Thanks for pointing out this script issue, they made changes recently in iDRAC where they removed the version string from #OemManager.ExportSystemConfiguration object name. I added try except to the script to support both old/new iDRAC versions. 

Please try out updated script and let me know if you still see any issues. 

Thanks
Tex

**Comment by srcauley** [comment]
> Hi @srcauley
> 
> Thanks for pointing out this script issue, they made changes recently in iDRAC where they removed the version string from #OemManager.ExportSystemConfiguration object name. I added try except to the script to support both old/new iDRAC versions.
> 
> Please try out updated script and let me know if you still see any issues.
> 
> Thanks Tex

That seems to have resolved the issue.  Thanks much!!!
