### ISSUE TITLE
GracefulRestart performs a hard reset

### ISSUE THREAD

**Issue by pythongates** [dell/iDRAC-Redfish-Scripting#29]
Tested against multiple Dell R730, iDRAC 8 firmware version 2.60.60.60.  

Running the following performs a hard reset which is also confirmed in the Lifecycle logs: 
Set-PowerControlREDFISH -idrac_ip $ip -idrac_username $user -idrac_password $pwd -power_request_value GracefulRestart

Running the following correctly performs a Graceful Shutdown which is also confirmed in the Lifecycle logs: 
Set-PowerControlREDFISH -idrac_ip $ip -idrac_username $user -idrac_password $pwd -power_request_value GracefulShutdown

**Comment by pythongates** [comment]
Looks like the API does not support a Graceful Restart.  When using Postman and sending {"ResetType":"GracefulRestart"} I get a hard reset.  When sending {"ResetType":"GracefulShutdown"} that works properly.

Oddly enough in the iDRAC WebUI, Power Monitoring tab, Power Control drop down there is no Graceful Restart option.

**Comment by texroemer** [comment]
@pythongates

For GracefulRestart value, this is currently a bug in the iDRAC code and will be resolved in next iDRAC firmware release. For a workaround to perform a graceful restart of the server, you will need to execute Set-PowerControlREDFISH passing in a value of GracefulShutdown, then execute cmdlet again passing in a value of On. 

iDRAC GUI (WSMAN and RACADM also) will have similar or different power state commands compared to Redfish. These commands are based off OEM implemented behavior. For Redfish power state commands, these are implemented based off the DMTF Redfish Standards.
