### ISSUE TITLE
Invoke-ChangeIdracUserPasswordREDFISH - New-Object : Exception calling ".ctor" with ....

### ISSUE THREAD

**Issue by wojzag** [dell/iDRAC-Redfish-Scripting#297]
After executing the command:
Invoke-ChangeIdracUserPasswordREDFISH -idrac_ip 10.17.129.242 -idrac_user_id 4 -idrac_new_password Test1234!

I get the following message:
---------------------------------------------------------------------------------------------------------------------------------------
- INFO, executing PATCH command to change iDRAC user password
- PASS, statuscode 200 returned successfully for PATCH command to change iDRAC user password

New-Object : Exception calling ".ctor" with "2" argument(s): "Cannot process argument because the value of argument "us
erName" is not valid. Change the value of the "userName" argument and run the operation again."
At C:\Program Files\WindowsPowerShell\Modules\IdracRedfishSupport\5.0.0\IdracRedfishSupport.psm1:34426 char:15
+ ... redential = New-Object System.Management.Automation.PSCredential($use ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand

- INFO, executing GET command with new user password to validate password was changed
{
    "error": {
        "code": "Base.1.8.GeneralError",
        "message": "A general error has occurred. See ExtendedInfo for more information.",
        "@Message.ExtendedInfo": [
        {
            "@odata.type": "#Message.v1_1_0.Message",
            "MessageId": "Base.1.8.AccessDenied",
            "Message": "The authentication credentials included with this request are missing or invalid.",
            "MessageArgs": [],
            "MessageArgs@odata.count": 0,
            "RelatedProperties":[],
            "RelatedProperties@odata.count": 0,
            "Severity": "Critical",
            "Resolution": "Attempt to ensure that the URI is correct and that the service has the appropriate credentials."
        }
        ]
    }
}
-------------------------------------------------------------------

The script generates an error but the user's password is changed.

Woj.Zag

**Comment by texroemer** [comment]
Hi @wojzag 

Can you share what iDRAC version you're currently using? I just tried the cmdlet on iDRAC9 7.10.30 and unable to repro the issue.

Thanks
Tex

**Comment by texroemer** [comment]
Thanks. Can you update to latest cmdlet and try again. 

```
PS C:\> Invoke-ChangeIdracUserPasswordREDFISH -idrac_ip 192.168.0.120 -idrac_user_id 3 -idrac_new_password Test1234!

- INFO, executing PATCH command to change iDRAC user password

- PASS, statuscode 200 returned successfully for PATCH command to change iDRAC user password

PS C:\> Get-Command -Name Invoke-ChangeIdracUserPasswordREDFISH

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Invoke-ChangeIdracUserPasswordREDFISH              22.17.0.0  IdracRedfishSupport

PS C:\>
```

**Comment by wojzag** [comment]
I had an old version of IdracRedfishSupport installed.
After updating to the latest version, the error does not occur. 
Thank you for your help.

**Comment by texroemer** [comment]
@wojzag 

Good to hear latest cmdlet version does not have this issue.

Thanks
Tex
