### ISSUE TITLE
How can i get size of all disks

### ISSUE THREAD

**Issue by eligosfx** [dell/iDRAC-Redfish-Scripting#3]
right now, getting only:
HealthRollUp: OK
State: Enabled
Health: OK
Model : xxxxxxxxxx
Name: Physical Disk 0:1:3
Manufacturer: HGST

How can I check a size?

**Comment by tehbluemuppetz** [comment]
Please try GetStorageInventoryREDFISH.py. 

Example:
===============
user@yggdrasil:~/Redfish Python$ python ./GetStorageInventoryREDFISH.py -i 192.168.0.120 -u root -p calvin -o c

- Current controllers detected in server:

RAID.Slot.6-1
AHCI.Embedded.2-1
AHCI.Embedded.1-1
 
user@yggdrasil:~/Redfish Python$ python ./GetStorageInventoryREDFISH.py -i 192.168.0.120 -u root -p calvin -c RAID.Slot.6-1

- Supported disks and backplane for controller: RAID.Slot.6-1

**CapacityBytes : 959656755200**
HealthRollup : OK
State : Enabled
Health : OK
Model : SSDSC2BB960G7R
Name : Solid State Disk 0:1:0
Manufacturer : ATA

**Comment by bdesika** [comment]
it didnt work for me. did you mean this? https://raw.githubusercontent.com/dell/iDRAC-Redfish-Scripting/master/Redfish%20Python/GetStorageInventoryREDFISH.py

**Comment by eligosfx** [comment]
Hi, still doesn't work. is this depend on FW version?

**Comment by eligosfx** [comment]
any updates?

**Comment by jonas-werner** [comment]
Hi @eligosfx and @bdesika , 

I've tested on a few 13G servers (iDRAC 8) and can't get size info for the disks on any of them. This is regardless of firmware version. 

It looks like only 14G (iDRAC 9 and PERC 10) returns the disk sizes via Redfish at the moment. I'll check if the size information will be added to later firmware revisions. 

This may or may not be useful in your case, but just in case:
It's possible to use the RACADM command line tool to get the disk sizes also on 13G / iDRAC 8. The command for this is "racadm storage get pdisks -o -p Size". If done remotely (you have RACADM installed on your management PC) you can use "racadm -r <idrac ip> -u root -p calvin storage get pdisks -o -p Size". From Linux it can be done over SSH without having RACADM installed on the Linux management PC.

**Comment by jonas-werner** [comment]
@eligosfx and @bdesika It indeed looks like the disk size info is considered for a near future release.

**Comment by texroemer** [comment]
Currently iDRAC 8 doesn't support reporting disk size using Redfish but will be supported in next release which should be 2.60 version.

Thanks

**Comment by eligosfx** [comment]
Release date?

**Comment by texroemer** [comment]
End of June this year. 

Thanks
