### ISSUE TITLE
Suggestion to remove ForceOff from cmdlets

### ISSUE THREAD

**Issue by pythongates** [dell/iDRAC-Redfish-Scripting#30]
IMHO the following cmdlets should remove the additional step to perform a power "ForceOff"

Invoke-CheckConsistencyVirtualDiskREDFISH
Invoke-CreateVirtualDiskREDFISH
Invoke-DeleteVirtualDiskREDFISH
Invoke-InitializeVirtualDiskREDFISH
Invoke-SecureEraseDeviceREDFISH
Invoke-SetExternalEnclosureAssetTagREDFISH
Set-BiosBootOrderBootSourceStateREDFISH
Set-BiosDefaultSettingsREDFISH
Set-MultipleBIOSAttributesREDFISH
Set-NetworkPropertiesREDFISH
Set-NextOneTimeBootDeviceREDFISH
Set-OneBIOSAttributeREDFISH
Set-UpdateOneDeviceREDFISH

The user should control that action as they see fit using the wonder Set-PowerControlREDFISH cmdlet you created.

Thank you!

**Comment by texroemer** [comment]
@pythongates 

Thanks for the feedback on the cmdlets. I'll work on getting them updated to make the power request dynamic and based off user input what type of server reboot the user wants to perform for the end 2 end workflow.
