### ISSUE TITLE
GetFirmwareInventoryREDFISH.py - Enhancement request: Add or create new version to save to network share

### ISSUE THREAD

**Issue by srcauley** [dell/iDRAC-Redfish-Scripting#300]
Apologies if this is not the right place for this inquiry.

Is there any way to get an updated or separate version of this script that saves to a network share similar to ExportHWInventoryREDFISH.py or ExportSystemConfigurationNetworkShareREDFISH.py?  Any plans for this?

**Comment by texroemer** [comment]
Hi @srcauley 

Currently there is no iDRAC support to only export firmware inventory details to a network share. ExportHWInventoryREDFISH.py script output will contain firmware inventory details along with hardware details, look for FirmwareVersion string in the XML which will report the firmware version for each component.

Example snippet from export hardware inventory XML:

```
<PROPERTY NAME="FQDD" TYPE="string">
<VALUE>iDRAC.Embedded.1-1</VALUE>
<DisplayValue>iDRAC.Embedded.1-1</DisplayValue>
</PROPERTY>
<PROPERTY NAME="FirmwareVersion" TYPE="string">
<VALUE>7.10.30.00</VALUE>
<DisplayValue>7.10.30.00</DisplayValue>
</PROPERTY>
```

Thanks
Tex

**Comment by srcauley** [comment]
> Hi @srcauley
> 
> Currently there is no iDRAC support to only export firmware inventory details to a network share. ExportHWInventoryREDFISH.py script output will contain firmware inventory details along with hardware details, look for FirmwareVersion string in the XML which will report the firmware version for each component.
> 
> Example snippet from export hardware inventory XML:
> 
> ```
> <PROPERTY NAME="FQDD" TYPE="string">
> <VALUE>iDRAC.Embedded.1-1</VALUE>
> <DisplayValue>iDRAC.Embedded.1-1</DisplayValue>
> </PROPERTY>
> <PROPERTY NAME="FirmwareVersion" TYPE="string">
> <VALUE>7.10.30.00</VALUE>
> <DisplayValue>7.10.30.00</DisplayValue>
> </PROPERTY>
> ```
> 
> Thanks Tex

Thank you Tex! I will close this inquiry with the information provided.

Shane
