### ISSUE TITLE
Use redfish to mount local iso for OS install similar to how webUI works

### ISSUE THREAD

**Issue by jallirs** [dell/iDRAC-Redfish-Scripting#302]
Although, it might not be there today in the redfish spec, something that should be possible given functionality exists in racadm/vmcli cli tools, as well as in the idrac webUI is the ability to mount a local iso/disk image for the purposes of OS installation. What exists today in the redfish spec as an alternative is the ability to use a remote fileserver/ fileshare. 
However, I still long for the days when you could just do this with CLI and a standard interface would certainly make things easier and simpler not just for home users, but also for those of us that manage servers professionally.

**Comment by texroemer** [comment]
Hi @jallirs 

You're correct DMTF does not currently support attaching a local ISO/IMG as virtual media. But i did ask a Dell team member who's part of the DMTF community and he stated there are discussions currently going on to see if support can be added in the future (no ETA on when or if support can be added). 

Btw VirtualMedia schema does have this statement for Image property "A service may allow a relative URI to reference a SoftwareInventory resource" but currently iDRAC does not support this. 

https://github.com/DMTF/Redfish-Publications/blob/main/csdl/VirtualMedia_v1.xml#L84

Thanks
Tex
