### ISSUE TITLE
Where is the script GetBiosBootOrderBootSourceStateREDFISH.py?

### ISSUE THREAD

**Issue by jasmeer** [dell/iDRAC-Redfish-Scripting#305]
Hi
I have seen references to this script; but did not find it in repo. 
Thanks
Jasmeer

**Comment by texroemer** [comment]
Hi @jasmeer 

I removed this script once iDRAC added DMTF support to change the boot order (originally only OEM extension was supported to change boot order) but i added it back with updated fixes / enhancements. See script "ChangeBiosBootOrderSourceStateREDFISH.py".

Thanks
Tex

**Comment by jasmeer** [comment]
Thanks a lot @texroemer.
