### ISSUE TITLE
Redfish Query 

### ISSUE THREAD

**Issue by yograj099** [dell/iDRAC-Redfish-Scripting#307]
Hi,

What is the header value we can pass with redfish uri while querying for RDE ?
Can someone please share header values ?

**Comment by texroemer** [comment]
Hi @yograj099 

Can you share what URI you're trying to run iDRAC Redfish request against?

Thanks
Tex

**Comment by yograj099** [comment]
HI,

Please find the uri below:
https://<Server IP>/redfish/v1/Chassis/System.Embedded.1/NetworkAdapters/FC.Slot.8/

**Comment by texroemer** [comment]
Thanks, header for GET request should be "Content-Type: application/json", if you still see a failure can you share details of the Redfish call along with the error returned.

Thanks
Tex

**Comment by yograj099** [comment]
Hi,

I do not see any error with redfish uri. I have a proper output as well. Question here is , GET operation is retrieving the data through DCi ,not via RDE.  I want redfish to retrieve the data through RDE.

**Comment by texroemer** [comment]
Hi @yograj099 

RDE is currently not supported by iDRAC and is mentioned in this previous issue:

https://github.com/dell/iDRAC-Redfish-Scripting/issues/277

Thanks
Tex

**Comment by yograj099** [comment]
Thanks Tex. I expected that with new releases support might have added  as its in plan.
Thanks again for your time.
