### ISSUE TITLE
Broken link 

### ISSUE THREAD

**Issue by roddynwr** [dell/iDRAC-Redfish-Scripting#309]
At this site: https://github.com/dell/iDRAC-Redfish-Scripting?tab=readme-ov-file the link for: ""iDRAC User Interface to Redfish Mapping" " is broken. need correct site for the link. Thanks!
![Screenshot 2024-07-26 083145](https://github.com/user-attachments/assets/02f6d785-43ad-4e1a-ae86-8913ebeefd0d)

**Comment by texroemer** [comment]
Hi @roddynwr 

Thanks for pointing out this issue, link has been fixed. 

Thanks
Tex
