### ISSUE TITLE
Set-IdracLcSystemAttributesREDFISH invalid url?

### ISSUE THREAD

**Issue by pythongates** [dell/iDRAC-Redfish-Scripting#31]
I don't believe these urls exist.  I'm getting this error:
"Unable to complete the operation because the resource Attributes entered in not found."

"https://$idrac_ip/redfish/v1/Managers/iDRAC.Embedded.1/Attributes"
"https://$idrac_ip/redfish/v1/Managers/LifecycleController.Embedded.1/Attributes"
"https://$idrac_ip/redfish/v1/Managers/System.Embedded.1/Attributes"

Additionally browsing with Postman I don't see "Attributes"

**Comment by texroemer** [comment]
@pythongates 

Yes, these URIs are not supported on iDRAC 7/8 but are supported on iDRAC 9. I updated the Python scripts with a check to validate if version of iDRAC detected is supported or not. 

If you are using iDRAC 7/8, use Server Configuration Profile (SCP ) feature to either SET or GET iDRAC / System or Lifecycle Controller attributes.
