### ISSUE TITLE
Work notes?

### ISSUE THREAD

**Issue by Gerardwx** [dell/iDRAC-Redfish-Scripting#312]
Does the Redfish API allow reading and writing of the Work notes that are on the main screen of the iDrac Web interface?

(Unfortunately "note" is such a common phrase in the docs google and grep are failing me.)

**Comment by texroemer** [comment]
Hi @Gerardwx 

OEM action "DellLCService.InsertCommentInLCLog" will add a work note to iDRAC GUI / Dashboard / Notes section besides adding the same work note to iDRAC LC logs. 

See script InsertLclogCommentREDFISH.py for code example.

Thanks
Tex

**Comment by Gerardwx** [comment]
In the words of the great technician Homer Simpson: D'oh!

Works perfectly.
