### ISSUE TITLE
DeviceFirmwareUpdateREDFISH.py compatibility issue 

### ISSUE THREAD

**Issue by muraliselva10** [dell/iDRAC-Redfish-Scripting#32]
We want to upgrade idrac version to 2.60.60.60 on our 400 plus hosts, So that we tried executing the script for the same (DeviceFirmwareUpdateREDFISH.py ).

We use idrac version 2.50.50.50.

It give us message: WARNING, current server iDRAC version does not support Redfish firmware features. Refer to Dell online Redfish documentation for information on which iDRAC version supports firmware features.

We want to know whether is there any way available for upgrading the idrac version using this script or any other ways available.

**Comment by texroemer** [comment]
@muraliselva10 

Hi,

With older version of iDRAC installed that doesn't support updates using Redfish, you will have to use either WSMAN or RACADM to update your iDRAC to latest version with scripting.

Here's an example of using remote RACADM command to update the iDRAC. The update will get applied immediately and no server reboot is needed. If you want to script this command, use Python subprocess module.

C:\>racadm -r 192.168.0.120 -u root -p calvin update -f iDRAC-with-Lifecycle-Controller_Firmware_CX8N2_WN64_2.60.60.60_A00.EXE
Security Alert: Certificate is invalid - Certificate is not signed by Trusted Third Party
Continuing execution. Use -S option for racadm to stop execution on certificate-related errors.
        The Copying Operation has begun,
        This might take several minutes to complete, depending on the network.
        Do not interrupt the operation.
RAC987: Firmware update job for iDRAC-with-Lifecycle-Controller_Firmware_CX8N2_WN64_2.60.60.60_A00.EXE is initiated.
This firmware update job may take several minutes to complete depending on the
component or firmware being updated. To view the progress of the job, use the
"racadm jobqueue view" command. If the job is scheduled, the system will require a manual reboot.
To reboot the system  manually, use the "racadm serveraction powercycle" command.

**Comment by muraliselva10** [comment]
Thanks for the answer, Is it possible to initiate multiple servers at the same time ? We have n number of servers, So need to update at once, If we do by this way it will wait for one server to complete then only start the next server. Is there any command-line options available ?

**Comment by Roddd** [comment]
> Thanks for the answer, Is it possible to initiate multiple servers at the same time ? We have n number of servers, So need to update at once, If we do by this way it will wait for one server to complete then only start the next server. Is there any command-line options available ?

@muraliselva10 : Why not just do a script and launch each command as a subprocess? I usually run a batch of commands 20 or 50 at a time. With python, import multiprocessing. With bash, just "&".

**Comment by BLR1458** [comment]
Hi,

I am trying to upgrade BIOS version to 2.2.5 using this script I am unable to do.
And iDRAC version i am using is 2.60.60.60.

Could you please help me with full redfish API to upgrade BIOS version from 1.2.5 to 2.2.5. I need to run redfish API with curl command.

Regards,
Salma

**Comment by texroemer** [comment]
Hi @BLR1458 

DeviceFirmwareUpdate script has been removed and replaced with DeviceFirmwareDellUpdateServiceREDFISH and DeviceFirmwareSimpleUpdateREDFISH scripts. DellUpdateService uses OEM method and SimpleUpdate uses DMTF method. Please try one of these scripts for updates which should work.

For using CURL, example workflow below of updating the BIOS firmware:

1. First you want to execute GET command to get current ETag for Firmware inventory. ETag is needed for uploading the firmware image:

[root@vm1 opt]# curl -GET "https://192.168.0.120/redfish/v1/UpdateService/FirmwareInventory
" -u root:calvin --insecure -i -o output.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
101  2121  101  2121    0     0     91      0  0:00:23  0:00:23 --:--:--   634
[root@vm1 opt]# cat output.txt
HTTP/1.1 200 OK
OData-Version: 4.0
Keep-Alive: timeout=60, max=199
Content-Type: application/json;odata.metadata=minimal;charset=utf-8
Server: iDRAC/8
Date: Wed, 17 Oct 2018 19:06:36 GMT
**ETag: b5a284cf5c079720baf10922407c8a50**
Link: </redfish/v1/Schemas/SoftwareInventoryCollection.json>;rel=describedby
Cache-Control: no-cache
Content-Length: 2121
Allow: POST
Connection: Keep-Alive
Access-Control-Allow-Origin: *
Accept-Ranges: bytes

{"@odata.context":"/redfish/v1/$metadata#SoftwareInventoryCollection.SoftwareInventoryCollection","@odata.id":"/redfish/v1/UpdateService/FirmwareInventory","@odata.type":"#SoftwareInventoryCollection.SoftwareInventoryCollection","Description":"Collection of Firmware Inventory","Members":[{"@odata.id":"/redfish/v1/UpdateService/FirmwareInventory/Current-101068-3.35"},{"@odata.id":"/redfish/v1/UpdateService/FirmwareInventory/Current-101557-25.5.4.0006"},{"@odata.id":"/redfish/v1/UpdateService/FirmwareInventory/Current-101560-25.5.4.0006"},{"@odata.id":"/redfish/v1/UpdateService/FirmwareInventory/Current-159-2.8.0"},{"@odata.id":"/redfish/v1/UpdateService/FirmwareInventory/Installed-101068-3.35"},{"@odata.id":"/redfish/v1/UpdateService/FirmwareInventory/Installed-101097-00.10.37"},{"@odata.id":"/redfish/v1/UpdateService/FirmwareInventory/Installed-101557-25.5.4.0006"},{"@odata.id":"/redfish/v1/UpdateService/FirmwareInventory/Installed-101560-25.5.4.0006"},{"@odata.id":"/redfish/v1/UpdateService/FirmwareInventory/Installed-101734-OSC_1.1"},{"@odata.id":"/redfish/v1/UpdateService/FirmwareInventory/Installed-101809-110C"},{"@odata.id":"/redfish/v1/UpdateService/FirmwareInventory/Installed-159-2.8.0"},{"@odata.id":"/redfish/v1/UpdateService/FirmwareInventory/Installed-18981-14.05.10"},{"@odata.id":"/redfish/v1/UpdateService/FirmwareInventory/Installed-25227-2.60.60.60"},{"@odata.id":"/redfish/v1/UpdateService/FirmwareInventory/Installed-25806-0"},{"@odata.id":"/redfish/v1/UpdateService/FirmwareInventory/Installed-27763-1.0.1"},{"@odata.id":"/redfish/v1/UpdateService/FirmwareInventory/Installed-28897-2.60.60.60"},{"@odata.id":"/redfish/v1/UpdateService/FirmwareInventory/Previous-101068-3.35"},{"@odata.id":"/redfish/v1/UpdateService/FirmwareInventory/Previous-101557-25.5.4.0006"},{"@odata.id":"/redfish/v1/UpdateService/FirmwareInventory/Previous-101560-25.5.4.0006"},{"@odata.id":"/redfish/v1/UpdateService/FirmwareInventory/Previous-159-2.7.1"},{"@odata.id":"/redfish/v1/UpdateService/FirmwareInventory/Previous-25227-2.60.60.60"}],"Members@odata.count":21,"Name":"Firmware Inventory Collection"}

2. Take the ETag along with the name of the firmware DUP (must be Windows DUP) and execute POST command.

[root@vm1 opt]# curl -X POST -u root:calvin -i -o output.txt  --insecure -H "If-Match:b5a2
84cf5c079720baf10922407c8a50" -F "file=@BIOS_NMF8F_WN64_2.7.1.EXE" https://192.168.0.120/re
dfish/v1/UpdateService/FirmwareInventory
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 17.7M    0  1167  100 17.7M     10   166k  0:01:49  0:01:49 --:--:--     0
[root@vm1 opt]# cat output.txt
HTTP/1.1 100 Continue

HTTP/1.1 201 Created
Keep-Alive: timeout=60, max=199
Content-Type: application/json
Location: /redfish/v1/UpdateService/FirmwareInventory/Available-159-2.7.1
Date: Wed, 17 Oct 2018 19:08:59 GMT
Connection: Keep-Alive
Transfer-Encoding: chunked
Accept-Ranges: bytes

{"@Message.ExtendedInfo":[{"Message":"Package successfully downloaded.","MessageArgs":[],"MessageArgs@odata.count":0,"MessageId":"iDRAC.1.5.RED002","RelatedProperties":[],"RelatedProperties@odata.count":0,"Resolution":"Schedule the job if it is not already scheduled.","Severity":"Informational"},{"Message":"The resource has been created successfully","MessageArgs":[],"MessageArgs@odata.count":0,"MessageId":"Base.1.0.Created","RelatedProperties":[],"RelatedProperties@odata.count":0,"Resolution":"None","Severity":"OK"},{"Message":"A new resource is successfully created.","MessageArgs":[],"MessageArgs@odata.count":0,"MessageId":"iDRAC.1.5.SYS414","RelatedProperties":[],"RelatedProperties@odata.count":0,"Resolution":"No response action is required.","Severity":"Informational"}],"@odata.context":"/redfish/v1/$metadata#SoftwareInventory.SoftwareInventory","@odata.id":"**/redfish/v1/UpdateService/FirmwareInventory/Available-159-2.7.1**","@odata.type":"#SoftwareInventory.v1_0_0.SoftwareInventory","Description":"Represents Firmware Inventory","Id":"Available-159-2.7.1","Name":"BIOS","Status":{"Health":"OK","State":"Enabled"},"Updateable":true,"Version":"2.7.1"}

3. From previous output, you want to take the Available URI returned for the downloaded package and use this to generate a update job. 

[root@vm1 opt]# curl -X POST -u root:calvin -i -o output.txt  --insecure -k https://192.168.0.120/redfish/v1/UpdateService/Actions/UpdateService.SimpleUpdate -d '{"ImageURI":"/redfi
sh/v1/UpdateService/FirmwareInventory/Available-159-2.7.1"}' -H "Content-Type: application
/json"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0    78      0     12 --:--:--  0:00:06 --:--:--     0
[root@vm1 opt]# cat output.txt
HTTP/1.1 202 Accepted
OData-Version: 4.0
Keep-Alive: timeout=60, max=199
Content-Type: application/json;odata.metadata=minimal;charset=utf-8
Server: iDRAC/8
**Location: /redfish/v1/TaskService/Tasks/JID_398033659417**
Date: Wed, 17 Oct 2018 19:09:26 GMT
Cache-Control: no-cache
Content-Length: 0
Connection: Keep-Alive
Access-Control-Allow-Origin: *
Accept-Ranges: bytes

4. In previous output, you should see a URI returned with job ID. Take this URI and run a GET to verify the status. Once you see a status of Scheduled, you need to reboot the server to execute the job to apply the firmware update.

[root@vm1 opt]# curl -GET "https://192.168.0.120/redfish/v1/TaskService/Tasks/JID_398033659
417" -u root:calvin --insecure
{"@odata.context":"/redfish/v1/$metadata#Task.Task","@odata.id":"/redfish/v1/TaskService/Tasks/JID_398033659417","@odata.type":"#Task.v1_0_2.Task","Description":"Server Configuration and other Tasks running on iDRAC are listed here","EndTime":"1969-12-31T18:00:00-06:00","Id":"JID_398033659417","Messages":[{"Message":"Downloading the BIOS_NMF8F_WN64_2.7.1.EXE update package.","MessageArgs":[],"MessageArgs@odata.count":0,"MessageId":"RED110"}],"Messages@odata.count":1,"Name":"Firmware Update: BIOS","Oem":{"Dell":{"@odata.type":"#DellManager.v1_0_0.DellManager","Jobs":{"@odata.id":"/redfish/v1/Managers/iDRAC.Embedded.1/Jobs"}}},"StartTime":"","TaskState":"New","TaskStatus":"OK"}
[root@vm1 opt]# curl -GET "https://192.168.0.120/redfish/v1/TaskService/Tasks/JID_398033659
417" -u root:calvin --insecure
{"@odata.context":"/redfish/v1/$metadata#Task.Task","@odata.id":"/redfish/v1/TaskService/Tasks/JID_398033659417","@odata.type":"#Task.v1_0_2.Task","Description":"Server Configuration and other Tasks running on iDRAC are listed here","EndTime":"1969-12-31T18:00:00-06:00","Id":"JID_398033659417","Messages":[{"Message":"Package successfully downloaded.","MessageArgs":[],"MessageArgs@odata.count":0,"MessageId":"RED002"}],"Messages@odata.count":1,"Name":"Firmware Update: BIOS","Oem":{"Dell":{"@odata.type":"#DellManager.v1_0_0.DellManager","Jobs":{"@odata.id":"/redfish/v1/Managers/iDRAC.Embedded.1/Jobs"}}},"StartTime":"","TaskState":"Starting","TaskStatus":"OK"}
[root@vm1 opt]# curl -GET "https://192.168.0.120/redfish/v1/TaskService/Tasks/JID_398033659
417" -u root:calvin --insecure
{"@odata.context":"/redfish/v1/$metadata#Task.Task","@odata.id":"/redfish/v1/TaskService/Tasks/JID_398033659417","@odata.type":"#Task.v1_0_2.Task","Description":"Server Configuration and other Tasks running on iDRAC are listed here","EndTime":"1969-12-31T18:00:00-06:00","Id":"JID_398033659417","Messages":[{"**Message":"Task successfully scheduled.**","MessageArgs":[],"MessageArgs@odata.count":0,"MessageId":"JCP001"}],"Messages@odata.count":1,"Name":"Firmware Update: BIOS","Oem":{"Dell":{"@odata.type":"#DellManager.v1_0_0.DellManager","Jobs":{"@odata.id":"/redfish/v1/Managers/iDRAC.Embedded.1/Jobs"}}},"StartTime":"","TaskState":"Pending","TaskStatus":"OK"}

5. Execute POST commands to reboot the server.

[root@vm1 opt]# curl -k "https://192.168.0.120/redfish/v1/Systems/System.Embedded.1/Actions
/ComputerSystem.Reset" -d '{"ResetType":"ForceOff"}' -X POST -u root:calvin -H "Content-Ty
pe: application/json" -i -o output.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0    24      0      4 --:--:--  0:00:04 --:--:--     0
[root@vm1 opt]# curl -k "https://192.168.0.120/redfish/v1/Systems/System.Embedded.1/Actions
/ComputerSystem.Reset" -d '{"ResetType":"On"}' -X POST -u root:calvin -H "Content-Type: ap
plication/json" -i -o output.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0    18      0      3 --:--:--  0:00:05 --:--:--     0

6. After server reboots, you want to query the job status until marked completed

[root@vm1 opt]# curl -GET "https://192.168.0.120/redfish/v1/TaskService/Tasks/JID_398033659417" -u root:calvin --insecure
{"@odata.context":"/redfish/v1/$metadata#Task.Task","@odata.id":"/redfish/v1/TaskService/Tasks/JID_398033659417","@odata.type":"#Task.v1_0_2.Task","Description":"Server Configuration and other Tasks running on iDRAC are listed here","EndTime":"2018-10-17T14:20:37-05:00","Id":"JID_398033659417","Messages":[{"**Message":"Job completed successfully.**","MessageArgs":[],"MessageArgs@odata.count":0,"MessageId":"PR19"}],"Messages@odata.count":1,"Name":"Firmware Update: BIOS","Oem":{"Dell":{"@odata.type":"#DellManager.v1_0_0.DellManager","Jobs":{"@odata.id":"/redfish/v1/Managers/iDRAC.Embedded.1/Jobs"}}},"StartTime":"","TaskState":"Completed","TaskStatus":"OK"}
