### ISSUE TITLE
Changing BIOS setting for LogicalProc to Enabled

### ISSUE THREAD

**Issue by tdeneau** [dell/iDRAC-Redfish-Scripting#33]
I tried to use the BiosSetAttributeREDFISH.py script to change the "LogicalProc" setting to "Enabled" (enabling SMT).   Everything reported as working, the  update job got scheduled and the system rebooted.  After it came up BiosGetAttributesREDFISH.py reported LogicalProc as Enabled.  But the total number of processors reported by nproc had not changed.

Even when I enter the BIOS and look at LogicalProc, it is set to enabled.
And if I then exit from the BIOS, it doesn't think anything has changed and doesn't do a reboot, and nproc still shows that LogicalProc is not being recognized.

I had to enter the BIOS, make some other needless change, which caused it to go thru reboot.  That did then manage to really change LogicalProc as reflected by nproc.

 This was on a Dell r7425.

**Comment by texroemer** [comment]
Hi,

After changing LogicalProc BIOS setting to enabled, where are you checking the logical proc count? Are you running a GET on URI "redfish/v1/Systems/System.Embedded.1" and under ProcessorSummary, verify LogicalProcessorCount property? 

I verified on a R7425 with LogicalProc disabled, i was seeing LogicalProcessorCount report 32. Once i enabled LogicalProc, it now reports 64.

**Comment by tdeneau** [comment]
I don't believe I looked at LogicalProcessorCount under Processor Summary.  The Redfish BIOS attribute for LogicalProc did show it enabled.  But when the OS came up after the "update job" caused a reboot, the number of processors reported by linux (nproc) had not changed.

Did you see a change in the nproc processor count reported by the OS after your Redfish change?

**Comment by texroemer** [comment]
Yes, i also checked from the OS (i have RHEL 7) and nproc reported the correct value.

Here's output from my system and checking after i changed LogicalProc attribute from Enabled to Disabled and back to Enabled:

_[root@localhost opt]# nproc
64
[root@localhost opt]# ./BiosGetAttributesREDFISH.py -ip 192.168.0.120 -u root -p calvin -
a LogicalProc

- Current value for attribute "LogicalProc" is "Enabled"

[root@localhost opt]# ./BiosGetAttributesREDFISH.py -ip 192.168.0.120 -u root -p calvin -
a LogicalProc

- Current value for attribute "LogicalProc" is "Disabled"

[root@localhost opt]# nproc
32

[root@localhost opt]# ./BiosGetAttributesREDFISH.py -ip 192.168.0.120 -u root -p calvin -
a LogicalProc

- Current value for attribute "LogicalProc" is "Enabled"

[root@localhost opt]# nproc
64_

What is your BIOS version and also what linux OS are you using? I will try to repro the issue with the linux OS you are using.

**Comment by tdeneau** [comment]
Here is the BIOS info as printed by dmidecode
BIOS Information
    Vendor: Dell Inc.
    Version: 1.2.5
    Release Date: 03/13/2018

The OS is Ubuntu 18.04.1 LTS
I definitely see it doing the "update job" and rebooting after SetAttributeREDFISH.py

Can you send the BiosSetAttributeREDFISH.py command line you are using?

**Comment by texroemer** [comment]
Hi,

I discussed this issue with BIOS team at Dell and this is indeed a BIOS defect which will be addressed in next BIOS release. This new BIOS version is expected to come out Dec of this year. This issue is only with AMD platforms, no issues with Intel platforms. 

Thanks for bringing this issue to my attention which I was able to escalate to the correct team at Dell to get resolved.

**Comment by tdeneau** [comment]
Looking forward to the new version...
