### ISSUE TITLE
PowerSupply and Temperature overview

### ISSUE THREAD

**Issue by urbanb** [dell/iDRAC-Redfish-Scripting#34]
Feature Request:
It would be great to have an overview of the overall and specific sensor data with redfish and PowerShell.
Like power consumption, temperature, all sensor data, and overall health.

**Comment by texroemer** [comment]
Hi,

In current shipping iDRAC 8 2.60 and iDRAC 9 3.21, sensor and temperature readings are not supported with Redfish (health is supported) but will be supported in next iDRAC release which will be available early next year.

With current shipping iDRAC with Redfish, here's an example of current information reported for power supplies with GET on URI "redfish/v1/Chassis/System.Embedded.1/Power" which will report the health of the power supply:


@odata.context | "/redfish/v1/$metadata#Power.Power"
-- | --
@odata.id | "/redfish/v1/Chassis/System.Embedded.1/Power"
@odata.type | "#Power.v1_3_0.Power"
Description | "Power"
Id | "Power"
Name | "Power"
PowerControl |  
0 |  
@odata.id | "/redfish/v1/Chassis/System.Embedded.1/Power/PowerControl"
MemberId | "PowerControl"
Name | "System Power Control"
PowerAllocatedWatts | 750
PowerAvailableWatts | 0
PowerCapacityWatts | 902
PowerConsumedWatts | 135
PowerLimit |  
CorrectionInMs | 0
LimitException | "HardPowerOff"
LimitInWatts | 152
PowerMetrics |  
AverageConsumedWatts | 135
IntervalInMin | 1
MaxConsumedWatts | 147
MinConsumedWatts | 132
PowerRequestedWatts | 488
RelatedItem |  
0 |  
@odata.id | "/redfish/v1/Chassis/System.Embedded.1"
1 |  
@odata.id | "/redfish/v1/Systems/System.Embedded.1"
RelatedItem@odata.count | 2
PowerControl@odata.count | 1
PowerSupplies |  
0 |  
@odata.id | "/redfish/v1/Chassis/System.Embedded.1/Power/PowerSupplies/PSU.Slot.1"
FirmwareVersion | "00.16.4F"
InputRanges |  
0 |  
InputType | "AC"
MaximumFrequencyHz | 47
MaximumVoltage | 90
MinimumFrequencyHz | 63
MinimumVoltage | 264
OutputWattage | 750
InputRanges@odata.count | 1
LastPowerOutputWatts | 750
LineInputVoltage | 208
LineInputVoltageType | "AC240V"
Manufacturer | "Dell"
MemberId | "PSU.Slot.1"
Model | "PWR SPLY,750W,RDNT,ARTESYN    "
Name | "PS1 Status"
PartNumber | "0Y9VFCA00"
PowerCapacityWatts | 750
PowerSupplyType | "AC"
Redundancy | []
Redundancy@odata.count | 0
RelatedItem |  
0 |  
@odata.id | "/redfish/v1/Chassis/System.Embedded.1"
RelatedItem@odata.count | 1
SerialNumber | "PH1629868100PC"
SparePartNumber | "0Y9VFCA00"
Status |  
Health | "OK"
State | "Enabled"
PowerSupplies@odata.count | 1
Redundancy | []
Redundancy@odata.count | 0
