### ISSUE TITLE
DeviceFirmwareSimpleUpdateREDFISH.py assumes Windows

### ISSUE THREAD

**Issue by howardjones** [dell/iDRAC-Redfish-Scripting#35]
DeviceFirmwareSimpleUpdateREDFISH.py should use os.path.join to create ImagePath, not inserting a backslash. On a unix system, this produces an invalid path.

That is, 
`    ImagePath = ImageLocation + "\\" + filename`

should be:
`    ImagePath = os.path.join(ImageLocation, filename)`

to work on both platforms.

**Comment by texroemer** [comment]
Hi,

Thanks for the script change to work in both Windows and Linux. Updated scripts have been uploaded.
