### ISSUE TITLE
Api returning error 500

### ISSUE THREAD

**Issue by nildoadao** [dell/iDRAC-Redfish-Scripting#36]
Hi, we are implementing an .NET client to consume Dell Redfish api, it works fine for most functions but returns an error 500 when we try to upload an firmware to Idrac, 

We are running the tests on a R740, the Idrac version is 3.21.23.22

here's the code I'm using to upload the file:

`

        private async Task<Uri> UploadFile(string path)
        {
            using (var request = new HttpRequestMessage(HttpMethod.Post, baseUri + FIRMWARE_INVENTORY))
            using (var content = new MultipartFormDataContent(Guid.NewGuid().ToString()))
            using (var fileContent = new StreamContent(File.Open(path, FileMode.Open)))
            {
                string etag = await GetHeaderValue("ETag", baseUri + FIRMWARE_INVENTORY);
                fileContent.Headers.ContentType = MediaTypeHeaderValue.Parse("application/octet-stream");
                request.Headers.Authorization = HttpUtil.GetCredentialHeader(server.User, server.Password);
                request.Headers.TryAddWithoutValidation("If-Match", etag);
                fileContent.Headers.ContentDisposition = new ContentDispositionHeaderValue("form-data")
                {
                    Name = "file",
                    FileName = Path.GetFileName(path).ToLower()
                };
                content.Add(fileContent);
                request.Content = content;
                using (HttpResponseMessage response = await client.SendAsync(request))
                {
                    if (!response.IsSuccessStatusCode)
                    {
                        throw new HttpRequestException("Falha no upload do arquivo: " + response.ReasonPhrase);
                    }
                    return response.Headers.Location;
                }
            }
        }

`

**Comment by texroemer** [comment]
Hi,

Can you print out the status code details for status code 500? There should be error messages returned in the POST response which will get more details on what is failing.

Can you also try python script "DeviceFirmwareSimpleUpdateREDFISH.py" to see if this works? This will help narrow down if its a script issue or iDRAC issue.

Thanks

**Comment by nildoadao** [comment]
Hi,

POST command returns an empty string along with status code 500 "Internal Server Error", the python script works fine.

Thanks

**Comment by nildoadao** [comment]
Hi,

I've tried the same procedure but this time using Postman, and I'm still getting the 500 error, here's the output from Postman

![image](https://user-images.githubusercontent.com/15050535/47854877-baf75c80-ddc1-11e8-8677-4c894cafe683.png)

here the headers I'm using

![image](https://user-images.githubusercontent.com/15050535/47855047-335e1d80-ddc2-11e8-894c-c4e2d3b74819.png)

**Comment by texroemer** [comment]
@nildoadao 

For the Body, did you select "File" for a key and then choose a file? I repro the issue you were seeing but this happened because i didn't set up the Body to point to a file.

Here's from my server below showing the Body where i pointed it to a file.

![image](https://user-images.githubusercontent.com/30351677/47861793-98fdda00-ddc1-11e8-9d62-4feb1352fb87.png)

![image](https://user-images.githubusercontent.com/30351677/47861819-aa46e680-ddc1-11e8-8725-9f528d73ec9c.png)

**Comment by texroemer** [comment]
@nildoadao 

Good to hear you got it to work and also fixed your script, glad to help out!
