### ISSUE TITLE
Redfish API for generating  X.509 certificate dynamically

### ISSUE THREAD

**Issue by avinashcpandey** [dell/iDRAC-Redfish-Scripting#38]
Is there any API in Redfish for generating  X.509 certificate dynmically. If yes what is the signature of that API and how do we pass input attributes to that?

**Comment by texroemer** [comment]
Hi,

In shipping iDRAC, we don't support cert management with Redfish but current plan is to support the Redfish 2018 standard APIs for cert management in our next iDRAC release which should be available March of next year.

Thanks

**Comment by mister2d** [comment]
Does that mean that certificate management is currently only supported by `racadm` for 14g servers?

**Comment by texroemer** [comment]
@mister2d 

That's correct. Next 14G iDRAC 9 release 3.30 will have Redfish support for this feature. 3.30 is scheduled to be posted next month.
