### ISSUE TITLE
Redfish script to upgrade BIOS, Controller and Idrac

### ISSUE THREAD

**Issue by tyagian** [dell/iDRAC-Redfish-Scripting#39]
I am using Idrac 7, 8 and 9 on R730xd and need to upgrade BIOS, controllers, and Idrac in bulk of servers. It would be great if we have Redfish or non-redfish based Python script to upgrade them. 
Or just script to upload iso/ exe which we usually do to upgrade them.

**Comment by tyagian** [comment]
Great. Thanks a lot. Did you just write it now?  
I found 2 relevant scripts (DeviceFirmwareDellUpdateServiceREDFISH and DeviceFirmwareSimpleUpdateREDFISH.py) but this one is new and not available in the repository yet.

**Comment by texroemer** [comment]
New RACADM script i just created since you will have servers at an iDRAC version which doesn't have Redfish update support. Once you update iDRAC 7/8 to 2.60, you can then use the Redfish scripts you mentioned. If you have 14G servers with iDRAC 9, you can already use the Redfish scripts but the RACADM script i just created will also work.

**Comment by tyagian** [comment]
Appreciate your efforts.

**Comment by texroemer** [comment]
No problem, glad to help!

**Comment by tyagian** [comment]
Do you also know any way to upgrade BIOS also using a script? This only upgrade firmware. There are Idrac 8 and 9 both in different environments.

**Comment by texroemer** [comment]
Once at the latest iDRAC versions i mentioned, you can use script "DeviceFirmwareSimpleUpdateREDFISH.py" to perform firmware updates for devices. 

Example below is using this script to update the BIOS on R730 from 2.7.1 to 2.8.0.

C:\Python27>DeviceFirmwareSimpleUpdateREDFISH.py -ip 192.168.0.120 -u root -p calvin -g y

- WARNING, current devices detected with firmware version and updateable status -

Device Name: Power Supply.Slot.1, Firmware Version: 00.10.37, Updatable: True
Device Name: BP13G+ 0:1, Firmware Version: 2.25, Updatable: True
Device Name: PERC H730 Mini, Firmware Version: 25.5.5.0005, Updatable: True
Device Name: OS COLLECTOR 1.1, OSC_1.1, A00, Firmware Version: OSC_1.1, Updatable: True
Device Name: Disk 5 in Backplane 1 of Integrated RAID Controller 1, Firmware Version: VT31, Updatable: True
**Device Name: BIOS, Firmware Version: 2.7.1, Updatable: True**
Device Name: Dell OS Driver Pack, 17.08.10, A00, Firmware Version: 17.08.10, Updatable: True
Device Name: Integrated Dell Remote Access Controller, Firmware Version: 2.60.60.60, Updatable: True
Device Name: Diagnostics, Firmware Version: 0, Updatable: True
Device Name: QLogic 577xx/578xx 10 Gb Ethernet BCM57810 - 00:0A:F7:5D:7A:72, Firmware Version: 14.04.18, Updatable: True
Device Name: Broadcom Gigabit Ethernet BCM5720 - 44:A8:42:46:9C:2B, Firmware Version: 7.10.64, Updatable: True
Device Name: System CPLD, Firmware Version: 1.0.1, Updatable: True
Device Name: Lifecycle Controller, Firmware Version: 2.60.60.60, Updatable: False

C:\Python27>DeviceFirmwareSimpleUpdateREDFISH.py -ip 192.168.0.120 -u root -p calvin -l C:\Python27\master_scripts_modified -f BIOS_2JFRF_WN64_2.8.0.EXE

- WARNING, downloading "BIOS_2JFRF_WN64_2.8.0.EXE" image, this may take a few minutes depending on the size of the image

- PASS: POST command passed successfully to download image, status code 201 returned
- WARNING, AVAILABLE entry created for download image "BIOS_2JFRF_WN64_2.8.0.EXE" is "Available-159-2.8.0"
- PASS, JID_418172050541 firmware update job ID successfully created
- Message: Downloading the BIOS_2JFRF_WN64_2.8.0.EXE update package., current job execution time is: 0:00:03
- Message: Downloading the BIOS_2JFRF_WN64_2.8.0.EXE update package., current job execution time is: 0:00:06
- Message: Downloading the BIOS_2JFRF_WN64_2.8.0.EXE update package., current job execution time is: 0:00:11
- Message: Downloading the BIOS_2JFRF_WN64_2.8.0.EXE update package., current job execution time is: 0:00:16
- Message: Downloading the BIOS_2JFRF_WN64_2.8.0.EXE update package., current job execution time is: 0:00:21
- Message: Downloading the BIOS_2JFRF_WN64_2.8.0.EXE update package., current job execution time is: 0:00:24
- Message: Downloading the BIOS_2JFRF_WN64_2.8.0.EXE update package., current job execution time is: 0:00:27
- Message: Package successfully downloaded., current job execution time is: 0:00:31
- Message: Package successfully downloaded., current job execution time is: 0:00:33
- Message: Package successfully downloaded., current job execution time is: 0:00:38

- PASS, job ID JID_418172050541 successfully marked as scheduled, powering on or rebooting the server to apply the update

- WARNING, Current server power state is: On
- PASS, Command passed to gracefully power OFF server, code return is 204
- PASS, GET command passed to verify server is in OFF state
- PASS, Command passed to power ON server, code return is 204
- WARNING, JobStatus not completed, current status is: "Task successfully scheduled.", job execution time is "0:00:01"
- WARNING, JobStatus not completed, current status is: "Task successfully scheduled.", job execution time is "0:00:22"
- WARNING, JobStatus not completed, current status is: "Task successfully scheduled.", job execution time is "0:00:43"
- WARNING, JobStatus not completed, current status is: "Task successfully scheduled.", job execution time is "0:01:04"
- WARNING, JobStatus not completed, current status is: "Task successfully scheduled.", job execution time is "0:01:26"
- WARNING, JobStatus not completed, current status is: "Job in progress.", job execution time is "0:01:47"
- WARNING, JobStatus not completed, current status is: "Job in progress.", job execution time is "0:02:08"
- WARNING, JobStatus not completed, current status is: "Job in progress.", job execution time is "0:02:29"
- WARNING, JobStatus not completed, current status is: "Job in progress.", job execution time is "0:02:51"
- WARNING, JobStatus not completed, current status is: "Job in progress.", job execution time is "0:03:13"
- WARNING, JobStatus not completed, current status is: "Job in progress.", job execution time is "0:03:34"
- WARNING, JobStatus not completed, current status is: "Job in progress.", job execution time is "0:03:55"
- WARNING, JobStatus not completed, current status is: "Job in progress.", job execution time is "0:04:15"
- WARNING, JobStatus not completed, current status is: "Job in progress.", job execution time is "0:04:36"
- WARNING, JobStatus not completed, current status is: "Job in progress.", job execution time is "0:04:57"
- WARNING, JobStatus not completed, current status is: "Job in progress.", job execution time is "0:05:19"
- WARNING, JobStatus not completed, current status is: "Job in progress.", job execution time is "0:05:40"
- WARNING, JobStatus not completed, current status is: "Job in progress.", job execution time is "0:06:01"
- WARNING, JobStatus not completed, current status is: "Job in progress.", job execution time is "0:06:22"
- WARNING, JobStatus not completed, current status is: "Job in progress.", job execution time is "0:06:45"

- PASS, job ID JID_418172050541 successfully marked completed

- Final detailed job results -

@odata.type: #DellJob.v1_0_0.DellJob
JobState: Completed
Description: Job Instance
TargetSettingsURI: None
MessageArgs: []
CompletionTime: 2018-11-09T20:41:37
PercentComplete: 100
StartTime: TIME_NOW
MessageId: PR19
Message: Job completed successfully.
EndTime: TIME_NA
Id: JID_418172050541
JobType: FirmwareUpdate
Name: update:DCIM:INSTALLED#741__BIOS.Setup.1-1

- JOB ID JID_418172050541 completed in 0:07:10

C:\Python27>DeviceFirmwareSimpleUpdateREDFISH.py -ip 192.168.0.120 -u root -p calvin -g y

- WARNING, current devices detected with firmware version and updateable status -

Device Name: Power Supply.Slot.1, Firmware Version: 00.10.37, Updatable: True
Device Name: BP13G+ 0:1, Firmware Version: 2.25, Updatable: True
Device Name: PERC H730 Mini, Firmware Version: 25.5.5.0005, Updatable: True
Device Name: OS COLLECTOR 1.1, OSC_1.1, A00, Firmware Version: OSC_1.1, Updatable: True
Device Name: Disk 5 in Backplane 1 of Integrated RAID Controller 1, Firmware Version: VT31, Updatable: True
**Device Name: BIOS, Firmware Version: 2.8.0, Updatable: True**
Device Name: Dell OS Driver Pack, 17.08.10, A00, Firmware Version: 17.08.10, Updatable: True
Device Name: Integrated Dell Remote Access Controller, Firmware Version: 2.60.60.60, Updatable: True
Device Name: Diagnostics, Firmware Version: 0, Updatable: True
Device Name: QLogic 577xx/578xx 10 Gb Ethernet BCM57810 - 00:0A:F7:5D:7A:72, Firmware Version: 14.04.18, Updatable: True
Device Name: Broadcom Gigabit Ethernet BCM5720 - 44:A8:42:46:9C:2B, Firmware Version: 7.10.64, Updatable: True
Device Name: System CPLD, Firmware Version: 1.0.1, Updatable: True
Device Name: Lifecycle Controller, Firmware Version: 2.60.60.60, Updatable: False

C:\Python27>

**Comment by tyagian** [comment]
oh! it updates all of them? It seems like `yum upgrade`

**Comment by texroemer** [comment]
The RACADM repo script i gave you will update any device which detects a firmware version on the server from the repository.

DeviceFirmwareSimpleUpdateREDFISH.py script will just update one device at a time but it can be modified to update multiple devices as needed. The example i posted using this script is only updating the BIOS firmware. Before and after running the script, i pulled the firmware of all devices but just wanted to highlight in bold text the BIOS version did change after the update.

**Comment by tyagian** [comment]
so I am testing RepositoryUpdateRACADM.py script but how did you find catalog_filename for .ini file?
Also, my idrac servers are using https not http with ipv6

**Comment by tyagian** [comment]
can I use current directory as repo_uri_path?

**Comment by texroemer** [comment]
For the repo catalog filename, iDRAC code will look for one of the 2 default catalog filenames which are "Catalog.xml" or "Catalog.xml.gz". If the catalog file is one of these names, you can either pass it in or leave this parameter field empty. If you decide to change the name of the catalog file to a custom name, then its mandatory you pass in this name. 

For the Dell repository, its using "Catalog.xml.gz" which is a default catalog file name. When the repository is generated using Dell Repository Manager utility, it will generate a "Catalog.xml" file for you when you want to save the repository. Due to how many platforms the Dell repository is using, we zipped the catalog file. 

Repository update only supports network shares so local directories are not supported. If you want to use your current directory, convert it to one of the supported network shares and make sure it contains the firmware Dell Update packages (Windows .exe only supported) along with the Catalog.xml file.  You will need to use Dell Repository Manager to generate the Catalog.xml file.

**Comment by aviv12825** [comment]
Hi, 
Maybe this have been answered before... but Im trying to use the DeviceFirmwareSimpleUpdateREDFISH.py script and getting the following error: 
C:\Python36>DeviceFirmwareSimpleUpdateREDFISH.py -ip 10.0.0.60 -u root -p calvin
 -l C:\Python27\master_scripts_modified -f iDRAC-with-Lifecycle-Controller_Firmw
are_K877V_WN64_3.21.23.22_A00.EXE

- WARNING, downloading "iDRAC-with-Lifecycle-Controller_Firmware_K877V_WN64_3.21
.23.22_A00.EXE" image, this may take a few minutes depending on the size of the
image
Traceback (most recent call last):
  File "C:\Python36\DeviceFirmwareSimpleUpdateREDFISH.py", line 273, in <module>

    download_image_payload()
  File "C:\Python36\DeviceFirmwareSimpleUpdateREDFISH.py", line 77, in download_
image_payload
    http_push_uri = data[u'HttpPushUri']
KeyError: 'HttpPushUri'

Can anyone exaplin whats wrong here ?
**using iDrac9 with 3.17.17.17 fw
Thanks
Aviv

**Comment by texroemer** [comment]
Hi @aviv12825 

3.17 did not have support for HttpPushUri with SimpleUpdate. You will need to use either iDRAC GUI or RACADM to update the iDRAC FW to 3.21. Then try the script again which will now pass. 

Also we just posted 3.30 version on 3/4 which is the latest iDRAC version. This firmware version has added lots of new features to Redfish (OEM and DTMF). We are currently working on the docs and scripts for these new features and will have them posted in the next week. 

Thanks

**Comment by aviv12825** [comment]
Hi @texroemer  - thank you for the replay! :)
What about idrac8 2.60.60.60 - is it support SimpleUpdate ? 
I assume the is asnwer is NO - any workaround for this ? 
Thank you.

**Comment by texroemer** [comment]
@aviv12825 

2.60 iDRAC does support SimpleUpdate. Run a GET on URI "redfish/v1/UpdateService", you will see SimpleUpdate action along with HttpPushUri listed.

Thanks

**Comment by tyagian** [comment]
I came to know about Dell repo manager now and understood what you were talking about. 
In the first script at the top, RepositoryUpdateRACADM.py 
We use the source file to get all user/pass info. If I've repo manager installed on the same system from which I am running this script, it's a vbox ubuntu image with a user/pass. Does cifs_username= and
cifs_password=  will be my ubuntu VM user/pass? 
"repository_update_RACADM.ini"
```
[Parameters]
idrac_ip=192.168.0.120
idrac_username=root
idrac_password=calvin
repo_uri_path=143.166.135.76
protocol_type=HTTP
apply_update=TRUE
catalog_filename=Catalog.xml.gz
cifs_username=
cifs_password=
```
When I am trying to run this script, I get error:

$python RepositoryUpdateRACADM.py

- WARNING, checking if remote RACADM is installed first before starting the script
/bin/sh: 1: racadm: not found
- FAIL, remote RACADM is not installed. This must be installed to execute the script
```
but racadm is installed on it and I get 
/admin1-> racadm getversion
 Bios Version                     = 1.4.9

 iDRAC Version                    = 3.34.34.34

 Lifecycle Controller Version     = 3.34.34.34

 IDSDM Version                    = NA

on r740xd server. I want to use script to use Dell Repo manager.

**Comment by texroemer** [comment]
Hi @tyagian 

You need to have remote RACADM installed on the system you are running the script from. SSH to the iDRAC and running RACADM command is local RACADM. 

Remote RACADM is available to download from Dell Support Site.

Example link for R740xd:

https://www.dell.com/support/home/us/en/04/drivers/driversdetails?driverid=g3ndf&oscode=rh60&productcode=poweredge-r740xd

Thanks

**Comment by tyagian** [comment]
so my local system is ubuntu. 
At https://www.dell.com/support/home/us/en/04/drivers/driversdetails?driverid=g3ndf&oscode=rh60&productcode=poweredge-r740xd 
in Supported Operating Systems, it only RHEL/SuSe but has a link
Looking for a different OS? "View the list of Dell supported operating systems" which has ubuntu listed but don't know how to get installation file for it? Mentioned tar.gz only has .rpm files

**Comment by tyagian** [comment]
So when I am using RepositoryUpdateRACADM.py, it expects dell repo manager on NFS and idrac try to reach there. What if I am installing dell repo manager
and python script from the same system? It shouldn't req cfs IP, user password?
Because when I am using DeviceFirmwareSimpleUpdateREDFISH.py, it doesn't ask req idrac to ask for NFS and other credentials. 

Is it possible for a script like DeviceFirmwareSimpleUpdateREDFISH.py to work with dell repo manager? My idrac job failing to reach dell repo manager but it works when I have firmware on the same server and using DeviceFirmwareSimpleUpdateREDFISH.py

**Comment by texroemer** [comment]
Ubuntu is currently an OS we official support for RACADM but I did a Google search and found multiple workaround articles about installing RACADM on Ubuntu. Can you try this out and see if it works?

https://www.gocit.vn/bai-viet/install-racadm-on-ubuntu-debian-for-dell-idrac/

For the RACADM repo update script, it supports NFS, CIFS, HTTP, TFTP or FTP for network protocol where the repository is located. The INI file example i sent you uses the Dell HTTP repository which has the latest DUPs for your server. Were you not able to access this repository with the script or are you wanting to create your own custom repository?
