### ISSUE TITLE
Create and Delete iDRAC Users

### ISSUE THREAD

**Issue by ma-husyk** [dell/iDRAC-Redfish-Scripting#40]
Hy Texas, 

is it possible to extend the  Set-IdracUserPasswordREDFISH.psm1 to the functionality of 
CreateIdracUserPasswordREDFISH.py

I got the code from JSON and brought it to Powershell ;)

$JsonBody = @{"Enabled"= $True ; 'UserName'= $idrac_newusername; 'Password'= $idrac_new_password; 'RoleId'= "Administrator"; 'Description'= "Admin"} | ConvertTo-Json -Compress

But I also like to delete a user not only to disable it as you did in the Python.

$JsonBody = @{"Enabled"= $False ; 'RoleId'= "None"; 'Description'= ""; 'UserName'= "" ; 'Password'= "" } | ConvertTo-Json -Compress

This does the Trick but it throws an ugly Error in the end,  even if it succeeds in deleting Username and Password.

[{"Message":"The specified value is not allowed to be configured if the user name \\nor password is 
blank.","

any advice how to make it right.

**Comment by texroemer** [comment]
@ma-husyk 

Powershell cmdlet "Invoke-CreateIdracUserPasswordREDFISH.psm1" already exists on GitHub which behavior is the same as Python script "CreateIdracUserPasswordREDFISH.py". 

Let me know if you have any issues executing it.

**Comment by ma-husyk** [comment]
@texroemer

The cmdlet  "Invoke-CreateIdracUserPasswordREDFISH.psm1" gives an ERROR

Invoke-WebRequest : Access Error: 400 -- Bad Request
Bad request parameters
At D:\DELL_Redfish\Redfish
PowerShell\Invoke-CreateIdracUserPasswordREDFISH\Invoke-CreateIdracUserPasswordREDFISH.psm1:162 char:12
+ $result1 = Invoke-WebRequest -Uri $u1 -Credential $credential -Method ...
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



I did some digging and found 

LINE 154:
$JsonBody = @{UserName = $idrac_new_username; Password= $idrac_new_password; RoleId = $idrac_user_privilege; Enabled = $enable_status} | ConvertTo-Json

I changed it to 
$JsonBody = @{UserName = $idrac_new_username; Password= $idrac_new_password; RoleId = $idrac_user_privilege; Enabled = $enable_status} | ConvertTo-Json -Compress


Now adding a user is working for me.

Deleteing a User also had to be changed, but this now works of course without Error :)

212
$JsonBody = @{Enabled = $false; RoleId = "None"} | ConvertTo-Json -compress
217
$JsonBody = @{UserName = ""} | ConvertTo-Json -compress

In the end I added to every ConvertTo-Json  a -compress and now it works.


I use iDRAC8 with 2.60.60.60
PS 5.1 on W2016

**Comment by ma-husyk** [comment]
thx
