### ISSUE TITLE
Problem to upload files Idrac7/8

### ISSUE THREAD

**Issue by nildoadao** [dell/iDRAC-Redfish-Scripting#41]
Hi,

I was testing the new Idrac7/8 (2.60.60.60) firmware with support to UpdateService with the client that I developed, but it was not working, after some research I saw that in Idrac 7/8 the server doesn't understand post requests with the boundary in quotes 

ex:
content-type: multipart/form-data; boundary="--------------------------906062808661884025570449"

Requests library in python doesn't use quotes for boundary so it works fine when running the scripts that you made, but .NET HttpClient which is the library that I'm using to make request, put quotes in the boundary, so the server don't understand the request and throw me an 400 error.

I was able to find a workaround for this and get it to work with Idrac7/8, but since Idrac9 support this kind of request and the RFC says that is valid [https://tools.ietf.org/html/rfc2046#section-5.1.1](url), it would be nice to have this in Idrac7/8, that may avoid some compatibility problems in the future.

**Comment by texroemer** [comment]
@nildoadao 

I've escalated your issue to iDRAC Redfish development team to get this supported added in next iDRAC 7/8 release. Once i get a confirmation from the development team about adding support, i'll let you know.

Thanks

**Comment by nildoadao** [comment]
Hi @texroemer  

Great ! looking forward to the next version.

Thanks

**Comment by texroemer** [comment]
@nildoadao 

I got confirmation that support for this will be added in next iDRAC 7/8 release (2.70) which is scheduled to be available June 2019.
