### ISSUE TITLE
IDRAC 14gen switchconnection ID

### ISSUE THREAD

**Issue by adamliq** [dell/iDRAC-Redfish-Scripting#42]
Whilst IDRAC 14Gen web interface can view the switchconnection ID for a network adapter. I am unable to find within the Redfish API an ability to view the switchconnection ID for a network adapter.
Is this possible within redfish.

**Comment by texroemer** [comment]
Hi @adamliq 

This OEM property is currently not supported in Redfish but Dell is looking into adding more OEM properties for future iDRAC releases. For now, you can only get this property information using either iDRAC GUI, RACADM or WSMAN. 

RACADM command example is "racadm switchconnection view".

**Comment by texroemer** [comment]
@adamliq 

Wanted to give you an update. Redfish support for switch connection information will be coming in next 14G iDRAC9 release 3.30 which is scheduled to be released March 2019.

**Comment by zaiguiw** [comment]
> Redfish support for switch connection information will be coming in next 14G iDRAC9 release 3.30 which is scheduled to be released March 2019

Did the release happen?

**Comment by texroemer** [comment]
Hi @zaiguiw 

Yes this is now supported by Redfish and script is available on GitHub.

https://github.com/dell/iDRAC-Redfish-Scripting/blob/master/Redfish%20Python/DellSwitchConnectionCollectionREDFISH.py

Thanks
Tex

**Comment by zaiguiw** [comment]
Thanks Texas! Let me look into it.

**Comment by zaiguiw** [comment]
I can see the switch ID, port ID, etc, but not seeing the switch Names...
        {
            "Id": "NIC.Integrated.1-1-1",
            "SwitchConnectionID": "5c:17:83:30:fb:1c",
            "SwitchPortConnectionID": "Ethernet32"
        },
Is the switch name something the idrac does not parse properly? My networking guy is saying that they do send the hostname info through LLDP.

**Comment by texroemer** [comment]
Hi @zaiguiw 

iDRAC currently does not supporting returning the switch name but let me escalate to iDRAC teams internally, see if there are any future plans to add this support. 

Thanks
Tex

**Comment by zaiguiw** [comment]
Thank you @texroemer. 
I hope there'll be a straightforward fix;-)

**Comment by zaiguiw** [comment]
This whitepapaer seems to provide some details on what LLDP info is available to this API feature:
https://downloads.dell.com/manuals/all-products/esuprt_solutions_int/esuprt_solutions_int_solutions_resources/dell-management-solution-resources_White-Papers16_en-us.pdf

On page #6, it talks about:
 Switch connection ID - Chassis Identifier – this corresponds to a unique identifier for the switch
(For example, the switch MAC address)

it's not clear whether the "Switch connection ID" can only be a mac address. The example in the diagram actually uses "Switch1", "switch2" etc. There is definitely hope there...
