### ISSUE TITLE
Memory and Update Redfish

### ISSUE THREAD

**Issue by vaidyasaurabh08** [dell/iDRAC-Redfish-Scripting#43]
Hi,
I am consuming the redfish api on a dell gen 13.
My server is currently at redfish v1.0.2
I want to access individual DIMM information using /systems/systems.Embedded.1/Memory. Right now, I can just see the Memory Summary in /systems/systems.Embedded.1/. I am guessing the 1.0.2 dosent support /Memory path. 

So my question is -> 
1) Is there a resource which I could find which tells me what all paths are supported in what version.

2) I am also willing to upgrade redfish to 1.6 which is the standard DMTF specifies. So how do I upgrade the redfish version on my dell without touching any other firmware or software on the server.

**Comment by texroemer** [comment]
@vaidyasaurabh08 

On latest iDRAC version 2.60 for 13G servers, if you run a GET on URI "redfish/v1/Systems/System.Embedded.1/Memory", you should see URIs for each DIMM installed which you can run a GET on each of these URI to see detailed DIMM information.

Example of running GET on URI "redfish/v1/Systems/System.Embedded.1/Memory":

@odata.context | "/redfish/v1/$metadata#MemoryCollection.MemoryCollection"
-- | --
@odata.id | "/redfish/v1/Systems/System.Embedded.1/Memory"
@odata.type | "#MemoryCollection.MemoryCollection"
Description | "Collection of memory devices for this system"
Members |  
0 |  
@odata.id | "/redfish/v1/Systems/System.Embedded.1/Memory/iDRAC.Embedded.1%23DIMMSLOTA1"
1 |  
@odata.id | "/redfish/v1/Systems/System.Embedded.1/Memory/iDRAC.Embedded.1%23DIMMSLOTB1"
Members@odata.count | 2
Name | "Memory Devices Collection"

For version of Redfish iDRAC uses, there is no way to only update Redfish. Redfish support is added in the iDRAC firmware itself and each iDRAC version that gets posted on Dell support site, more Redfish support is being added. To see what Redfish schema versions are supported in the iDRAC version you have installed, run a GET on URI "redfish/v1/JSONSchemas".

**Comment by vaidyasaurabh08** [comment]
Hi @texroemer,

Thank you very much for your reply. 
I tried the uri you specified /Systems/System.Embedded.1/Memory
on a R740xd 14 gen with idraac firmware version 3.15.147.15
I got the same error of no resource not found.

Can you please advise me on this. I know I an not putting in the path incorrect as it works for all other things.

**Comment by vaidyasaurabh08** [comment]
Update even the above server is running

**Comment by texroemer** [comment]
On 14G server, did you run GET on this URI "https://"your iDRAC ip"/redfish/v1/Systems/System.Embedded.1/Memory" and it didn't work? 3.21 is the latest firmware version for 14G, can you try this version if you are still seeing the error?

**Comment by vaidyasaurabh08** [comment]
@texroemer
I was wondering if I hardcode the urls like this from getLcLog example

https://%s/redfish/v1/Managers/iDRAC.Embedded.1/Logs/Lclog?$skip=%s'

Will such hardcoding work for any redfish version and json schema... as in will the new redfish versions and jsonschemas change old hypermedias or will they be backward compatible.

Also I see in the url the path after the manager is Vendor specific, IDRAC in our example.
So will dell keep this as constant itrespective of redfish version??

Thanks

**Comment by texroemer** [comment]
@vaidyasaurabh08 

Yes, if you hard code that URI, it will be supported for backwards compatibility. 

Correct, this is a Dell OEM extension which the iDRAC firwmare version exposes to Redfish. It's not tied to the Redfish schema version so it will be constant.

Thanks
