### ISSUE TITLE
Export Config Local&Network

### ISSUE THREAD

**Issue by ma-husyk** [dell/iDRAC-Redfish-Scripting#45]
Hy Texas, 

why did you make to different versions?

Set-ExportImportServerConfigurationProfileNetworkShareREDFISH
Set-ExportServerConfigurationProfileLocalREDFISH

I realy like to get the ExportUse options also in the Local Version as I need this more often while testing stuff.

- ExportUse (Supported values: Default, Clone and Replace) OPTIONAL for export only. If not passed in, value will be "Default" used.

I did change it for testing, but of course it will be better we can use it out of the box.

$ExportUse = "Clone"

$share_info=@{"ExportFormat"=$ExportFormat;"ExportUse"=$ExportUse;"ShareParameters"=@{"Target"=$Target}}

Thx

**Comment by texroemer** [comment]
@ma-husyk 

Thanks for the suggestion, i updated the cmdlet "Set-ExportServerConfigurationProfileLocalREDFISH" on GitHub and it now supports ExportUse as an argument.

**Comment by ma-husyk** [comment]
thx
