### ISSUE TITLE
Python Set Next Onetime boot device doesn't work

### ISSUE THREAD

**Issue by snecklifter** [dell/iDRAC-Redfish-Scripting#46]
I can list the current devices but am unable to set the next boot device, no error.

Using curl works fine with PATCH.

This is on RHEL 7.6

**Comment by texroemer** [comment]
Hi @snecklifter 

Can you tell me which iDRAC version you are on and also can you copy the terminal output of running the python script? I just tried the script on RHEL 7 and was able to set onetime boot with no issues. This is was on a R740 with 3.21 iDRAC version.

[root@localhost opt]# ./SetNextOneTimeBootDeviceREDFISH.py -ip 100.65.84.100 -u root -p ca
lvin -o None -r n

- PASS, PATCH command passed to set next boot onetime boot device to: "None"
- WARNING, no reboot selected for -r argument. Onetime boot will be applied on next manaul server reboot
[root@localhost opt]# ./SetNextOneTimeBootDeviceREDFISH.py -ip 192.168.0.120 -u root -p ca
lvin -c y

-Supported values for next server reboot, one time boot:

None
Pxe
Floppy
Cd
Hdd
BiosSetup
Utilities
UefiTarget
SDCard
UefiHttp

- Current next reboot, one time boot setting is: **None**
[root@localhost opt]# ./SetNextOneTimeBootDeviceREDFISH.py -ip 192.168.0.120 -u root -p ca
lvin -o Pxe -r n

- PASS, PATCH command passed to set next boot onetime boot device to: "Pxe"
- WARNING, no reboot selected for -r argument. Onetime boot will be applied on next manaul server reboot
[root@localhost opt]# ./SetNextOneTimeBootDeviceREDFISH.py -ip 192.168.0.120 -u root -p ca
lvin -c y

-Supported values for next server reboot, one time boot:

None
Pxe
Floppy
Cd
Hdd
BiosSetup
Utilities
UefiTarget
SDCard
UefiHttp

- Current next reboot, one time boot setting is: **Pxe**
[root@localhost opt]#

**Comment by snecklifter** [comment]
Hi @texroemer 

Thanks for the response - so it looks like -r is mandatory?

This could be the problem as I wasn't passing this as didn't want to reboot. If this is the case, perhaps add something to catch this?

**Comment by texroemer** [comment]
Yes, if you are using -o argument to set the next onetime boot device, you must also pass in -r argument for rebooting the server.

I already made changes to the script to catch this condition and error correctly. Thanks for pointing this out.

C:\Python27>SetNextOneTimeBootDeviceREDFISH.py -ip 192.168.0.120 -u root -p calvin -o None

- FAIL, either missing or invalid parameter(s) passed in. If needed, see script help text for supported parameters and script examples

C:\Python27>SetNextOneTimeBootDeviceREDFISH.py -ip 192.168.0.120 -u root -p calvin -o None -r n

- PASS, PATCH command passed to set next boot onetime boot device to: "None"
- WARNING, no reboot selected for -r argument. Onetime boot will be applied on next manual server reboot

**Comment by snecklifter** [comment]
@texroemer thank you, much appreciated!
