### ISSUE TITLE
Invoke-SecureEraseDeviceREDFISH:   Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by mkanet** [dell/iDRAC-Redfish-Scripting#47]
The function Ignore-SSLCertificates seems to be ignored when I use Invoke-SecureEraseDeviceREDFISH.  I'm getting the error below on my workstation.  Any ideas how to get around this?

Invoke-WebRequest : The request was aborted: Could not create SSL/TLS secure channel.

**Comment by texroemer** [comment]
Hi @mkanet 

The system you are running the cmdlet from, what version of TLS does it support? Its recommended to use TLS 1.1 or 1.2 due to security issues. 

Thanks

**Comment by mkanet** [comment]
Thanks for the quick reply.

I'm not certain.  However, the below command doesnt seem to make any difference, even after restarting PowerShell.  I've also tried adding TLS 1.1 as well.  Is there a more reliable way to add support for TLS12 in PowerShell as the default?  Thanks again.

[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12;

**Comment by texroemer** [comment]
In the cmdlet, can you change:

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::TLS12

to:

[Net.ServicePointManager]::SecurityProtocol = "TLS12, TLS11, TLS"

Then relaunch Powershell session and see if it works? If not could be an issue with SSL. I've also been trying different settings on my end and been unable to reproduce the issue you are seeing.

Thanks
