### ISSUE TITLE
License View

### ISSUE THREAD

**Issue by kgrvamsi** [dell/iDRAC-Redfish-Scripting#48]
Is there any API to view the IDRAC license 

example command:
```
racadm license view
````

**Comment by texroemer** [comment]
Hi @kgrvamsi 

With 3.30 iDRAC9 version which was just posted on 3/4, we added OEM extensions to get, export, import and delete iDRAC licenses. 

For viewing iDRAC licenses installed, run a GET on URI "redfish/v1/Dell/Managers/iDRAC.Embedded.1/DellLicenseCollection".

For export, import, delete actions and URIs, run a GET on URI "redfish/v1/Dell/Managers/iDRAC.Embedded.1/DellLicenseManagementService".

Thanks

**Comment by kgrvamsi** [comment]
Thanks @texroemer
