### ISSUE TITLE
Redfish tree structure - DELL 

### ISSUE THREAD

**Issue by aviv12825** [dell/iDRAC-Redfish-Scripting#49]
Hi All, 

Maybe this one already been answered in the past - sorry for that, but maybe there is a location or link that show \ explained in details the Redfish tree structure (from Dell point of view of course...) ...

Please **dont** share this link : https://www.dell.com/support/article/us/en/19/sln310624/redfish?lang=en

Thank you for the help.

**Comment by texroemer** [comment]
Hi @aviv12825 

Dell currently doesn't have a document which explains the Redfish tree structure specific to OEM. The Redfish API and other DTMF docs will explain the overall Redfish tree structure and how OEM extensions can be supported. 

For information on the OEM extensions, refer to the Dell Redfish API guide which will show you root URIs along with any sub URIs it supports.

Thanks
