### ISSUE TITLE
how to get host dhcp ip from iDRAC?

### ISSUE THREAD

**Issue by simonfangyingzhang** [dell/iDRAC-Redfish-Scripting#5]
Hi Guru,

supposing I have Dell PE host and let it boot up such as from Linux or VMWare vSphere iso, it will have a dhcp ip, 

may from iDRAC (is there a powershell way?) I can know this ip? thanks

**Comment by texroemer** [comment]
Hi and sorry for the late reply. Currently iDRAC doesn't support getting OS IPs which are configured. iDRAC currently only supports getting OS hostname / OS name and OS version.

**Comment by simonfangyingzhang** [comment]
never mind :), os hostname, do you mean such as dhcp host name? please let me know how to get it, thanks

**Comment by texroemer** [comment]
OS hostname means the name that the OS assigns for the install. Example, installed Windows Server 2012, the host name assigned is WIN-JUDKML7BENS.

So it does look like in latest iDRAC releases for iDRAC 8 2.52 and iDRAC 9 3.15, support has been added where you can get the OS IP information using Redfish but you need iSM (iDRAC Service Module) installed on the operating system to get this information (You can download latest iSM from Dell support site under Drivers and Downloads / System Management for your server model). If iSM is not running on the OS, this information will not be available from the iDRAC. Once you install iSM in the OS and the service is running, using Redfish you run GET on URI "redfish/v1/Systems/System.Embedded.1/EthernetInterfaces" which will return ports detected by the OS with network information. You will then take one of the ports and append that to the URI to get specific information for that network port. Example: run GET on URI "redfish/v1/Systems/System.Embedded.1/EthernetInterfaces/iDRAC.Embedded.1%23ServiceModule.1%23OSLogicalNetwork.1" will get information only for port 1.

I currently don't have Redfish scripts created for this workflow but will work on one and get it posted , will let you know when available.

**Comment by texroemer** [comment]
Python script has been uploaded "GetOSNetworkInformationREDFISH.py". Examples below show executing the script.


C:\Python27>GetOSNetworkInformationREDFISH.py -ip 192.168.0.120 -u root -p calvin -g y

- Supported host network devices detected to get OS network information -

iDRAC.Embedded.1%23ServiceModule.1%23OSLogicalNetwork.1
iDRAC.Embedded.1%23ServiceModule.1%23OSLogicalNetwork.2

C:\Python27>GetOSNetworkInformationREDFISH.py -ip 192.168.0.120 -u root -p calvin -i iDRAC.Embedded.1%23ServiceModule.1%23OSLogicalNetwork.1 -a IPv4Addresses

- Property "IPv4Addresses" information for network device iDRAC.Embedded.1%23ServiceModule.1%23OSLogicalNetwork.1 -

IPv4Addresses: [{u'SubnetMask': u'255.255.255.0', u'AddressOrigin': u'DHCP', u'Gateway': u'192.168.0.254', u'Address': u'192.168.0.130'}]

C:\Python27>

**Comment by simonfangyingzhang** [comment]
thank you for your support, really appericate! sadly my iDRAC not latest and can not support rest api, will try other way

thanks, have a good day!
