### ISSUE TITLE
DeviceFirmwareSimpleUpdateREDFISH error in exe upload

### ISSUE THREAD

**Issue by tyagian** [dell/iDRAC-Redfish-Scripting#51]
With -g option, it works fine and sharing all firmware which can be upgraded. I am using it on 
PowerEdge R740xd.
With -l option, I am getting below error: 

```
- WARNING, downloading "BIOS_YJXXX_WN64_1.6.13.EXE" image, this may take a few minutes depending on the size of the image
Traceback (most recent call last):
  File "server_upgrade.py", line 249, in <module>
    download_image_payload()
  File "server_upgrade.py", line 57, in download_image_payload
    http_push_uri = data[u'HttpPushUri']
KeyError: u'HttpPushUri'
```
Any hints on how to fix it?

**Comment by nildoadao** [comment]
Hi @tyagian 

I think this is the same problem described in #39, depending on the version, Idrac9 don't have support to HttpPushUri

What version are you using ?

The script should work for version 3.21 or higher

**Comment by texroemer** [comment]
Hi @tyagian 

What @nildoadao stated is correct. HttpPushUri support was added to 3.18 and newer iDRAC versions. If you are at an older iDRAC version, you can use OEM script "DeviceFirmwareDellUpdateServiceREDFISH.py" to perform updates. 

Thanks

**Comment by tyagian** [comment]
Also, it's not suppose to work with ipv6 server IP?

**Comment by texroemer** [comment]
@tyagian 

Yes, IPv6 is supported with Redfish. Make sure to pass in the IPv6 address with "[]".

Example:

https://[1607:f2b1:f001:64:4ed9:8fff:fe11:c543]/redfish/v1/UpdateService/FirmwareInventory/

**Comment by tyagian** [comment]
Thanks. 
when you said "HttpPushUri support was added to 3.18", do you mean firmware version?
I have servers with idrac 8 and 9.

**Comment by texroemer** [comment]
@tyagian 

Yes, sorry about my wording, 3.18 is iDRAC 9 firmware version which added HttpPushUri. For iDRAC 7/8 firmware, 2.60 version added HttpPushUri support.

Thanks

**Comment by nildoadao** [comment]
Hi

@texroemer knows better, but I think since both DeviceFirmwareSimpleUpdateREDFISH.py and DeviceFirmwareDellUpdateService.py do an Http post to the same Uri "/redfish/v1/UpdateService/FirmwareInventory" you can use DeviceFirmwareDellUpdateService.py to update Servers with firmware version < 3.18 in Idrac 9.

**Comment by texroemer** [comment]
Correct, if your server is at iDRAC 9 < 3.18 version, you will need to use DeviceFirmwareDellUpdateService.py script to perform updates.
