### ISSUE TITLE
Storage Controller URI is wrong in GetStorageInventoryREDFISH

### ISSUE THREAD

**Issue by khayamgondal** [dell/iDRAC-Redfish-Scripting#52]
Line number 69. 'https://%s/redfish/v1/Systems/System.Embedded.1/Storage/Controllers/%s' should be changed to 'https://%s/redfish/v1/Systems/System.Embedded.1/Storage/%s'
i.e remove the 'Controller' word

**Comment by texroemer** [comment]
@khayamgondal 

Thanks for pointing this out. I updated the script with getting more detailed information for storage hardware and updated to use Storage and SimpleStorage URIs.

Thanks
