### ISSUE TITLE
Example of Redfish iDRAC using LDAP or AD authentication

### ISSUE THREAD

**Issue by rchola** [dell/iDRAC-Redfish-Scripting#55]
Hi,

Does anyone have some example of authentication using AD or LDAP instead local user/pass of iDRAC?

Regads,

RChola

**Comment by nildoadao** [comment]
Hi @rchola 

I think you can use the same scripts provide in this repository, the only diference will be the way you pass the username.

Lets say you have a domain called domain.dev

you can pass the username as domain.dev\username 

ex: python somescript.py -ip ip -u domain.dev\username -p password

**Comment by rchola** [comment]
Hi

Nldo,

Great. I test with you suggestion and work as well.

Thank you,

RChola

**Comment by nildoadao** [comment]
Great !
