### ISSUE TITLE
KWH Usage reader

### ISSUE THREAD

**Issue by OpaDopa** [dell/iDRAC-Redfish-Scripting#57]
Hello Guys,
Maby i am a bit blind, but i cant find the total kWh readings in the Redfish API.
So the: Cumulative Reading in the "System Overview dashboard"

Time | Since Mon oct 9999
Total Usage | xxx.780 kWh

Like to hear from you.

**Comment by texroemer** [comment]
Hi @OpaDopa 

Currently we don't support these OEM properties in Redfish but we are planning to add them in a future iDRAC release. Btw, you can get these properties using RACADM CLI, example:

_racadm>>get System.Power.EnergyConsumption.StarttimeStamp

racadm get System.Power.EnergyConsumption.StarttimeStamp
Wed Dec 31 18:00:01 2018
RAC1248: The RACADM "System.Power" group will be deprecated in a future release of iDRAC firmware.
         The group attributes will be migrated to "System.ServerPwr".

racadm>>get System.Power.EnergyConsumption

racadm get System.Power.EnergyConsumption
789.825 KWh | 2695673 Btu
RAC1248: The RACADM "System.Power" group will be deprecated in a future release of iDRAC firmware.
         The group attributes will be migrated to "System.ServerPwr"._

Thanks
