### ISSUE TITLE
What are the corresponding Redfish APIs for these operations in menu bar?

### ISSUE THREAD

**Issue by lxjbutterfly** [dell/iDRAC-Redfish-Scripting#59]
Hi, 
  I want make below manual operations automatically by redfish APIs, but I haven't found out all the corresponding redfish APIs, would you please give some suggestions?

virual media -> connect virual media
virual media -> map CD/DVD -> choose Live Image
next boot -> virtual CD/DVD/ISO
power -> reset system
For above operation in menu bar, are there corresponding redfish APIs for these operations?
For example:
virual media -> map CD/DVD -> choose Live Image ----- --
curl -X POST https://10.196.23.75/redfish/v1/Managers/iDRAC.Embedded.1/VirtualMedia/CD/Actions/VirtualMedia.InsertMedia -d '{"Image": "http://<web_server>/<iso_file>.iso"}' -H "Content-Type: application/json" -k -u root:calvin
What are the other Redfish APIs?

**Comment by texroemer** [comment]
Sorry for the late reply, refer to iDRAC 3.30 Redfish whitepaper 2.1 section which walks you through an example of attaching virtual media and performing one time boot to virtual media device.

https://downloads.dell.com/manuals/all-products/esuprt_software/esuprt_remote_ent_sys_mgmt/idrac9-lifecycle-controller-v3303030_white-papers10_en-us.pdf
