### ISSUE TITLE
Paths don't exist?

### ISSUE THREAD

**Issue by allywilson** [dell/iDRAC-Redfish-Scripting#6]
I'm trying to use some of these scripts, but a lot of the redfish paths don't appear to exist on any of my iDRACs (v2.50.50, redfish v1.0.2)?

"failed: Request URI: /redfish/v1/UpdateService is invalid"

**Comment by tehbluemuppetz** [comment]
I'm guessing that's due to the server version. 12G? I may be able to check tomorrow. In the meantime, please access https://<idrac ip>/redfish/v1/ and see what URI's are listed. Not all features are available on older hardware afaik.

**Comment by allywilson** [comment]
13G, mostly R730's:


```
{
  "@odata.context": "/redfish/v1/$metadata#ServiceRoot.ServiceRoot",
  "@odata.id": "/redfish/v1",
  "@odata.type": "#ServiceRoot.v1_0_2.ServiceRoot",
  "AccountService": {
    "@odata.id": "/redfish/v1/Managers/iDRAC.Embedded.1/AccountService"
  },
  "Chassis": {
    "@odata.id": "/redfish/v1/Chassis"
  },
  "Description": "Root Service",
  "EventService": {
    "@odata.id": "/redfish/v1/EventService"
  },
  "Id": "RootService",
  "JsonSchemas": {
    "@odata.id": "/redfish/v1/JSONSchemas"
  },
  "Links": {
    "Sessions": {
      "@odata.id": "/redfish/v1/Sessions"
    }
  },
  "Managers": {
    "@odata.id": "/redfish/v1/Managers"
  },
  "Name": "Root Service",
  "RedfishVersion": "1.0.2",
  "Registries": {
    "@odata.id": "/redfish/v1/Registries"
  },
  "SessionService": {
    "@odata.id": "/redfish/v1/SessionService"
  },
  "Systems": {
    "@odata.id": "/redfish/v1/Systems"
  },
  "Tasks": {
    "@odata.id": "/redfish/v1/TaskService"
  }
}
```

**Comment by tehbluemuppetz** [comment]
Thank you @allywilson . I can confirm that right now only 14G servers have the ability to update firmware using Redfish (/redfish/v1/UpdateService). This feature is likely to be added to previous server generations but I don't have a date.  

Apart from that a lot of the Redfish paths should be available also on 13G and older, but you'll likely come across some features that haven't yet been implemented (or that require 14G hardware).

**Comment by tehbluemuppetz** [comment]
@allywilson Actually, there is an alternative for using Redfish to update firmware on 12G and 13G servers. A firmware update can be initiated with Redfish by pushing an SCP (Server Configuration Profile) file to the iDRAC. This is described in the following whitepaper (page 29):
http://en.community.dell.com/techcenter/extras/m/white_papers/20443207

**Comment by allywilson** [comment]
Thank very much, I'll look into that, much appreciated.

I wonder if it's worth putting some compatibility checks into the scripts represented in this repo to mitigate further issues others may encounter as well?
