### ISSUE TITLE
InsertEjectVirtualMediaREDFISH.py failed

### ISSUE THREAD

**Issue by aviv12825** [dell/iDRAC-Redfish-Scripting#60]
Hi All, 

Idrac FW. 3.30.30.30 being used here. 
Trying to executed the below and getting an error - can someone explain why: 

InsertEjectVirtualMediaREDFISH.py -ip 10.0.0.57 -u root -p calvin -o 1 -d 1 -i http://127.0.0.1/linuxISO.iso

 - WARNING, insert(attached) "CD" virtual media device "http://127.0.0.1/linuxISO.iso"

- FAIL, POST command InsertMedia action failed, detailed error message: b'{"error":{"@Message.ExtendedInfo":[{"Message":"The requested operation cannot be completed because of an internal error.","MessageArgs":[],"MessageArgs@odata.count":0,"MessageId":"IDRAC.1.6.SYS446","RelatedProperties":[],"RelatedProperties@odata.count":0,"Resolution":"Retry the operation after a few minutes. If the issue persists, contact your service provider.","Severity":"Critical"},{"Message":"The request failed due to an internal service error.  The service is still operational.","MessageArgs":[],"MessageArgs@odata.count":0,"MessageId":"Base.1.2.InternalError","RelatedProperties":[],"RelatedProperties@odata.count":0,"Resolution":"Resubmit the request.  If the problem persists, consider resetting the service.","Severity":"Critical"}],"code":"Base.1.2.GeneralError","message":"A general error has occurred. See ExtendedInfo for more information"}}\n'

**Comment by texroemer** [comment]
Hi @aviv12825 

iDRAC seems to be in a bad state when internal error is being returned. Can you reset the iDRAC using RACADM (racadm racreset) or iDRAC GUI and once the iDRAC is back up and in ready state, try the Redfish command again?

Thanks

**Comment by aviv12825** [comment]
Try to reset the iDRAC using RACADM (racadm racreset) or iDRAC GUI and once the iDRAC is back up and in ready state as you mentioned and run the command again. same result.
also did warm and cold reboot. same result. (all Healthy for system and storage) .  any idea ?

**Comment by texroemer** [comment]
Can you execute "SetPowerStateREDFISH.py -ip <iDRAC ip> -u <iDRAC username> -p <iDRAC password> -r ForceRestart" to see if the server reboots. Want to verify if all POST commands are failing on the iDRAC or only the command to attach virtual media.

**Comment by aviv12825** [comment]
done what you have requested. 
see below: (it worked successfully) 
SetPowerStateREDFISH.py -ip 10.0.0.57 -u root -p calvin -r ForceRestart
- WARNING, setting new server power state to: ForceRestart
- PASS, status code 204 returned, server power state successfully set to "ForceRestart"

**Comment by texroemer** [comment]
Thanks for confirming this command works. We now know it's not an issue with executing POST commands but an issue with accessing the HTTP share. 

For the HTTP share you are using, is this a share that you setup on a web server? Not using iDRAC with Redfish, are you able to access the share with no issues? Issue seems to be the share doesn't have the correct permissions to allow iDRAC access to the ISO to mount it.

**Comment by aviv12825** [comment]
I have set up the http share using "pthyon command "python -m http.server 80".
The ISO have been placed in my folder \ local sever and I can see it without any issue once entering 127.0.0.1 in the browser. 
-see below: 
python -m http.server 80
Serving HTTP on 0.0.0.0 port 80 (http://0.0.0.0:80/) ...
127.0.0.1 - - [05/May/2019 21:02:06] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2019 21:02:14] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [06/May/2019 18:44:38] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [07/May/2019 16:02:41] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [07/May/2019 16:11:17] "GET / HTTP/1.1" 200 -

Any idea ?

**Comment by texroemer** [comment]
Are you sure your firewall is not blocking the port for HTTP server and also does the HTTP share have the correct permissions? I tested on HTTP share using Windows IIS and HTTP share using Linux Apache and no issues with attaching virtual media. 

Here is a screenshot example of the IIS HTTP share i setup and attached an ISO using Redfish.

![http_share_image](https://user-images.githubusercontent.com/30351677/57671070-c67cd900-75d7-11e9-9bec-d0dd4119555f.JPG)

**Comment by aviv12825** [comment]
I open port 80 on my windows firwall settings (inboud\outbound)
The folder is on sharing mode with permiisions to everyone\administartor.
also  -
I can run wget command for my http share. 

C:\localfileserver>wget http://127.0.0.1/linuxISO.iso
--17:26:55--  http://127.0.0.1:80/linuxISO.iso
           => `linuxISO.iso.1'
Connecting to 127.0.0.1:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 1,045,501,952 [application/octet-stream]

    0K -> .......... .......... .......... .......... .......... [  0%]
   50K -> .......... .......... .......... .......... .......... [  0%]
  100K -> .......... .......... .......... .......... .......... [  0%]

Any idea ?

**Comment by texroemer** [comment]
Thanks for confirming this. Since wget works, attach virtual media using Redfish should also work.

Can you check iDRAC sessions and make sure you don't have any virtual media already attached? You can use either iDRAC GUI Sessions page or "racadm getssninfo" command.

**Comment by aviv12825** [comment]
(10.0.0.103 is my local host ip) 

racadm -r 10.0.0.57 -u root -p calvin getssninfo 
Security Alert: Certificate is invalid - Certificate is not signed by Trusted Third Party
Continuing execution. Use -S option for racadm to stop execution on certificate-related errors.
SSNID Type              User                                          IP Address Login Date/Time
---------------------------------------------------------------------------
105   GUI               root                                          10.0.0.103 05/15/2019 02:04:24
115   RACADM            root                                          10.0.0.103 05/15/2019 02:14:09

**Comment by aviv12825** [comment]
I have created also IIS http share - there is something strange here:
I can acsses it with the browser and see the files, but once I donwload the iso file I get http error:
 HTTP Error 404.3 - Not Found which doesnt happen on other files. see pictures attached. 
![1](https://user-images.githubusercontent.com/29521767/57783319-9861db00-7736-11e9-8fa5-02343648a22e.JPG)
![2](https://user-images.githubusercontent.com/29521767/57783375-b0d1f580-7736-11e9-99a6-30bc1f2ecf8b.JPG)

**Comment by texroemer** [comment]
I've never seen that error before with my IIS HTTP share but just googled it, seems to be a common issue which can be resolved.

Does Redfish command still fail with the IIS HTTP share you set up?

**Comment by lxjbutterfly** [comment]
> Hi All,
> Idrac FW. 3.30.30.30 being used here.
> Trying to executed the below and getting an error - can someone explain why:
> InsertEjectVirtualMediaREDFISH.py -ip 10.0.0.57 -u root -p calvin -o 1 -d 1 -i http://127.0.0.1/linuxISO.iso
> 
> 
> WARNING, insert(attached) "CD" virtual media device "http://127.0.0.1/linuxISO.iso"
> 
> 
> FAIL, POST command InsertMedia action failed, detailed error message: b'{"error":{"@Message.ExtendedInfo":[{"Message":"The requested operation cannot be completed because of an internal error.","MessageArgs":[],"MessageArgs@odata.count":0,"MessageId":"IDRAC.1.6.SYS446","RelatedProperties":[],"RelatedProperties@odata.count":0,"Resolution":"Retry the operation after a few minutes. If the issue persists, contact your service provider.","Severity":"Critical"},{"Message":"The request failed due to an internal service error.  The service is still operational.","MessageArgs":[],"MessageArgs@odata.count":0,"MessageId":"Base.1.2.InternalError","RelatedProperties":[],"RelatedProperties@odata.count":0,"Resolution":"Resubmit the request.  If the problem persists, consider resetting the service.","Severity":"Critical"}],"code":"Base.1.2.GeneralError","message":"A general error has occurred. See ExtendedInfo for more information"}}\n'

I also meet the similar issue, what are you going on with it?
Has it been resolved? If yes, would you please share some experience?
Thanks

**Comment by aviv12825** [comment]
I have resolved the http 404.3 error BUT still getting the same error while trying to use this script:
InsertEjectVirtualMediaREDFISH.py -ip 10.0.0.57 -u root -p calvin -o 1 -d 1 -i http://10.0.0.103\ISO\linuxISO.iso

 - WARNING, insert(attached) "CD" virtual media device "http://10.0.0.103\ISO\linuxISO.iso"

- FAIL, POST command InsertMedia action failed, detailed error message: b'{"error":{"@Message.ExtendedInfo":[{"Message":"The requested operation cannot be completed because of an internal error.","MessageArgs":[],"MessageArgs@odata.count":0,"MessageId":"IDRAC.1.6.SYS446","RelatedProperties":[],"RelatedProperties@odata.count":0,"Resolution":"Retry the operation after a few minutes. If the issue persists, contact your service provider.","Severity":"Critical"},{"Message":"The request failed due to an internal service error.  The service is still operational.","MessageArgs":[],"MessageArgs@odata.count":0,"MessageId":"Base.1.2.InternalError","RelatedProperties":[],"RelatedProperties@odata.count":0,"Resolution":"Resubmit the request.  If the problem persists, consider resetting the service.","Severity":"Critical"}],"code":"Base.1.2.GeneralError","message":"A general error has occurred. See ExtendedInfo for more information"}}\n'

**Comment by texroemer** [comment]
@aviv12825, @lxjbutterfly 

Can both of you execute this racadm command and send me the output.

"racadm get idrac.virtualmedia"

Thanks

**Comment by lxjbutterfly** [comment]
@texroemer 
1. 
![image](https://user-images.githubusercontent.com/50070028/57898163-8002d500-788a-11e9-968f-6719052d1192.png)
The corresponding response
![image](https://user-images.githubusercontent.com/50070028/57898218-a9bbfc00-788a-11e9-8b6f-8586c6308be4.png)

2.
![image](https://user-images.githubusercontent.com/50070028/57898240-c6583400-788a-11e9-96af-fc25ac5f52b7.png)

The corresponding response
![image](https://user-images.githubusercontent.com/50070028/57899035-fbb25100-788d-11e9-99f1-0f238d08c351.png)

3.
![image](https://user-images.githubusercontent.com/50070028/57899071-213f5a80-788e-11e9-87e5-d31f584767d2.png)

The corresponding response

![image](https://user-images.githubusercontent.com/50070028/57899097-3e742900-788e-11e9-83fc-be1c0033c068.png)

**Comment by lxjbutterfly** [comment]
> I have resolved the http 404.3 error BUT still getting the same error while trying to use this script:
> InsertEjectVirtualMediaREDFISH.py -ip 10.0.0.57 -u root -p calvin -o 1 -d 1 -i http://10.0.0.103\ISO\linuxISO.iso
> 
> 
> WARNING, insert(attached) "CD" virtual media device "http://10.0.0.103\ISO\linuxISO.iso"
> 
> 
> FAIL, POST command InsertMedia action failed, detailed error message: b'{"error":{"@Message.ExtendedInfo":[{"Message":"The requested operation cannot be completed because of an internal error.","MessageArgs":[],"MessageArgs@odata.count":0,"MessageId":"IDRAC.1.6.SYS446","RelatedProperties":[],"RelatedProperties@odata.count":0,"Resolution":"Retry the operation after a few minutes. If the issue persists, contact your service provider.","Severity":"Critical"},{"Message":"The request failed due to an internal service error.  The service is still operational.","MessageArgs":[],"MessageArgs@odata.count":0,"MessageId":"Base.1.2.InternalError","RelatedProperties":[],"RelatedProperties@odata.count":0,"Resolution":"Resubmit the request.  If the problem persists, consider resetting the service.","Severity":"Critical"}],"code":"Base.1.2.GeneralError","message":"A general error has occurred. See ExtendedInfo for more information"}}\n'

HI, @aviv12825 
Could you run "wget http://10.0.0.103\ISO\linuxISO.iso" succesfully?

**Comment by aviv12825** [comment]
I have send the racadm command u mentioned - the answer below:

racadm -r 10.0.0.57 -u root -p calvin get idrac.virtualmedia
Security Alert: Certificate is invalid - Certificate is not signed by Trusted Third Party
Continuing execution. Use -S option for racadm to stop execution on certificate-related errors.
[Key=idrac.Embedded.1#VirtualMedia.1]
#ActiveSessions=0
Attached=AutoAttach
BootOnce=Disabled
Enable=Enabled
EncryptEnable=Enabled
FloppyEmulation=Disabled
KeyEnable=Disabled
#MaxSessions=1

**Comment by texroemer** [comment]
@aviv12825 

Thanks for RACADM output and your virtual media settings are correct.

For HTTP, are you using default port of 80 or a different port? If using different port, can you pass in port number for the URI and try Redfish command again?

**Comment by aviv12825** [comment]
I belive I use port 80. 
How do I check this please ?
How can I pass in port number for the URI by Redfish command please ?
Thank you.
Aviv

**Comment by texroemer** [comment]
In IIS, you would check binding settings, in Apache you would check httpd.conf file.

Example of passing in the port number:

C:\>InsertEjectVirtualMediaREDFISH.py -ip 192.168.0.120 -u root -p calvin -o 1 -d 1 -i http://192.168.0.130:80/boot.iso

 - WARNING, insert(attached) "CD" virtual media device "http://192.168.0.130:80/boot.iso"

- PASS, POST command passed to successfully insert(attached) CD media
- PASS, GET command passed to verify CD media successfully inserted(attached)

**Comment by texroemer** [comment]
@aviv12825 @lxjbutterfly 

I forgot to mention if you have a virtual console session open, make sure the virtual media session is not attached. If the session is attached, trying to attach virtual media using Redfish will fail with internal error. 

Example of session not attached:

![image](https://user-images.githubusercontent.com/30351677/58104192-f9136c80-7ba9-11e9-94e1-427c2b8e8e5b.png)

Example of session attached which will cause Redfish attach virtual media to fail:

![image](https://user-images.githubusercontent.com/30351677/58104229-10525a00-7baa-11e9-8884-d82d62fde433.png)

**Comment by lxjbutterfly** [comment]
> @aviv12825 @lxjbutterfly
> I forgot to mention if you have a virtual console session open, make sure the virtual media session is not attached. If the session is attached, trying to attach virtual media using Redfish will fail with internal error.
> Example of session not attached:
> 
> Example of session attached which will cause Redfish attach virtual media to fail:

I just want to discuss this problem with you .

I'm working on make all these steps automatic.

Before trying to attach the ISO, I should make sure 
Pic. 1. 
![image](https://user-images.githubusercontent.com/50070028/58152463-373e8800-7c9f-11e9-908f-ad177d77c68b.png)
And not 
Pic. 2.
![image](https://user-images.githubusercontent.com/50070028/58152492-46253a80-7c9f-11e9-90e0-429df1f2dda7.png)

So questions
Q1: How to check the status of connection? Identify Pic. 1 or Pic. 2. 
       **What is the corresponding Redfish API to query?**

If it looks like Pic. 1, I will continue the attach operation.

If it looks like Pic. 2, 
  First, Roll back to Pic. 1, and **Q2: What is the corresponding Redfish API to "Disconnect Virtual Media"?**
  Second, continue to attach operation.

**Comment by aviv12825** [comment]
Now it works ! :-) 
But only after I added the IP addres in binding settings in IIS, otherwise it fails.

![3](https://user-images.githubusercontent.com/29521767/58155199-1fa1d800-7c7c-11e9-899f-63514195773b.JPG)

**Comment by texroemer** [comment]
@aviv12825 

Good to hear it's finally working :)

**Comment by lxjbutterfly** [comment]
> @aviv12825 @lxjbutterfly
> I forgot to mention if you have a virtual console session open, make sure the virtual media session is not attached. If the session is attached, trying to attach virtual media using Redfish will fail with internal error.
> Example of session not attached:
> Example of session attached which will cause Redfish attach virtual media to fail:
> 
> I just want to discuss this problem with you .
> I'm working on make all these steps automatic.
> Before trying to attach the ISO, I should make sure
> Pic. 1.
> 
> And not
> Pic. 2.
> 
> So questions
> Q1: How to check the status of connection? Identify Pic. 1 or Pic. 2.
> What is the corresponding Redfish API to query?
> If it looks like Pic. 1, I will continue the attach operation.
> If it looks like Pic. 2,
> First, Roll back to Pic. 1, and Q2: What is the corresponding Redfish API to "Disconnect Virtual Media"?
> Second, continue to attach operation.

@texroemer 
Would you please help to have a look at my above questions?

**Comment by texroemer** [comment]
@lxjbutterfly 

Sorry about the late reply, been out of office.

To verify if any virtual media sessions are open by the iDRAC, you will need to execute racadm command "racadm getssninfo". This will report any open sessions on the iDRAC. Currently with Redfish, iDRAC does support DMTF "redfish/v1/Sessions" URI which will return the same iDRAC sessions but the DMTF standard doesn't have support "Type" property. Without this property, you will not be able to tell which session is which from Redfish so this is why you need to use RACADM. Also DTMF just added support for "Type" property in the latest 2019 spec which we will add support for this new spec in a future release.

To delete the virtual console session, you can either use RACADM command "racadm closessn" command or Redfish DELETE command passing in the URI of the virtual media session.

Example using RACADM:

C:\Python27>racadm -r 192.168.0.120 -u root -p calvin --nocertwarn getssninfo
SSNID Type              User                                          IP Address Login Date/Time
---------------------------------------------------------------------------
4604  GUI               root                                         10.132.50.5 05/23/2019 14:23:13
4661  Virtual Console   root                                         10.132.50.5 05/23/2019 14:33:18
4662  Virtual Media     root                                         10.132.50.5 05/23/2019 14:33:23
4663  RACADM            root                                         10.132.50.5 05/23/2019 14:33:27


C:\Python27>racadm -r 192.168.0.120 -u root -p calvin --nocertwarn closessn -i 4662
Session 4662 closed successfully.


C:\Python27>racadm -r 192.168.0.120 -u root -p calvin --nocertwarn getssninfo
SSNID Type              User                                          IP Address Login Date/Time
---------------------------------------------------------------------------
4604  GUI               root                                         10.132.50.5 05/23/2019 14:23:13
4661  Virtual Console   root                                         10.132.50.5 05/23/2019 14:33:18
4667  RACADM            root                                         10.132.50.5 05/23/2019 14:33:45

**Comment by lxjbutterfly** [comment]
@texroemer 

I got your meaning, at current, we could not distinguish a session which is "Virtual Media" by redfish API because it could not support "Type" which could be support by racadm .
But I still want to confirm 2 questions which I indeed care.
    **Is there any redfish API to execute "Disconnect Virtual Media" located in the menu**
    
![image](https://user-images.githubusercontent.com/50070028/58298591-a5ee2380-7e0e-11e9-96be-099894531521.png)



In my scenario, the "Virtual Media" exists or not doesn't matter, 
I want to attach the ISO image, and I need make some preparation.
     First of all, just execute the Redfish API to "Disconnect Virtual Media" in case of the session  "Virtual Media" exists.

**Comment by texroemer** [comment]
There is a way to delete the virtual media session using Redfish but you first need to find out the virtual media session ID using RACADM command. Once you get session ID, you can use Redfish to delete it.

I created a script to handle this workflow which is now on GitHub. Example of running the script to delete virtual media session:

C:\Python27\>GetDeleteiDRACSessionsREDFISH.py -ip 192.168.0.120 -u root -p calvin -c y

- Current running session(s) detected for iDRAC 192.168.0.120 -

/redfish/v1/Sessions/1939
/redfish/v1/Sessions/1845
/redfish/v1/Sessions/1810

- Detailed information for session URI "/redfish/v1/Sessions/1939" -

@odata.type: #Session.v1_1_0.Session
UserName: root
Name: User Session
@odata.id: /redfish/v1/Sessions/1939
@odata.context: /redfish/v1/$metadata#Session.Session
Password: None
Id: 1939
Description: User Session

- Detailed information for session URI "/redfish/v1/Sessions/1845" -

@odata.type: #Session.v1_1_0.Session
UserName: root
Name: User Session
@odata.id: /redfish/v1/Sessions/1845
@odata.context: /redfish/v1/$metadata#Session.Session
Password: None
Id: 1845
Description: User Session

- Detailed information for session URI "/redfish/v1/Sessions/1810" -

@odata.type: #Session.v1_1_0.Session
UserName: root
Name: User Session
@odata.id: /redfish/v1/Sessions/1810
@odata.context: /redfish/v1/$metadata#Session.Session
Password: None
Id: 1810
Description: User Session

C:\Python27>GetDeleteiDRACSessionsREDFISH.py -ip 192.168.0.120 -u root -p calvin -g y

- Current active sessions for iDRAC 192.168.0.120 using RACADM command -

SSNID Type              User                                          IP Address Login Date/Time
---------------------------------------------------------------------------
1810  GUI               root                                        192.168.0.120 05/24/2019 09:02:29
1845  Virtual Console   root                                        192.168.0.120 05/24/2019 10:16:53
1939  Virtual Media     root                                        192.168.0.120 05/24/2019 10:54:09
1946  RACADM            root                                        192.168.0.120 05/24/2019 10:54:34



C:\Python27>GetDeleteiDRACSessionsREDFISH.py -ip 192.168.0.120 -u root -p calvin -d 1939

- PASS: DELETE command passed to delete session id "1939", status code 200 returned
- PASS, validation passed to confirm session 1939 has been deleted

C:\Python27>GetDeleteiDRACSessionsREDFISH.py -ip 192.168.0.120 -u root -p calvin -c y

- Current running session(s) detected for iDRAC 192.168.0.120 -

/redfish/v1/Sessions/1845
/redfish/v1/Sessions/1810

- Detailed information for session URI "/redfish/v1/Sessions/1845" -

@odata.type: #Session.v1_1_0.Session
UserName: root
Name: User Session
@odata.id: /redfish/v1/Sessions/1845
@odata.context: /redfish/v1/$metadata#Session.Session
Password: None
Id: 1845
Description: User Session

- Detailed information for session URI "/redfish/v1/Sessions/1810" -

@odata.type: #Session.v1_1_0.Session
UserName: root
Name: User Session
@odata.id: /redfish/v1/Sessions/1810
@odata.context: /redfish/v1/$metadata#Session.Session
Password: None
Id: 1810
Description: User Session


And yes, these python scripts should work with 3.x Python version. Let me know if you see any issues.

**Comment by lxjbutterfly** [comment]
@texroemer 
   Thanks a lot for your new script, and I have tried it.
   parser.add_argument('-g', help='Get current iDRAC session IDs using remote RACADM, pass in \"y\". NOTE: Make sure you have **remote RACADM installed** first which is available to download from Dell support site.', required=False)

eshncho@seliiuts02448[14:56][iDrac/iDRAC-Redfish-Scripting/Redfish Python]$ python ./GetDeleteiDRACSessionsREDFISH.py -ip 10.196.23.75 -u root -p calvin -g y
/bin/sh: racadm: command not found

- Current active sessions for iDRAC 10.196.23.75 using RACADM command -
In fact, we could make sure a server has installed racadm, so missing the property "Type" for /redfish/v1/Sessions makes the session management not convenient.

PS: Another question

![image](https://user-images.githubusercontent.com/50070028/58401481-8cf4a500-8090-11e9-8b57-f6fb0feb303a.png)

As the snapshot show, an ISO has been attached, are there any redfish api to query(get) whether an ISO has been attached?

**Comment by lxjbutterfly** [comment]
@texroemer

About the version of python, would these script support python 3.0 and above?

![image](https://user-images.githubusercontent.com/50070028/58454025-c4765680-814f-11e9-82fa-54ed4a2664db.png)
![image](https://user-images.githubusercontent.com/50070028/58454062-e2dc5200-814f-11e9-8b5e-39b9cd24852c.png)


According my test results, it seems that the python script could not run normally if using python 3.5.0, but it could run using python 2.6.6.
In my opinion, the backward compatibility  is very important.
Do these scripts support python 3.0 or above? 
How to make these scripts run using python 3.5.0?

**Comment by texroemer** [comment]
@lxjbutterfly 

You need to install requests module for Python 3. Looks like you only have the requests module installed for Python 2. You need to also install it for Python 3. 

Here is my server running Python 3.7 and script works:

C:\Users\Administrator\AppData\Local\Programs\Python\Python37>InsertEjectVirtualMediaREDFISH.py -ip 192.168.0.120 -u root -p calvin -c y

 - Virtual Media URIs detected

/redfish/v1/Managers/iDRAC.Embedded.1/VirtualMedia/RemovableDisk
/redfish/v1/Managers/iDRAC.Embedded.1/VirtualMedia/CD

- Detailed information for URI "/redfish/v1/Managers/iDRAC.Embedded.1/VirtualMedia/RemovableDisk"

ConnectedVia: NotConnected
Description: iDRAC Virtual Media Services Settings
Id: RemovableDisk
Image: None
ImageName: None
Inserted: False
MediaTypes: ['USBStick']
Name: Virtual Removable Disk
WriteProtected: None

- Detailed information for URI "/redfish/v1/Managers/iDRAC.Embedded.1/VirtualMedia/CD"

ConnectedVia: NotConnected
Description: iDRAC Virtual Media Services Settings
Id: CD
Image: None
ImageName: None
Inserted: False
MediaTypes: ['CD', 'DVD']
Name: Virtual CD
WriteProtected: None

C:\Users\Administrator\AppData\Local\Programs\Python\Python37>

**Comment by lxjbutterfly** [comment]
@texroemer 
 I continued to try other python version

![image](https://user-images.githubusercontent.com/50070028/58522680-08229c00-81f4-11e9-9238-dc7aac2842ce.png)
![image](https://user-images.githubusercontent.com/50070028/58522712-22f51080-81f4-11e9-99e8-8db85472bf72.png)
 
I tested these python scripts with different python versions, the results as following 
python 2.6.6  ----- work normally
python 3.6, 3.5.0-----Need to install "requests" module
python 3.0.1, 3.2 --- SyntaxError: invalid syntax
whether I could get a conclusion:
At current, the compatibility of these scripts are not flexible, some python version could work, some other python version could not work.

**Comment by texroemer** [comment]
Hi @lxjbutterfly 

For older versions of Python especially with 3.x versions, Python team is always changing/improving behavior in their code. I only maintain the scripts to be working with latest Python versions which is what i recommend using.
