### ISSUE TITLE
InstallFromRepository - error message is: Mount of remote share failed.

### ISSUE THREAD

**Issue by aviv12825** [dell/iDRAC-Redfish-Scripting#63]
Hi, 

I run the below command and it fail- can someone explain why ?

**InstallFromRepositoryREDFISH.py** -ip 10.0.0.57 -u root -p calvin -i y --ipaddress 10.0.0.103 --sharename \SharedFolder1 --username root --password Ab:123456! --sharetype CIFS  --applyupdate True --rebootneeded True

- WARNING, arguments and values for InstallFromRepository method

ApplyUpdate: True
RebootNeeded: True
IPAddress: 10.0.0.103
ShareType: CIFS
ShareName: \SharedFolder1
UserName: root
Password : ********

- PASS: POST command passed for method "InstallFromRepository", status code 202 returned
- PASS, job ID JID_591386454604 successfully created
- WARNING, Job ID JID_591386454604 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:00:00"
- WARNING, Job ID JID_591386454604 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:00:05"
- WARNING, Job ID JID_591386454604 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:00:11"
- WARNING, Job ID JID_591386454604 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:00:16"
- WARNING, Job ID JID_591386454604 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:00:21"
- WARNING, Job ID JID_591386454604 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:00:26"
- WARNING, Job ID JID_591386454604 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:00:32"
- WARNING, Job ID JID_591386454604 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:00:37"
- WARNING, Job ID JID_591386454604 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:00:42"
- WARNING, Job ID JID_591386454604 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:00:48"
- WARNING, Job ID JID_591386454604 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:00:53"
- WARNING, Job ID JID_591386454604 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:00:58"
- WARNING, Job ID JID_591386454604 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:01:03"
- WARNING, Job ID JID_591386454604 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:01:09"
- WARNING, Job ID JID_591386454604 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:01:14"
- WARNING, Job ID JID_591386454604 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:01:19"
- WARNING, Job ID JID_591386454604 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:01:25"
- WARNING, Job ID JID_591386454604 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:01:30"
- WARNING, Job ID JID_591386454604 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:01:35"
- WARNING, Job ID JID_591386454604 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:01:41"
- WARNING, Job ID JID_591386454604 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:01:46"
- WARNING, Job ID JID_591386454604 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:01:51"
- WARNING, Job ID JID_591386454604 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:01:56"
- WARNING, Job ID JID_591386454604 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:02:02"
- WARNING, Job ID JID_591386454604 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:02:07"
- WARNING, Job ID JID_591386454604 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:02:12"
- WARNING, Job ID JID_591386454604 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:02:18"
- WARNING, Job ID JID_591386454604 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:02:23"
- WARNING, Job ID JID_591386454604 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:02:28"
- WARNING, Job ID JID_591386454604 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:02:33"
- WARNING, Job ID JID_591386454604 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:02:39"
- WARNING, Job ID JID_591386454604 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:02:44"
- WARNING, Job ID JID_591386454604 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:02:49"
- WARNING, Job ID JID_591386454604 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:02:54"
**- FAIL: Job ID JID_591386454604 failed, detailed error message is: Mount of remote share failed.**

**Comment by texroemer** [comment]
Hi @aviv12825 

Job ID failed due to unable to mount the network share. Is "SharedFolder1" your root CIFS share? if yes, you don't need to pass in "\" with the share name.

**Comment by aviv12825** [comment]
Im not sure I understand the question.
Im using win server not linux and my folder is shared, I did this using server manager tool\app. (file storge rule..) 
Can you please explain how to test this on Win server ? 
10x

**Comment by texroemer** [comment]
iDRAC is failing to mount your network share which is the error returned for job failure. 

For your CIFS share, i was trying to find out what is the absolute share path? If your share is "SharedFolder1", can you try passing in this string for your share name and see if it works? If iDRAC still fails to mount, can you check to make sure you can access this CIFS share with your user credentials?

**Comment by aviv12825** [comment]
I can enter the folder using the browser without any use of user name & password: 
![image](https://user-images.githubusercontent.com/29521767/58654257-25548900-8320-11e9-8d83-15665f1b9130.png)

but once sending the command with CLI I got the follwoing answer:
InstallFromRepositoryREDFISH.py -ip 10.0.0.57 -u root -p calvin -i y --ipaddress 10.0.0.103 --sharename //10.0.0.103/SharedFolder1/ --username root --password Ab:123456! --sharetype CIFS  --applyupdate True --rebootneeded True

- WARNING, arguments and values for InstallFromRepository method

ApplyUpdate: True
RebootNeeded: True
IPAddress: 10.0.0.103
ShareType: CIFS
ShareName: //10.0.0.103/SharedFolder1/
UserName: root
Password : ********

- PASS: POST command passed for method "InstallFromRepository", status code 202 returned
- PASS, job ID JID_592399136804 successfully created
- WARNING, Job ID JID_592399136804 not marked completed, current status: "New", job polling time: "0:00:00"
- WARNING, Job ID JID_592399136804 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:00:05"
- WARNING, Job ID JID_592399136804 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:00:11"
- WARNING, Job ID JID_592399136804 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:00:16"
- WARNING, Job ID JID_592399136804 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:00:21"
- WARNING, Job ID JID_592399136804 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:00:26"
- WARNING, Job ID JID_592399136804 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:00:32"
- WARNING, Job ID JID_592399136804 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:00:37"
- WARNING, Job ID JID_592399136804 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:00:42"
- WARNING, Job ID JID_592399136804 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:00:48"
- WARNING, Job ID JID_592399136804 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:00:53"
- WARNING, Job ID JID_592399136804 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:00:58"
- WARNING, Job ID JID_592399136804 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:01:04"
- WARNING, Job ID JID_592399136804 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:01:09"
- WARNING, Job ID JID_592399136804 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:01:14"
- WARNING, Job ID JID_592399136804 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:01:19"
- WARNING, Job ID JID_592399136804 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:01:25"
- WARNING, Job ID JID_592399136804 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:01:30"
- WARNING, Job ID JID_592399136804 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:01:35"
- WARNING, Job ID JID_592399136804 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:01:41"
- WARNING, Job ID JID_592399136804 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:01:46"
- WARNING, Job ID JID_592399136804 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:01:52"
- WARNING, Job ID JID_592399136804 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:01:57"
- WARNING, Job ID JID_592399136804 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:02:02"
- WARNING, Job ID JID_592399136804 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:02:07"
- WARNING, Job ID JID_592399136804 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:02:13"
- WARNING, Job ID JID_592399136804 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:02:18"
- WARNING, Job ID JID_592399136804 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:02:23"
- WARNING, Job ID JID_592399136804 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:02:29"
- WARNING, Job ID JID_592399136804 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:02:34"
- WARNING, Job ID JID_592399136804 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:02:39"
- WARNING, Job ID JID_592399136804 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:02:45"
- WARNING, Job ID JID_592399136804 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:02:50"
- WARNING, Job ID JID_592399136804 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:02:55"
- FAIL: Job ID JID_592399136804 failed, detailed error message is: Mount of remote share failed.

**Comment by texroemer** [comment]
Can you execute the command again but only pass in "SharedFolder1" for sharename argument?

Example:

InstallFromRepositoryREDFISH.py -ip 10.0.0.57 -u root -p calvin -i y --ipaddress 10.0.0.103 --sharename SharedFolder1 --username root --password Ab:123456! --sharetype CIFS --applyupdate True --rebootneeded True

**Comment by aviv12825** [comment]
sure, this is the result: 
>InstallFromRepositoryREDFISH.py -ip 10.0.0.57 -u root -p calvin -i y --ipaddress 10.0.0.103 --sharename SharedFolder1 --username root --password Ab:123456! --sharetype CIFS --applyupdate True --rebootneeded True

- WARNING, arguments and values for InstallFromRepository method

ApplyUpdate: True
RebootNeeded: True
IPAddress: 10.0.0.103
ShareType: CIFS
ShareName: SharedFolder1
UserName: root
Password : ********

- PASS: POST command passed for method "InstallFromRepository", status code 202 returned
- PASS, job ID JID_592406924199 successfully created
- WARNING, Job ID JID_592406924199 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:00:00"
- WARNING, Job ID JID_592406924199 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:00:05"
- WARNING, Job ID JID_592406924199 not marked completed, current status: "Downloading the Catalog.xml update package.", job polling time: "0:00:10"
- FAIL: Job ID JID_592406924199 failed, detailed error message is: The network file transfer of an update package was not successful.

**Comment by texroemer** [comment]
Thanks. So mount issue has been resolved and now hitting a new issue.

I noticed on your CIFS share, your catalog file is not named the default "Catalog.xml". When the file name is not the default name, you have to pass in this argument to tell iDRAC which catalog file to look for.

Can you try this?

InstallFromRepositoryREDFISH.py -ip 10.0.0.57 -u root -p calvin -i y --ipaddress 10.0.0.103 --sharename SharedFolder1 --username root --password Ab:123456! --sharetype CIFS --applyupdate True --rebootneeded True --catalogfile asdsa_1.00_Catalog.xml

**Comment by aviv12825** [comment]
Ok now its working :-) 
Thank you :-)

**Comment by texroemer** [comment]
Good to hear :)
