### ISSUE TITLE
Invoke-BootToNetworkIsoOsdREDFISH fails

### ISSUE THREAD

**Issue by jpbolwe** [dell/iDRAC-Redfish-Scripting#64]
Please see that I did try to run other status and I did receive valid responses.
command and error received:

Invoke-BootToNetworkIsoOsdREDFISH -idrac_ip <mydracip> -idrac_username root -idrac_password calvin -get_attach_status y

- WARNING, iDRAC version installed does not support this feature using Redfish API

- WARNING, getting network ISO attach information for iDRAC <mydracip>

{"error":{"@Message.ExtendedInfo":[{"Message":"Unable to run the method because the requested HTTP method is not 
allowed.","MessageArgs":[],"MessageArgs@odata.count":0,"MessageId":"IDRAC.1.6.SYS402","RelatedProperties":[],"RelatedProperties@odata.count":0,"Resolution":"Enter a valid HTTP method and 
retry the operation. For information about valid methods, see the Redfish Users Guide available on the support 
site.","Severity":"Informational"}],"code":"Base.1.0.GeneralError","message":"A general error has occurred. See ExtendedInfo for more information"}}

**Comment by texroemer** [comment]
Hi @jpbolwe 

There was an issue with the cmdlet, the function returned correct error message about iDRAC version detected is not supported but it didn't break out and cmdlet still tried to run. I fixed the cmdlet which should now break out correctly when iDRAC version detected is not supported.

For executing this cmdlet, its currently only supported on iDRAC 9 3.30 or newer. iDRAC 7/8 currently doesn't support this cmdlet.

Thanks

**Comment by jpbolwe** [comment]
Thanks for the help.
