### ISSUE TITLE
Customizing roles beyond Adminstrator, Operator, ReadOnly, and None?

### ISSUE THREAD

**Issue by slmingol** [dell/iDRAC-Redfish-Scripting#65]
Does Redfish provide any method to customize the stock 4 roles that are included with the DRAC? In the UI you can further refine which privs a user with the stock roles has, such as Operator, but doesn't appear to be possible with Redfish.

```
parser.add_argument('-R', help='Pass in the iDRAC user privileges you want to set for the user. Supported values are: \"Administrator\", \"Operator\", \"ReadOnly\" and \"None\"', required=False)

```

We'd like to allow a user the abilty to collect logs but not be able to change configuration or reboot the servers.

**Comment by texroemer** [comment]
Hi @slmingol 

For OEM URI "redfish/v1/Managers/iDRAC.Embedded.1/Accounts", we don't support custom privilege values as you can create in the UI. But with Redfish, you can create custom iDRAC user privileges by executing PATCH command on OEM URI "redfish/v1/Managers/iDRAC.Embedded.1/Attributes". With this URI and attribute "iDRAC.Users.Privilege", you can set custom privilege level. 

To set custom privilege level, you will need to refer to Dell attribute registry to get the supported values:

https://downloads.dell.com/manuals/all-products/esuprt_software/esuprt_remote_ent_sys_mgmt/idrac9-lifecycle-controller-v3303030_reference-guide8_en-us.pdf

Search for "iDRAC.Users.Privilege" attribute which will give you details on the supported custom privilege levels. You should see:

_iDRAC.Users.Privilege (Read or Write)
Description Specifies the role based authority privileges allowed for the user. Below list shows the decimal values for each
individual privilege.To create a custom privilege, add up below privilege decimal values and pass the value to the
attribute. Login 1 Configure 2 Configure Users 4 Logs 8 System Control 16 Access Virtual Console 32 Access
Virtual Media 64 System Operations 128 Debug 256_

To create a custom privilege level, add up the numbers and pass in this value to set the custom privilege level. Example below is i want to set iDRAC user 3 privilege to only have login and logs access. To set this privilege, i'll will be passing in a value of 9.

C:\Python27>GetIdracLcSystemAttributesREDFISH.py -ip 192.168.0.120 -u root -p calvin -an Users.3.Privilege -g idrac

Attribute Name: Users.3.Privilege, Current Value: 511

C:\Python27>SetIdracLcSystemAttributesREDFISH.py -ip 192.168.0.120 -u root -p calvin -an Users.3.Privilege -av 9 -s idrac

- WARNING, changing "IDRAC" attributes -

 Attribute Name: Users.3.Privilege, setting new value to: 9

- PASS, Command passed to successfully set "IDRAC" attribute(s), status code 200 returned

- WARNING, getting new attribute values -

Attribute Name: Users.3.Privilege, Attribute Value: 9
