### ISSUE TITLE
How does one configure iDRAC's LDAP configurations via Redfish?

### ISSUE THREAD

**Issue by slmingol** [dell/iDRAC-Redfish-Scripting#66]
I'm trying to determine if the Redfish REST API supports the ability to configure the LDAP setup so that we can remotely configure this so that user's can then log into iDRAC using LDAP credentials vs. a local account. 

I've verified that I can configure our iDRACs on several 720's and would like to explore automating the setup of LDAP configuration on these servers either using Python directly or the Ansible Redfish* modules.

**Comment by texroemer** [comment]
Hi @slmingol 

Yes you can configure iDRAC LDAP settings using Redfish API. Refer to my response in your other comment which calls out the OEM URI used to set iDRAC attributes. The registry will also have the information on LDAP attributes you can configure.

https://github.com/dell/iDRAC-Redfish-Scripting/issues/65

Also you can use Server Configuration Profile (SCP) to set iDRAC attributes which simplifies the process for setting multiple attributes and deploying a configuration on multiple servers. Here is a snippet from an exported SCP file which shows all iDRAC LDAP attributes. 

Attribute Name="LDAP.1#Enable">Disabled</Attribute> 
 <Attribute Name="LDAP.1#Server"/> 
 <Attribute Name="LDAP.1#Port">636</Attribute> 
 <Attribute Name="LDAP.1#BaseDN"/> 
 <Attribute Name="LDAP.1#UserAttribute"/> 
 <Attribute Name="LDAP.1#GroupAttribute"/> 
 <Attribute Name="LDAP.1#GroupAttributeIsDN">Enabled</Attribute> 
 <Attribute Name="LDAP.1#BindDN"/> 
  
 <Attribute Name="LDAP.1#SearchFilter"/> 
 <Attribute Name="LDAP.1#CertValidationEnable">Enabled</Attribute> 
 <Attribute Name="LDAPRoleGroup.1#DN"/> 
 <Attribute Name="LDAPRoleGroup.1#Privilege">0</Attribute> 
 <Attribute Name="LDAPRoleGroup.2#DN"/> 
 <Attribute Name="LDAPRoleGroup.2#Privilege">0</Attribute> 
 <Attribute Name="LDAPRoleGroup.3#DN"/> 
 <Attribute Name="LDAPRoleGroup.3#Privilege">0</Attribute> 
 <Attribute Name="LDAPRoleGroup.4#DN"/> 
 <Attribute Name="LDAPRoleGroup.4#Privilege">0</Attribute> 
 <Attribute Name="LDAPRoleGroup.5#DN"/> 
 <Attribute Name="LDAPRoleGroup.5#Privilege">0</Attribute

With SCP feature, once you have made all changes to the SCP file, you can import it which will apply all the iDRAC changes with one POST call.
