### ISSUE TITLE
InsertEjectVirtualMediaREDFISH powershell fails

### ISSUE THREAD

**Issue by jpbolwe** [dell/iDRAC-Redfish-Scripting#68]
Hello again,

I was trying to mount a general ISO as a test. the information gathering using Invoke-InsertEjectVirtualMediaREDFISH worked but the mount was failing and I did realize the DRAC was outdated so I did upgrade it using the Set-UpdateOneDeviceREDFISH, it worked well as expected:

-  "Name":"Integrated Dell Remote Access Controller"
-  "Installed version": 3.30.30.30
-  "Updateable":true

So I tried again my ISO mount, but I'm still getting an error, is there any issue on the below execution or is there any issue on the cmdlet, just one thing to check I have to point to the port in the http server:

Invoke-InsertEjectVirtualMediaREDFISH -idrac_ip <DRACIP> -idrac_username root -idrac_password calvin -virtual_media_action 1 -virtual_media_device 1 -uri_path http://<Repository server:port/Folderpath>/vmwareESXI65u2.iso

{"error":{"@Message.ExtendedInfo":[{"Message":"The requested operation cannot be completed because of an internal 
error.","MessageArgs":[],"MessageArgs@odata.count":0,"MessageId":"IDRAC.1.6.SYS446","RelatedProperties":[],"RelatedProperties@odata.count":0,"Resolution":"Retry the operation after a few 
minutes. If the issue persists, contact your service provider.","Severity":"Critical"},{"Message":"The request failed due to an internal service error. The service is still 
operational.","MessageArgs":[],"MessageArgs@odata.count":0,"MessageId":"Base.1.2.InternalError","RelatedProperties":[],"RelatedProperties@odata.count":0,"Resolution":"Resubmit the request. 
If the problem persists, consider resetting the service.","Severity":"Critical"}],"code":"Base.1.2.GeneralError","message":"A general error has occurred. See ExtendedInfo for more 
information"}}

**Comment by texroemer** [comment]
Hi @jpbolwe 

Can you check iDRAC Lifecycle Controller logs and see if there is any other log entries as to why it failed? 

Using remote or local RACADM, can you execute "racadm get idrac.virtualmedia" command and send the output? Need to see if any other virtual media sessions are already running. If yes, this will cause Redfish attach to fail.

Example of output:

C:\Python27>racadm -r 192.168.0.120 -u root -p calvin get idrac.virtualmedia --nocertwarn
[Key=idrac.Embedded.1#VirtualMedia.1]
#ActiveSessions=0
Attached=AutoAttach
BootOnce=Disabled
Enable=Enabled
EncryptEnable=Enabled
FloppyEmulation=Disabled
KeyEnable=Disabled
#MaxSessions=1

**Comment by jpbolwe** [comment]
Hello,

I don't have racadm handy available here, so I did run your own check and I'm adding the details from within the DRAC web interface as well:

"Invoke-InsertEjectVirtualMediaREDFISH -idrac_ip <DRACIP> -idrac_username root -idrac_password calvin -get_virtual_media_info y"

- GET command passed for URI https://<DRACIP>/redfish/v1/Managers/iDRAC.Embedded.1/VirtualMedia, status code 200 returned

- Detailed information for URI: /redfish/v1/Managers/iDRAC.Embedded.1/VirtualMedia/RemovableDisk



@odata.context         : /redfish/v1/$metadata#VirtualMedia.VirtualMedia
@odata.id              : /redfish/v1/Managers/iDRAC.Embedded.1/VirtualMedia/RemovableDisk
@odata.type            : #VirtualMedia.v1_2_0.VirtualMedia
Actions                : @{#VirtualMedia.EjectMedia=; #VirtualMedia.InsertMedia=}
ConnectedVia           : NotConnected
Description            : iDRAC Virtual Media Services Settings
Id                     : RemovableDisk
Image                  : 
ImageName              : 
Inserted               : False
MediaTypes             : {USBStick}
MediaTypes@odata.count : 1
Name                   : Virtual Removable Disk
WriteProtected         : 

- Detailed information for URI: /redfish/v1/Managers/iDRAC.Embedded.1/VirtualMedia/CD

@odata.context         : /redfish/v1/$metadata#VirtualMedia.VirtualMedia
@odata.id              : /redfish/v1/Managers/iDRAC.Embedded.1/VirtualMedia/CD
@odata.type            : #VirtualMedia.v1_2_0.VirtualMedia
Actions                : @{#VirtualMedia.EjectMedia=; #VirtualMedia.InsertMedia=}
ConnectedVia           : NotConnected
Description            : iDRAC Virtual Media Services Settings
Id                     : CD
Image                  : 
ImageName              : 
Inserted               : False
MediaTypes             : {CD, DVD}
MediaTypes@odata.count : 2
Name                   : Virtual CD
WriteProtected         : 

From the WEB interface:

General overview:
Device Type | 14G Modular
-- | --
Hardware Version | 0.01
Firmware Version | 3.30.30.30
Firmware Updated | Tue Jun 11 09:34:03 2019
RAC Time | Tue Jun 11 17:11:03 2019
Number of Possible Sessions | 8
Number of Current Sessions | 1
IPMI Version | 2.0

and under virtual media:
![image](https://user-images.githubusercontent.com/39058850/59292697-f01b3580-8c53-11e9-90ce-a4ba8d5072d2.png)

**Comment by jpbolwe** [comment]
Just in case I did also run an unmount:

PS H:\> Invoke-InsertEjectVirtualMediaREDFISH -idrac_ip <DRACIP>-idrac_username root -idrac_password calvin -virtual_media_action 2 -virtual_media_device 1

{"error":{"@Message.ExtendedInfo":[{"Message":"No Virtual Media devices are currently 
connected.","MessageArgs":[],"MessageArgs@odata.count":0,"MessageId":"IDRAC.1.6.VRM0009","RelatedProperties":[],"RelatedProperties@odata.count":0,"Resolution":"No response action is 
required.","Severity":"Critical"},{"Message":"The request failed due to an internal service error. The service is still 
operational.","MessageArgs":[],"MessageArgs@odata.count":0,"MessageId":"Base.1.2.InternalError","RelatedProperties":[],"RelatedProperties@odata.count":0,"Resolution":"Resubmit the request. 
If the problem persists, consider resetting the service.","Severity":"Critical"}],"code":"Base.1.2.GeneralError","message":"A general error has occurred. See ExtendedInfo for more 
information"}}

**Comment by texroemer** [comment]
Thanks. So this confirms you have no active virtual media sessions. 

Can you check iDRAC Lifecycle logs and see what error is reported? You should see an error message stating why it failed to access your share.

Also can you access your HTTP share with no issues? You are able to read and write to it, firewall is not blocking the port.

**Comment by jpbolwe** [comment]
Well, also general message from my knowledge, although through the console I'm able to map the media. The file is available and downloadable from the http repository see the logs below:

![image](https://user-images.githubusercontent.com/39058850/59294976-0972b080-8c59-11e9-9f66-dd028d4a0208.png)

**Comment by texroemer** [comment]
Thanks. In the iDRAC GUI, can you go to Configuration / Virtual Media / Remote File Share and use this feature to try and connect with your HTTP share ISO. If this fails, then we know its not a Redfish specific issue and an issue with iDRAC accessing your HTTP share. 

Also which web server are you using? Is it IIS or Apache?

**Comment by jpbolwe** [comment]
Hello,
I tried from the GUI under the Virtual Media and it failed while accessing from my computer or any other did work, after some coffee, I did realize that under IIS the anonymous logon was not enabled, so totally my fault. After enabling the anon logon and configuring the site binding in my Repository IIS server it worked:

PS H:\> Invoke-InsertEjectVirtualMediaREDFISH -idrac_ip <DRACIP> -idrac_username root -idrac_password calvin -virtual_media_action 1 -virtual_media_device 1 -uri_path http://<RepoIP/Folderpath>/vmwareESXI65u2.iso

- PASS, POST command passed for Virtual Media Insert, status code 204 returned

- PASS, GET command passed and verified virtual media device is attached(insert)

**Comment by texroemer** [comment]
Good to hear it's now working :)
