### ISSUE TITLE
How can we retrieve CPLD firmware info

### ISSUE THREAD

**Issue by kgrvamsi** [dell/iDRAC-Redfish-Scripting#69]
Which redfish API would have the CPLD Firmware info to fetch and which version of idrac supports it?

**Comment by texroemer** [comment]
Hi @kgrvamsi 

GET on URI "redfish/v1/UpdateService/FirmwareInventory" will return URIs for each device iDRAC supports for firmware updates which CPLD is one of them. 

If you are using iDRAC 9 3.30, you can run GET on this URI using $expand query which will automatically expand all URIs with one GET call. You only then need to search for Name "System CPLD" in the JSON output. Once you find this name, look for "Version" property to get the current CPLD version installed.

Example of the URI using $expand "redfish/v1/UpdateService/FirmwareInventory?$expand=*($levels=1)".

If you have iDRAC 7/8 2.61, GET queries are not supported so you will need to run a GET on each firmware URI to figure out which one is CPLD.  If needed, you can use script "DeviceFirmwareSimpleUpdateREDFISH.py" to get the CPLD version.

Example of running the script:

C:\Python27>DeviceFirmwareSimpleUpdateREDFISH.py -ip 192.168.0.120 -u root -p calvin -g y

- WARNING, current devices detected with firmware version and updateable status -

Device Name: Power Supply.Slot.1, Firmware Version: 00.10.37, Updatable: True
Device Name: BP13G+ 0:1, Firmware Version: 2.25, Updatable: True
Device Name: PERC H730 Mini, Firmware Version: 25.5.5.0005, Updatable: True
Device Name: OS COLLECTOR 1.1, OSC_1.1, A00, Firmware Version: OSC_1.1, Updatable: True
Device Name: Disk 5 in Backplane 1 of Integrated RAID Controller 1, Firmware Version: VT31, Updatable: True
Device Name: BIOS, Firmware Version: 2.7.1, Updatable: True
Device Name: Dell OS Driver Pack, 18.11.00, A00, Firmware Version: 18.11.00, Updatable: True
Device Name: Integrated Dell Remote Access Controller, Firmware Version: 2.61.60.60, Updatable: True
Device Name: Dell 64 Bit uEFI Diagnostics, version 4239A37, 4239.45, Firmware Version: 4239A37, Updatable: True
Device Name: QLogic 577xx/578xx 10 Gb Ethernet BCM57810 - 00:0A:F7:5D:7A:72, Firmware Version: 14.04.18, Updatable: True
**Device Name: System CPLD, Firmware Version: 1.0.1, Updatable: True**
Device Name: Lifecycle Controller, Firmware Version: 2.61.60.60, Updatable: False

**Comment by kgrvamsi** [comment]
@texroemer so CPLD is firmware that is available from 2.30.30.30 or it is part of the Hardware (R730xd,740xd) ?

**Comment by texroemer** [comment]
CPLD firmware is on the motherboard itself, part of the hardware and separate from iDRAC firmware.

**Comment by kgrvamsi** [comment]
@texroemer  thanks and i can fetch the firmware info for CPLD.
