### ISSUE TITLE
Problem with redfish/v1/Systems/System.Embedded.1/Bios

### ISSUE THREAD

**Issue by dpjohnson** [dell/iDRAC-Redfish-Scripting#7]
Hi,

We have C6320s with iDRAC firmware version 2.41.40.40 (Build 07). I'm attempting to test Redfish scripting, and started by trying the BiosGetAttributesREDFISH.py script. I get the following error when running this script,

{u'error': {u'message': {u'lang': u'en-us', u'value': u'failed: Request URI: /redfish/v1/Systems/System.Embedded.1/Bios is invalid'}, u'code': u'1'}}
Traceback (most recent call last):
  File "./BiosGetAttributesREDFISH.py", line 65, in <module>
    get_bios_attributes()
  File "./BiosGetAttributesREDFISH.py", line 53, in get_bios_attributes
    for i in data[u'Attributes'].items():
KeyError: u'Attributes'

When I visit the corresponding URL in a browser I see the following,

{
  "error": {
    "code": "1",
    "message": {
      "lang": "en-us",
      "value": "failed: Request URI: /redfish/v1/Systems/System.Embedded.1/Bios is invalid"
    }
  }
}

Any insight into the error would be appreciated, we would really like to transition to Redfish for managing our systems.

**Comment by jonas-werner** [comment]
@dpjohnson The firmware version is likely too old to support the Bios settings via Redfish. Please update to 2.50.50.50. That release added a lot of new features.

**Comment by dpjohnson** [comment]
Hi, upgrade to 2.50.50.50 solved the problem. 

Thanks,
Doug
