### ISSUE TITLE
How to Set BootSeq with no values from Redfish API

### ISSUE THREAD

**Issue by kgrvamsi** [dell/iDRAC-Redfish-Scripting#76]
How to set BotSeq to empty array instead any value

Racadm command
`
racadm set BIOS.BiosBootSettings.BootSeq 
`

Not sure if empty space would set the BootSeq to null value but trying the same with redfish api is not working and resulting in error and success at times but i don't see any difference 

![image](https://user-images.githubusercontent.com/1199031/65009435-47bfe180-d8d2-11e9-9d6b-9b26a1bfbd2e.png)

But when did a get call to fetch the BootSource i get the following output

![image](https://user-images.githubusercontent.com/1199031/65009553-ba30c180-d8d2-11e9-803b-f9d519966dd2.png)

**Comment by kgrvamsi** [comment]
@texroemer can you help me on this please

**Comment by texroemer** [comment]
Hi @kgrvamsi 

Are you trying to empty out the boot order list with no devices or what is the end result you are looking for in the boot order? 

BIOS will not let you empty the boot device list, you must have at least one device in the boot order. You can though disable all the devices in the boot list but these devices will still be listed in the boot order, they just won't be bootable.

**Comment by kgrvamsi** [comment]
@texroemer how can we disable the device over redfish api?

**Comment by texroemer** [comment]
To disable/enable boot device device using Redfish, Dell supports using OEM and DMTF methods. 

See python scripts "GetBiosBootOrderBootSourceStateREDFISH.py and ChangeBootOrderBootSourceStateREDFISH.py" for changing the boot order using OEM.

See python script "ChangeBiosBootOrderDMTF_REDFISH.py" for changing the boot order using DTMF.
