### ISSUE TITLE
How to Set HardDisk.List.1-1 as one of the BootSeq Order?

### ISSUE THREAD

**Issue by kgrvamsi** [dell/iDRAC-Redfish-Scripting#77]
I'm trying to set HardDisk.List.1-1 as the bootseq order from the redfish api but the the request results in 202 accepted HTTP code but when i see the server job queue it gets failed not sure why its resulting in failure status

![image](https://user-images.githubusercontent.com/1199031/65010619-10533400-d8d6-11e9-8a95-033e2718ceb9.png)

Job Queue Result

![image](https://user-images.githubusercontent.com/1199031/65010639-1c3ef600-d8d6-11e9-859f-892b90fdfb69.png)

**Comment by texroemer** [comment]
HI @kgrvamsi 

For setting "HardDisk.List.1-1" in the BIOS boot order using Server Configuration Profile feature, you must use the BIOS FQDD.

Here's an example of the correct Body to pass in:

`{"ShareParameters":{"Target":"ALL"},"ImportBuffer":"<SystemConfiguration><Component FQDD=\"BIOS.Setup.1-1\"><Attribute Name=\"BiosBootSeq\">HardDisk.List.1-1</Attribute></Component></SystemConfiguration>"}`

**Comment by kgrvamsi** [comment]
@texroemer the job runs successfully and when i run the bootsources get call i don't see the HardDisk.List.1-1 listed

**Comment by kgrvamsi** [comment]
Here are some screenshots on the same

![image](https://user-images.githubusercontent.com/1199031/65079178-30313900-d964-11e9-86d6-0d0577a26b75.png)
![image](https://user-images.githubusercontent.com/1199031/65079220-4212dc00-d964-11e9-9323-a62a5bc29acd.png)

![image](https://user-images.githubusercontent.com/1199031/65079190-39220a80-d964-11e9-831b-d12fe7684858.png)

![image](https://user-images.githubusercontent.com/1199031/65079226-47702680-d964-11e9-9bef-5ebb352e48d4.png)

**Comment by texroemer** [comment]
If HardDisk.List.1-1 no longer shows up in BIOS boot order, then this means a RAID volume no longer exists. Can you check iDRAC storage inventory and see if a RAID volume is reported for your storage controller?
