### ISSUE TITLE
ExportTechSupportReportREDFISH.py module doesnot work for iDRAC 9 

### ISSUE THREAD

**Issue by aizazmak** [dell/iDRAC-Redfish-Scripting#78]
Why ExportTechSupportReportREDFISH.py module doesnot work for iDRAC9 ?
How can this be achieved for iDRAC9 servers ? Is their any alternative in place ?

**Comment by texroemer** [comment]
Hi @aizazmak 

For ExportTechSupportReport script to work, you must have at minimum iDRAC9 version 3.30 installed. 3.30 iDRAC is the version Dell added support for this feature. Latest current iDRAC 9 version posted on Dell support site is 3.34.

Example below running the script on iDRAC 3.34 version:

C:\Python27>racadm -r 192.168.0.120 -u root -p calvin --nocertwarn getversion
 Bios Version                     = 2.2.11

 iDRAC Version                    = 3.34.34.34

 Lifecycle Controller Version     = 3.34.34.34

 IDSDM Version                    = NA



C:\Python27>ExportTechSupportReportREDFISH.py -ip 192.168.0.120 -u root -p calvin --ipaddress 192.168.0.130 --sharetype NFS --sharename /nfs --dataselectorarrayin 3

- WARNING, arguments and values for ExportTechSupportReport method

ShareType: NFS
ShareName: /nfs
DataSelectorArrayIn: ['TTYLogs']
IPAddress: 100.65.84.144

- PASS: POST command passed for ExportTechSupportReport method, status code 202 returned
- PASS, job ID JID_699475342139 successfuly created for ExportTechSupportReport method

- WARNING, JobStatus not completed, current status: "The SupportAssist Collection operation started.", percent complete: "2"
- WARNING, JobStatus not completed, current status: "The SupportAssist Collection operation started.", percent complete: "2"
- WARNING, JobStatus not completed, current status: "The SupportAssist Collection operation started.", percent complete: "2"
- WARNING, JobStatus not completed, current status: "The SupportAssist Collection operation started.", percent complete: "2"
- WARNING, JobStatus not completed, current status: "The SupportAssist Collection operation started.", percent complete: "3"
- WARNING, JobStatus not completed, current status: "The SupportAssist Collection operation started.", percent complete: "3"
- WARNING, JobStatus not completed, current status: "The SupportAssist Collection operation started.", percent complete: "4"
- WARNING, JobStatus not completed, current status: "The SupportAssist Collection operation started.", percent complete: "4"
- WARNING, JobStatus not completed, current status: "The SupportAssist Collection operation started.", percent complete: "4"
- WARNING, JobStatus not completed, current status: "The SupportAssist Collection operation started.", percent complete: "5"
- WARNING, JobStatus not completed, current status: "The SupportAssist Collection operation started.", percent complete: "5"
- WARNING, JobStatus not completed, current status: "The SupportAssist Collection operation started.", percent complete: "6"
- WARNING, JobStatus not completed, current status: "The SupportAssist Collection operation started.", percent complete: "7"
- WARNING, JobStatus not completed, current status: "The SupportAssist Collection operation started.", percent complete: "7"
- WARNING, JobStatus not completed, current status: "The SupportAssist Collection operation started.", percent complete: "7"
- WARNING, JobStatus not completed, current status: "The SupportAssist Collection operation started.", percent complete: "8"
- WARNING, JobStatus not completed, current status: "The SupportAssist Collection operation started.", percent complete: "9"
- WARNING, JobStatus not completed, current status: "The SupportAssist Collection operation started.", percent complete: "9"
- WARNING, JobStatus not completed, current status: "The SupportAssist Collection operation started.", percent complete: "50"

--- PASS, Final Detailed Job Status Results ---

JobState: Completed
Description: Job Instance
CompletionTime: 2019-10-01T11:34:09
PercentComplete: 100
StartTime: TIME_NOW
MessageId: SRV088
Message: The SupportAssist Collection and Transmission Operation is completed successfully.
EndTime: None
Id: JID_699475342139
JobType: SACollectExportHealthData
Name: SupportAssist Collection

**Comment by aizazmak** [comment]
Is it possible to generate & download the TSR logs for iDRACs on lower FW version ?
Any REST / Redfish API that would be used for them ?

**Comment by texroemer** [comment]
If you have iDRAC version older than 3.30 installed, using Redfish to get TSR is not supported. But iDRAC CLI RACADM command does support getting TSR logs on older versions.

C:\Python27>racadm -r 192.168.0.120 -u root -p calvin --nocertwarn help techsupreport

Techsupreport -- Tech Support Report operations.

Techsupreport has multiple subcommands, view the help
as shown below.

Usage:

racadm techsupreport help collect
racadm techsupreport help export
racadm techsupreport help getupdatetime
racadm techsupreport help updateosapp

----------------------------------------------------

For help on viewing the properties of a group, run the command - racadm help get
For help on configuring the properties of a group, run the command - racadm help set

-----------------------------------------------------------------------
