### ISSUE TITLE
Set-IdracLcSystemAttributesREDFISH bug testing for value type

### ISSUE THREAD

**Issue by 6str** [dell/iDRAC-Redfish-Scripting#79]
Hello,

I found that I couldn't set iDRAC values that were IP addresses (like DNS servers)
 nor ADGroup.<n>.Privilege values, as they were falling foul of the code to test whether the values should be submitted as type string or int.

The problem seems to be the 192:   if ($value -match "^[\d\.]+$")
which coming out with the right result testing for numbers.

I changed it for the more familiar test,     if ($value -match "^\d+$") 
and have been able to set int values, ip address values, and a whole bunch of others without problem, but my tests are not exhaustive. There may be values that I haven't tried that would bomb out.

**Comment by texroemer** [comment]
Hi @6str 

Can you send me examples of the script failing? I just tried to change iDRAC IP and AD group privilege and didn't see any failures.

Examples:



C:\Python27>SetIdracLcSystemAttributesREDFISH.py -ip 100.65.84.49 -u root -p calvin -s idrac -an IPv4.1.Address -av "100.65.84.48"

- WARNING, changing "IDRAC" attributes -

 Attribute Name: IPv4.1.Address, setting new value to: 100.65.84.48

- PASS, Command passed to successfully set "IDRAC" attribute(s), status code 200 returned

- WARNING, getting new attribute values -

Attribute Name: IPv4.1.Address, Attribute Value: 100.65.84.48




C:\Python27>SetIdracLcSystemAttributesREDFISH.py -ip 100.65.84.48 -u root -p calvin -s idrac -an ADGroup.4.Privilege -av 511

- WARNING, changing "IDRAC" attributes -

 Attribute Name: ADGroup.4.Privilege, setting new value to: 511

- PASS, Command passed to successfully set "IDRAC" attribute(s), status code 200 returned

- WARNING, getting new attribute values -

Attribute Name: ADGroup.4.Privilege, Attribute Value: 511

**Comment by 6str** [comment]
Hi,
it looks like you tested the python code. The problem I reported was with the powershell code.
don't think it makes a difference, but I loaded the values from file

**Comment by texroemer** [comment]
Ah, Powershell, ok i found this issue and fixed the cmdlet. I also updated the cmdlet to no longer use a file for setting the attributes, you now pass in multiple attribute name/values for the parameter values. 

Example:

PS C:\> Set-IdracLcSystemAttributesREDFISH -idrac_ip 100.65.84.70 -idrac_username root -idrac_password calvin -attribute
_group idrac -attribute_name "ADGroup.4.Privilege,Telnet.1.Enable,Security.1.CsrCommonName" -attribute_value "0,Disabled
,blade"


- WARNING, checking attribute(s) against the Attribute Registry to get attribute type, this may take several seconds

- WARNING, attribute Telnet.1.Enable current value is: Enabled, setting new value to: Disabled
- WARNING, attribute ADGroup.4.Privilege current value is: 511, setting new value to: 0
- WARNING, attribute Security.1.CsrCommonName current value is: blade_Server, setting new value to: blade

- PASS, statuscode 200 returned to successfully SET "IDRAC" attributes

- PASS, statuscode 200 returned to successfully GET "IDRAC" attributes

- PASS, attribute Telnet.1.Enable current value is successfully set to: Disabled
- PASS, attribute ADGroup.4.Privilege current value is successfully set to: 0
- PASS, attribute Security.1.CsrCommonName current value is successfully set to: blade
