### ISSUE TITLE
BIOS Configuration Changes not being applied after reboot.

### ISSUE THREAD

**Issue by dhruman** [dell/iDRAC-Redfish-Scripting#84]
Hello, 

I am able to get all the bios settings but when patching the Settings, I get a success but the settings are shown as pending after reboots/power cycle.

![dell-redfish-bios-not-updated](https://user-images.githubusercontent.com/4665525/69288876-b873ca80-0baf-11ea-8bf0-7c31f4ca1342.jpg)
![dell-bios-pending](https://user-images.githubusercontent.com/4665525/69289002-156f8080-0bb0-11ea-856f-7a320a1e77b9.jpg)

**Comment by texroemer** [comment]
Hi @dhruman,

When executing PATCH command for setting BIOS attributes, you must also pass in "@Redfish.SettingsApplyTime" which will generate a job ID URI in the output header response. You can then execute a GET to validate this job ID is marked as schedule, then reboot the server for the job to execute and apply the BIOS changes.

Example of PATCH body:

{'@Redfish.SettingsApplyTime': {'ApplyTime': 'OnReset'}, 'Attributes': {'MemTest': 'Disabled'}}

If needed, you can refer to python script "GetSetBiosAttributesREDFISH.py" which shows this workflow.

Thanks
