### ISSUE TITLE
example python for generating csr/importing ssl certificate.

### ISSUE THREAD

**Issue by acblatt** [dell/iDRAC-Redfish-Scripting#88]
Can you use idrac redfish to generate csr and import certificate as can do with racadm?

**Comment by texroemer** [comment]
Hi @acblatt 

Sorry for the late reply, current iDRAC versions do not support generate CSR but they do support import certificate. Redfish generate CSR is planned to get added in future iDRAC release. 

For import certificate support, refer to URI "redfish/v1/Dell/Managers/iDRAC.Embedded.1/DelliDRACCardService" and schema "redfish/v1/Schemas/DelliDRACCardService_v1.xml".

Thanks
