### ISSUE TITLE
BiosResetToDefaultsREDFISH.py line 58 missing parentheses in print statement

### ISSUE THREAD

**Issue by krisiasty** [dell/iDRAC-Redfish-Scripting#89]
BiosResetToDefaultsREDFISH.py line 58 is missing parentheses in print statement, so the script does not work under python3:

```
$ python3 BiosResetToDefaultsREDFISH.py --help
  File "BiosResetToDefaultsREDFISH.py", line 58
    print detail_message
                       ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(detail_message)?
```

https://github.com/dell/iDRAC-Redfish-Scripting/blob/797230080a7ade1100acfa39ae20dd318173fdbb/Redfish%20Python/BiosResetToDefaultsREDFISH.py#L58

**Comment by texroemer** [comment]
Hi @krisiasty 

Thanks for pointing this out and yes, print statement format was incorrect and wasn't able to handle working with Python 3, only Python 2. I fixed the code and new script has been uploaded to GitHub, will work with Python 2 and 3 now.

Thanks
