### ISSUE TITLE
Failure to create configureation job

### ISSUE THREAD

**Issue by jimbr70** [dell/iDRAC-Redfish-Scripting#9]
I have no errors up until the 'create_bios_config_job' and the error is 
   No pending data present to create a Configuration job.
The data from the call before to set the config does not match current settings, so there is a change:

[{u'Index': 0, u'Enabled': True, u'Id': u'BIOS.Setup.1-1#UefiBootSeq#NIC.PxeDevice.1-1#81e55d13a36bc065ca3bf9bf8d699391', u'Name': u'NIC.PxeDevice.1-1'},
{u'Index': 1, u'Enabled': True, u'Id': u'BIOS.Setup.1-1#UefiBootSeq#RAID.Integrated.1-1#87261b9978c1e72f4eee4644670cb0a6', u'Name': u'RAID.Integrated.1-1'}]

No matter if I swap the indexes - same error.  Server has 2.50.50.50 iDRAC.
create_bios_configjob is unchanged from your code.
set_bios_boot_source is unchanged but passess with resp 200

Anxious to fix.  Be awesome

**Comment by texroemer** [comment]
Hi and sorry about the late reply. Did you first execute the GET script to get the current boot order which will generate the file needed or did you manually create the listed dictionary? Here's an example of mine which some of the syntax looks different.

[{"Index": 0, "Enabled": true, "Id": "BIOS.Setup.1-1#UefiBootSeq#Floppy.iDRACVirtual.1-1#f64c2e3f049b92a8e71f61cf51fea794", "Name": "Floppy.iDRACVirtual.1-1"}, {"Index": 1, "Enabled": true, "Id": "BIOS.Setup.1-1#UefiBootSeq#Optical.iDRACVirtual.1-1#375d3ecb49f87dd46ca6c60e34f6155d", "Name": "Optical.iDRACVirtual.1-1"}, {"Index": 2, "Enabled": true, "Id": "BIOS.Setup.1-1#UefiBootSeq#Optical.SATAEmbedded.J-1#cc771e0341320e3a39c9588b8fe10c03", "Name": "Optical.SATAEmbedded.J-1"}, {"Index": 3, "Enabled": true, "Id": "BIOS.Setup.1-1#UefiBootSeq#RAID.Integrated.1-1#87261b9978c1e72f4eee4644670cb0a6", "Name": "RAID.Integrated.1-1"}]

**Comment by jimbr70** [comment]
I have solved all my isues.  Thanks

Jim Brannan  |  PV Engineer
Office/Home: 530-878-1123 USA, GMT-7
Mobile: (916) 719-8063




________________________________________
