### ISSUE TITLE
Does not really change the boot order

### ISSUE THREAD

**Issue by Chandan-Hegde** [dell/iDRAC-Redfish-Scripting#91]
Though boot order change is initiated, the boot order does not gets changed really in the UEFI boot sequence. The status of the boot order shown will also be incorrect.

**Comment by texroemer** [comment]
Hi @Chandan-Hegde 

Can you give me more details on which script you tried to execute to change the UEFI boot sequence? 

Example below shows executing Python script to change URFI boot order which once the job ID is marked completed, new boot order is reported (I moved PXE device 1 as first device in the boot order).


C:\Python27>ChangeBiosBootOrderDMTF_REDFISH.py -ip 192.168.0.120 -u root -p calvin -g y

- Current boot order detected for BIOS boot mode "Uefi" -

SequenceNumber: 0, DisplayName: Integrated RAID Controller 1: sles-secureboot, Id: Boot0002
SequenceNumber: 1, DisplayName: PXE Device 1: Integrated NIC 1 Port 1 Partition 1, Id: Boot0003

C:\Python27>ChangeBiosBootOrderDMTF_REDFISH.py -ip 192.168.0.120 -u root -p calvin -c Boot0003,Boot0002

- PASS: PATCH command passed to change Uefi boot order sequence
- PASS, job ID "JID_805152406575" successfully created to change Uefi boot order sequence
- WARNING: JobStatus not scheduled, current status is: New
- PASS, JID_805152406575 job id successfully scheduled, rebooting the server to apply config changes

- WARNING, Current server power state is: On
- PASS, Command passed to attempt gracefully power OFF server, status code 204 returned
- PASS, GET command passed to verify server is in OFF state
- PASS, Command passed to power ON server, code return is 204
- WARNING, JobStatus not completed, current status is: "Task successfully scheduled."
- WARNING, JobStatus not completed, current status is: "Task successfully scheduled."
- WARNING, JobStatus not completed, current status is: "Task successfully scheduled."
- WARNING, JobStatus not completed, current status is: "Task successfully scheduled."
- WARNING, JobStatus not completed, current status is: "Job in progress."
- WARNING, JobStatus not completed, current status is: "Job in progress."
- WARNING, JobStatus not completed, current status is: "Job in progress."

- Final detailed job results -

 JobID = JID_805152406575
 Name = ConfigBIOS:BIOS.Setup.1-1
 Message = Job completed successfully.
 PercentComplete = 100


- Current boot order detected for BIOS boot mode "Uefi" -

SequenceNumber: 0, DisplayName: PXE Device 1: Integrated NIC 1 Port 1 Partition 1, Id: Boot0003
SequenceNumber: 1, DisplayName: Integrated RAID Controller 1: sles-secureboot, Id: Boot0002
