### ISSUE TITLE
Can't save output in variable?

### ISSUE THREAD

**Issue by lucien62** [dell/iDRAC-Redfish-Scripting#92]
Hello,

1)
I want to use Set-UpdateOneDeviceREDFISH command to do firmware inventory on lots of iDracs.
First trying on one iDrac:

`$result_idrac = Set-UpdateOneDeviceREDFISH -idrac_ip 192.168.100.50 -idrac_username root -idrac_password calvin -view_fw_inventory_only y`

This doesn't save anything in the $result_idrac variable, instead the console displays the output:
```

--- Firmware Inventory ---

-  "Name":"Broadcom Adv. Dual 25Gb Ethernet - B0:26:28:7F:DD:E1"
-  "Installed version": 21.40.22.20
-  "Updateable":true

-  "Name":"Power Supply.Slot.1"
-  "Installed version": 00.14.7F
-  "Updateable":true

-  "Name":"PERC H330 Adapter"
-  "Installed version": 25.5.5.0005
-  "Updateable":true

-  "Name":"OS COLLECTOR
-  "Installed version": 3.0
-  "Updateable":true

-  "Name":"Intel(R) Ethernet 10G X710 rNDC - E4:43:4B:5F:29:BC"
-  "Installed version": 18.8.9
-  "Updateable":true

-  "Name":"BP14G+ 0:1"
-  "Installed version": 4.27
-  "Updateable":true

-  "Name":"iDRAC Service Module Embedded Package
-  "Installed version": 3.4.0
-  "Updateable":true

-  "Name":"Disk 0 in Backplane 1 of RAID Controller in Slot 4"
-  "Installed version": HF56
-  "Updateable":true

-  "Name":"BIOS"
-  "Installed version": 2.2.11
-  "Updateable":true

-  "Name":"Dell OS Driver Pack
-  "Installed version": 19.04.05
-  "Updateable":true

-  "Name":"Integrated Dell Remote Access Controller"
-  "Installed version": 3.34.34.34
-  "Updateable":true

-  "Name":"Dell 64 Bit uEFI Diagnostics
-  "Installed version": 4301A33
-  "Updateable":true

-  "Name":"System CPLD"
-  "Installed version": 1.1.3
-  "Updateable":true

```
2)
Why is the output of these commands so un-standard to what I'm used to with other modules like powercli for ex.?
I do a little bit of powershell in my sysadmin job and almost everytime the ouput of powershell commands is presented with properties that can be filtered. Here the output looks like a big text object that can't be easily manipulated.

**Comment by texroemer** [comment]
Hi @lucien62 

GET output was returned in string format. I changed the cmdlet code to return output in PSCustomObject. You can now execute the cmdlet passing it to a variable which you can then parse for specific properties. 

Updated cmdlet has been uploaded to GitHub. Here's an example of executing new cmdlet, redirect to a variable and parse the data to get only specific properties.

PS C:\> $fw = Set-UpdateOneDeviceREDFISH -idrac_ip 192.168.0.120 -idrac_username root -idrac_password calvin -view_fw_inv
entory_only y

--- Getting Firmware Inventory For iDRAC 192.168.0.120 ---

PS C:\> $fw | Select Name,Version

Name                                                                  Version
----                                                                  -------
PERC H730P Mini                                                       25.5.6.0009
Intel(R) Ethernet Converged Network Adapter X710 - 3C:FD:FE:4F:09:C2  19.0.12
Intel(R) Ethernet Server Adapter X710-DA2 for OCP - 3C:FD:FE:4F:09:C0 19.0.12
Intel(R) Gigabit I350-t LOM - 80:18:44:7A:13:C5                       19.0.12
BOSS-S1                                                               2.6.13.3022
BIOS                                                                  2.3.10
PERC H730P Mini                                                       25.5.6.0009
OS COLLECTOR, 3.0, A00                                                3.0
Intel(R) Ethernet Converged Network Adapter X710 - 3C:FD:FE:4F:09:C2  19.0.12
Disk 7 in Backplane 1 of RAID Controller in Mezzanine 1               TT31
Disk 10 in Backplane 1 of RAID Controller in Mezzanine 1              VT31
BP14G+EXP 0:1                                                         2.25
iDRAC Service Module Installer                                        0
Intel(R) Ethernet Server Adapter X710-DA2 for OCP - 3C:FD:FE:4F:09:C0 19.0.12
Disk 2 in Backplane 1 of RAID Controller in Mezzanine 1               KSC8
Disk 11 in Backplane 1 of RAID Controller in Mezzanine 1              BS05
Intel(R) Gigabit I350-t LOM - 80:18:44:7A:13:C5                       19.0.12
Disk 3 in Backplane 1 of RAID Controller in Mezzanine 1               AS0E
Disk 6 in Backplane 1 of RAID Controller in Mezzanine 1               EC02
Disk 8 in Backplane 1 of RAID Controller in Mezzanine 1               DABB
Disk 0 on Integrated AHCI controller 1                                DL42
Disk 0 in Backplane 1 of RAID Controller in Mezzanine 1               SSC3
BOSS-S1                                                               2.6.13.3022
BIOS                                                                  2.3.10
Dell OS Driver Pack, 19.04.05, A00                                    19.04.05
Integrated Dell Remote Access Controller                              3.34.34.34
Dell 64 Bit uEFI Diagnostics, version 4301, 4301A34, 4301.35          4301A34
System CPLD                                                           1.0.7
Lifecycle Controller                                                  3.34.34.34
BIOS                                                                  2.4.7
Integrated Dell Remote Access Controller                              3.36.36.36

**Comment by lucien62** [comment]
Thank you @texroemer 
I’m going to compare the code before and after your change. I’m interested to know what changed. I like to use powershell but i skipped a bit on the basics.

**Comment by lucien62** [comment]
I compared the code, before and after, it's not as simple as I was expecting. I guess it's because i'm not familiar with APIs.
It's interesting, it looks like I could reuse this code to get inventory of other 'sections' in the iDrac.

**Comment by texroemer** [comment]
GET result will come back in BasicHtmlWebResponseObject type.

Example:

StatusCode        : 200
StatusDescription : OK
Content           : {"@odata.context":"/redfish/v1/$metadata#SoftwareInventoryCollection.SoftwareInventoryCollection","@odata.id":"/redfish/v1/UpdateService/FirmwareInventory","@odata.type":"#SoftwareInve
                    ntoryCollection....
RawContent        : HTTP/1.1 200 OK
                    Allow: POST
                    Link: </redfish/v1/Schemas/SoftwareInventoryCollection.json>;rel=describedby
                    OData-Version: 4.0
                    Access-Control-Allow-Origin: *
                    X-Frame-Options: DENY
                    Strict-Transport-...
Forms             : 
Headers           : {[Allow, POST], [Link, </redfish/v1/Schemas/SoftwareInventoryCollection.json>;rel=describedby], [OData-Version, 4.0], [Access-Control-Allow-Origin, *]...}
Images            : {}
InputFields       : {}
Links             : {}
ParsedHtml        : 
RawContentLength  : 57792

When you try to get only a specific property from the output, (example "Content"), it will return the value in string object. Now the old script code was taking this string value and parsing it. The new script code, i'm now using "ConvertFrom-Json" which changes the object to PSCustomObject which allows you to parse the properties, now supports passing the output into a variable.

**Comment by lucien62** [comment]
I copy pasted your code and extracted only the part that returns the firmware inventory info and I'm trying to understand what these lines are used for:

```
$u = "https://$idrac_ip/redfish/v1/UpdateService/FirmwareInventory"

# GET command to get software inventory for all devices
**$result = Invoke-WebRequest -Uri $u -Credential $credential -Method Get -UseBasicParsing -Headers @{"Accept"="application/json"} 
$ETag=$result.Headers.ETag
$matches = ([regex]'Installed-.+?}').Matches($result)
$new_count=$matches.count - 1**
```
Because using only the next lines will get me the firmware info already:
```
$expand_query ='?$expand=*($levels=1)'
$uri = "https://$idrac_ip/redfish/v1/UpdateService/FirmwareInventory$expand_query"
try
{
$get_result = Invoke-WebRequest -Uri $uri -Credential $credential -Method Get -UseBasicParsing -Headers @{"Accept"="application/json"} -ErrorVariable RespErr
}
catch
{
Write-Host
$RespErr
return
}
$get_fw_inventory = $get_result.Content | ConvertFrom-Json
$get_fw_inventory.Members

return
```

**Comment by texroemer** [comment]
Thanks for pointing this out, forgot to clean up unused code in the cmdlet. 

This code:

$matches = ([regex]'Installed-.+?}').Matches($result)
$new_count=$matches.count - 1**

is no longer used since i don't parse the GET output anymore as a string. Getting the ETag should only be used when performing firmware update which i moved this code to the correct section.

I uploaded new cmdlet to GitHub.
