### ISSUE TITLE
CheckConsistencyVirtualDiskREDFISH.py typo in double quote escape

### ISSUE THREAD

**Issue by yafrank** [dell/iDRAC-Redfish-Scripting#95]
Hi, 
    The double quote escape for -vv help should be prior to it.
diff CheckConsistencyVirtualDiskREDFISH.py.orig CheckConsistencyVirtualDiskREDFISH.py
30c30
< parser.add_argument('-vv', help='Get current server storage controller virtual disks detailed information, pass in storage controller FQDD, Example "\RAID.Integrated.1-1\"', required=False)
---
> parser.add_argument('-vv', help='Get current server storage controller virtual disks detailed information, pass in storage controller FQDD, Example \"RAID.Integrated.1-1\"', required=False)

**Comment by texroemer** [comment]
Thanks @yafrank 

Typo has been corrected and updated script uploaded.
