### ISSUE TITLE
DeviceFirmwareDellUpdateServiceREDFISH.py filename case converting to lower problem

### ISSUE THREAD

**Issue by yafrank** [dell/iDRAC-Redfish-Scripting#96]
Hi,
    When trying to use DeviceFirmwareDellUpdateServiceREDFISH.py for BIOS update in Ubuntu, following raised,
python DeviceFirmwareDellUpdateServiceREDFISH.py -ip XXXX -u XXXX -p XXXX -l /tmp/R740 -f BIOS_J5N3J_WN64_2.5.3.EXE -i NextReboot

- WARNING, downloading "BIOS_J5N3J_WN64_2.5.3.EXE" image payload to iDRAC
Traceback (most recent call last):
  File "DeviceFirmwareDellUpdateServiceREDFISH.py", line 341, in <module>
    download_image_payload()
  File "DeviceFirmwareDellUpdateServiceREDFISH.py", line 103, in download_image_payload
    files = {'file': (filename, open(ImagePath, 'rb'), 'multipart/form-data')}
IOError: [Errno 2] No such file or directory: '/tmp/R740/bios_j5n3j_wn64_2.5.3.exe'

    It turns out the filename is converted to lower case in download_image_payload(), but filename in Linux is case sensitive. 
frank@Lenovo-K4450:/tmp/R740$ ls 
BIOS_J5N3J_WN64_2.5.3.EXE
Diagnostics_Application_CH7FG_WN64_4301A42_4301.43.EXE
SAS-RAID_Firmware_G7N2C_WN64_25.5.6.0009_A14.EXE

    Modify as following works for me.
diff DeviceFirmwareDellUpdateServiceREDFISH.py.orig DeviceFirmwareDellUpdateServiceREDFISH.py
98c98
<     filename = file_image_name.lower()
---
>     filename = file_image_name

Regards,
Frank Wang

**Comment by texroemer** [comment]
Hi @yafrank 

Thanks for bringing this up, issue has been fixed and new script has been uploaded.

Thanks
