### ISSUE TITLE
LinkStatus of ethernet interfaces always report 'LinkUp'

### ISSUE THREAD

**Issue by digi-talo** [dell/iDRAC-Redfish-Scripting#97]
When querying the individual NIC statusses via `/redfish/v1/Systems/System.Embedded.1/EthernetInterfaces/` I noticed that the LinkStatus always reports LinkUp while in the iDrac web GUI the status is shown correctly.
Below an example:
```
{'@odata.context': '/redfish/v1/$metadata#EthernetInterface.EthernetInterface',
 '@odata.id': '/redfish/v1/Systems/System.Embedded.1/EthernetInterfaces/NIC.Integrated.1-2-1',
 '@odata.type': '#EthernetInterface.v1_4_1.EthernetInterface',
 'AutoNeg': False,
 'Description': 'Integrated NIC 1 Port 2 Partition 1',
 'FQDN': None,
 'FullDuplex': False,
 'HostName': None,
 'IPv4Addresses': [],
 'IPv4Addresses@odata.count': 0,
 'IPv6AddressPolicyTable': [],
 'IPv6AddressPolicyTable@odata.count': 0,
 'IPv6Addresses': [],
 'IPv6Addresses@odata.count': 0,
 'IPv6DefaultGateway': None,
 'IPv6StaticAddresses': [],
 'IPv6StaticAddresses@odata.count': 0,
 'Id': 'NIC.Integrated.1-2-1',
 'InterfaceEnabled': None,
 'LinkStatus': 'LinkUp',
 'Links': {'Chassis': {'@odata.id': '/redfish/v1/Chassis/System.Embedded.1'}},
 'MACAddress': 'B0:26:28:53:79:95',
 'MTUSize': None,
 'MaxIPv6StaticAddresses': None,
 'Name': 'System Ethernet Interface',
 'NameServers': [],
 'NameServers@odata.count': 0,
 'PermanentMACAddress': 'B0:26:28:53:79:95',
 'SpeedMbps': 0,
 'Status': {'Health': 'OK', 'State': 'Enabled'},
 'UefiDevicePath': 'PciRoot(0x1)/Pci(0x2,0x0)/Pci(0x0,0x1)',
 'VLAN': None}
```
![image](https://user-images.githubusercontent.com/24893896/76411586-67702800-6392-11ea-855b-71ecdd23fd6c.png)

This is on a Dell PowerEdge R640 with iDRAC Firmware Version `4.00.00.00` and BIOS Version `2.3.10`

**Comment by texroemer** [comment]
Hi @digi-talo 

This is a known bug in 4.00 iDRAC and will be fixed in 4.20 iDRAC which is scheduled to be posted this June.

For a workaround, you can run GET on URI "redfish/v1/Systems/System.Embedded.1/NetworkAdapters/NIC.Integrated.1/NetworkPorts/NIC.Integrated.1-2" which will report the correct link status.

Thanks

**Comment by digi-talo** [comment]
That seems to work but as I'm getting the URI's by looking them up it's not ideal. 
As a work around a used the `SpeedMbps` which is effectively 0 if the link is down.

**Comment by texroemer** [comment]
Hi @digi-talo 

Good to hear you a different workaround which detects link is down until 4.20 iDRAC is released.

Thanks
