### ISSUE TITLE
DeviceFirmwareDellUpdateServiceREDFISH.py -i Now stalls updating DIAG firmware 

### ISSUE THREAD

**Issue by yafrank** [dell/iDRAC-Redfish-Scripting#98]
Hi,
    When I tried updating DIAG firmware using "-i Now" after BIOS & PERC ones scheduled next reboot, it stalls. 
python DeviceFirmwareDellUpdateServiceREDFISH.py -ip XXXX -u XXXX -p XXXX -l /tmp/R740 -f Diagnostics_Application_CH7FG_WN64_4301A42_4301.43.EXE -i Now

- WARNING, downloading "Diagnostics_Application_CH7FG_WN64_4301A42_4301.43.EXE" image payload to iDRAC

- PASS: POST command passed to download image payload to iDRAC, 201 status code returned
- Firmware image version of downloaded payload is: 4301A42

- WARNING, executing POST command to create firmware update job ID
- PASS, JID_839202493045 firmware update job ID successfully created

    From iDrac webui, the DIAG one had been upgraded to 4301A42 and job was completed.
![DIAG_firmware](https://user-images.githubusercontent.com/33822940/76482785-2cccc500-6450-11ea-8730-41377cfd2299.png)

![diag_jobid](https://user-images.githubusercontent.com/33822940/76482734-fee78080-644f-11ea-8c64-14f8cf572779.png)

    Manual reboot performed and BIOS & PERC ones updated as expected, but the DIAG one still stalls. I had to press Ctrl-C to terminate it,

^CTraceback (most recent call last):
  File "DeviceFirmwareDellUpdateServiceREDFISH.py", line 344, in <module>
    check_job_status_host_reboot()
  File "DeviceFirmwareDellUpdateServiceREDFISH.py", line 210, in check_job_status_host_reboot
    check_idrac_connection()
  File "DeviceFirmwareDellUpdateServiceREDFISH.py", line 162, in check_idrac_connection
    execute_command=subprocess.Popen(command, stdout=subprocess.PIPE, shell=True).communicate()[0]
  File "/usr/lib/python2.7/subprocess.py", line 791, in communicate
    stdout = _eintr_retry_call(self.stdout.read)
  File "/usr/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt

    The server is a NX3240 with iDRAC 3.34.34.34(Build 17). The BIOS was 2.4.8 before upgrading and 2.5.3 afterwards.

Regards,
Frank Wang

**Comment by texroemer** [comment]
Hi @yafrank 

Script was hanging due to ping command difference between Windows and Linux. I corrected this issue in the script along with a few other fixes to handle both Python 2 and 3. New version of the script has been uploaded to GitHub. 

If you still see any issues, let me know.

Thanks

**Comment by yafrank** [comment]
Tried the same in another R740 and it works as expected now.
Thanks!

**Comment by texroemer** [comment]
@yafrank 

Good to hear new script is working now.

Thanks
